force-app/main/default/objects/EnergyUseConversionMapping__mdt/EnergyUseConversionMapping__mdt.object-meta.xml
<CustomObject>
    <description
    >Custom Mapping for Energy Use Measurement Unit in Arcadia to Supported unit measurement value in SF</description>
    <label>Energy Use Conversion Mapping</label>
    <pluralLabel>Energy Use Conversion Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/EnergyUseConversionMapping__mdt/fields/ApiUnitOfMeasurementFrom__c.field-meta.xml
<CustomField>
    <fullName>ApiUnitOfMeasurementFrom__c</fullName>
    <label>API Unit Of Measurement From</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EnergyUseConversionMapping__mdt/fields/ApiUnitOfMeasurementTo__c.field-meta.xml
<CustomField>
    <fullName>ApiUnitOfMeasurementTo__c</fullName>
    <label>API Unit Of Measurement To</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EnergyUseConversionMapping__mdt/fields/ConversionRate__c.field-meta.xml
<CustomField>
    <fullName>ConversionRate__c</fullName>
    <label>Conversion Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EnergyUseConversionMappingsSelector.cls
public with sharing class EnergyUseConversionMappingsSelector extends Selector {
    public EnergyUseConversionMappingsSelector() {
        super(Schema.EnergyUseConversionMapping__mdt.SObjectType);
    }

    public EnergyUseConversionMappingsSelector(Boolean enforceCRUD, Boolean enforceFLS, Boolean enforceShr) {
        super(Schema.EnergyUseConversionMapping__mdt.SObjectType, enforceCRUD, enforceFLS, enforceShr);
    }

    /**
     * Returns a Set that has all of the default fields.
     * @return   Set of Strings that contain the default fields for this object
     */
    public override Set<String> getDefaultFields() {
        return new Set<String>{
            'Id',
            'DeveloperName',
            'ApiUnitOfMeasurementFrom__c',
            'ConversionRate__c',
            'ApiUnitOfMeasurementTo__c'
        };
    }
}