force-app/main/default/objects/EnergyUseConversionMapping__mdt/EnergyUseConversionMapping__mdt.object-meta.xml
<CustomObject>
    <description
    >Custom Mapping for Energy Use Measurement Unit in Arcadia to Supported unit measurement value in SF</description>
    <label>Energy Use Conversion Mapping</label>
    <pluralLabel>Energy Use Conversion Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/EnergyUseConversionMapping__mdt/fields/ApiUnitOfMeasurementTo__c.field-meta.xml
<CustomField>
    <fullName>ApiUnitOfMeasurementTo__c</fullName>
    <label>API Unit Of Measurement To</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EnergyUseConversionMapping__mdt/fields/ConversionRate__c.field-meta.xml
<CustomField>
    <fullName>ConversionRate__c</fullName>
    <label>Conversion Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/StnryAssetEnrgyUse/fields/UtilityMeterUsage__c.field-meta.xml
<CustomField>
    <fullName>UtilityMeterUsage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A custom field for the meter usage data from which this record was derived.</description>
    <inlineHelpText>A custom field for the meter usage data from which this record was derived.</inlineHelpText>
    <label>Utility Meter Usage</label>
    <referenceTo>UtilityMeterUsage__c</referenceTo>
    <relationshipLabel>Stationary Asset Energy Uses</relationshipLabel>
    <relationshipName>StationaryAssetEnergyUses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityMeter__c/UtilityMeter__c.object-meta.xml
<CustomObject>
    <description>A custom object (created by the Urjanet Connect app) to store utility meter information</description>
    <label>Utility Meter</label>
    <nameField>
        <label>Utility Meter Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Meters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityMeter__c/fields/ProviderName__c.field-meta.xml
<CustomField>
    <fullName>ProviderName__c</fullName>
    <description>Provider Name for the meter on Arcadia System.</description>
    <externalId>true</externalId>
    <inlineHelpText>Provider Name for the meter on Arcadia System.</inlineHelpText>
    <label>Arcadia Utility Provider</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityMeter__c/fields/ServiceType__c.field-meta.xml
<CustomField>
    <fullName>ServiceType__c</fullName>
    <description>The meter’s service type.</description>
    <inlineHelpText>The meter’s service type.</inlineHelpText>
    <label>Service Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityMeter__c/fields/StationaryAssetEnvironmentalSource__c.field-meta.xml
<CustomField>
    <fullName>StationaryAssetEnvironmentalSource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Stationary Asset Environmental Source for this Utility Meter.</description>
    <inlineHelpText>The Stationary Asset Environmental Source for this Utility Meter.</inlineHelpText>
    <label>Stationary Asset Environmental Source</label>
    <referenceTo>StnryAssetEnvrSrc</referenceTo>
    <relationshipLabel>Utility Meters</relationshipLabel>
    <relationshipName>UtilityMeters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityMeterUsage__c/UtilityMeterUsage__c.object-meta.xml
<CustomObject>
    <description>A custom object (created by the Urjanet Connect app) to store utility meter usage data.</description>
    <label>Utility Meter Usage</label>
    <nameField>
        <label>Utility Meter Usage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Meter Usages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityMeterUsage__c/fields/MeasuredUsage__c.field-meta.xml
<CustomField>
    <fullName>MeasuredUsage__c</fullName>
    <description>Represents actual consumption at the meter location.</description>
    <inlineHelpText
    >Represents actual consumption at the meter location. (Editing this field will trigger the "Manually Updated" field for this asset)</inlineHelpText>
    <label>Measured Usage</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UtilityMeterUsage__c/fields/PeriodEnd__c.field-meta.xml
<CustomField>
    <fullName>PeriodEnd__c</fullName>
    <description>Date that the billing period ended.</description>
    <inlineHelpText
    >Date that the billing period ended. (Editing this field will trigger the "Manually Updated" field for this asset)</inlineHelpText>
    <label>Period End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/UtilityMeterUsage__c/fields/PeriodStart__c.field-meta.xml
<CustomField>
    <fullName>PeriodStart__c</fullName>
    <description>Date that the billing period started.</description>
    <inlineHelpText
    >Date that the billing period started. (Editing this field will trigger the "Manually Updated" field for this asset)
    </inlineHelpText>
    <label>Period Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/UtilityMeterUsage__c/fields/UsageUnit__c.field-meta.xml
<CustomField>
    <fullName>UsageUnit__c</fullName>
    <description>The meter’s usage unit of measure.</description>
    <inlineHelpText
    >The meter’s usage unit of measure. (Editing this field will trigger the "Manually Updated" field for this asset)</inlineHelpText>
    <label>Usage Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityMeterUsage__c/fields/UtilityMeter__c.field-meta.xml
<CustomField>
    <fullName>UtilityMeter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Utility Meter for this Utility Meter Usage record.</description>
    <inlineHelpText>The Utility Meter for this Utility Meter Usage record.</inlineHelpText>
    <label>Utility Meter</label>
    <referenceTo>UtilityMeter__c</referenceTo>
    <relationshipLabel>Utility Meter Usages</relationshipLabel>
    <relationshipName>UtilityMeterUsages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/StationaryAssetEnergyUseService.cls
public with sharing class StationaryAssetEnergyUseService {
    public StationaryAssetEnergyUseService() {
    }

    public static void createStationaryAssetEnergyUses(UtilityMeterUsage__c meterUsage) {
        if (
            meterUsage != null &&
            meterUsage.PeriodStart__c != null &&
            meterUsage.PeriodEnd__c != null &&
            meterUsage.MeasuredUsage__c != null
        ) {
            //Get the conversion multiplier to be used to convert the usage value from the API measurement to SF supported unit.
            Decimal conversionMultiplier = 1;
            String sfSupportedUnit;
            String usageUnitValue = (meterUsage.UsageUnit__c != null
                ? meterUsage.UsageUnit__c.toLowercase()
                : meterUsage.UsageUnit__c);
            Map<String, EnergyUseConversionMapping__mdt> mapConversionFactor = UrjanetUtils.getEnergyUseConversionMappings();

            if (mapConversionFactor.containsKey(usageUnitValue)) {
                EnergyUseConversionMapping__mdt energyUseConversionMapping = mapConversionFactor.get(usageUnitValue);
                conversionMultiplier = energyUseConversionMapping.ConversionRate__c;
                sfSupportedUnit = energyUseConversionMapping.ApiUnitOfMeasurementTo__c;
            } else {
                Logger.getInstance()
                    .log(
                        StationaryAssetEnergyUseService.class.getName(),
                        String.format(
                            Label.Conversion_Unsupported_Unit,
                            new List<String>{ meterUsage.UsageUnit__c, meterUsage.Id }
                        )
                    );
                return;
            }

            List<StnryAssetEnrgyUse> energyUseList = new List<StnryAssetEnrgyUse>();
            List<UrjanetUtils.SplitDateDetails> lstSplitDateRanges = UrjanetUtils.getDateRanges(meterUsage);

            try {
                for (UrjanetUtils.SplitDateDetails splitDetaildObj : lstSplitDateRanges) {
                    StnryAssetEnrgyUse energyUse = new StnryAssetEnrgyUse();
                    energyUse.StartDate = splitDetaildObj.startDate;
                    energyUse.EndDate = splitDetaildObj.endDate;
                    energyUseList.add(energyUse);
                }

                // Running in System context, ignore CRUD/FLS and Sharing
                Database.DMLOptions option = new Database.DMLOptions();
                option.OptAllOrNone = false;
                Logger.getInstance()
                    .log(
                        StationaryAssetEnergyUseService.class.getName(),
                        UrjanetUtils.getSObjectName(Schema.StnryAssetEnrgyUse.SObjectType),
                        Data.create(
                            populateOtherValuesForEnergyUses(
                                energyUseList,
                                meterUsage,
                                conversionMultiplier,
                                sfSupportedUnit
                            ),
                            option,
                            false,
                            false,
                            false
                        )
                    );
            } catch (DmlException e) {
                Logger.getInstance(false).log(StationaryAssetEnergyUseService.class.getName(), e);
            }
        }
    }

    private static List<StnryAssetEnrgyUse> populateOtherValuesForEnergyUses(
        List<StnryAssetEnrgyUse> energyUses,
        UtilityMeterUsage__c meterUsage,
        Decimal conversionMultiplier,
        String sfSupportedUnit
    ) {
        if (
            meterUsage == null ||
            meterUsage.PeriodStart__c == null ||
            meterUsage.PeriodEnd__c == null ||
            meterUsage.MeasuredUsage__c == null
        ) {
            return new List<StnryAssetEnrgyUse>();
        }

        Integer noOfDays = meterUsage.PeriodStart__c.daysBetween(meterUsage.PeriodEnd__c) + 1;
        Decimal measuredUsageValue = meterUsage.MeasuredUsage__c * conversionMultiplier;
        Decimal perDayMeasure = measuredUsageValue / noOfDays;
        Map<String, String> fuelTypeMappings = UrjanetUtils.getServiceToFuelTypeMappings();

        for (StnryAssetEnrgyUse energyUse : energyUses) {
            energyUse.StnryAssetEnvrSrcId = meterUsage.UtilityMeter__r?.StationaryAssetEnvironmentalSource__c;
            energyUse.SupplierId = meterUsage.UtilityMeter__r
                ?.StationaryAssetEnvironmentalSource__r
                ?.UtilityAccount__r
                ?.UtilityCredential__r
                ?.ProviderName__c;
            energyUse.FuelConsumptionUnit = sfSupportedUnit;
            if (
                meterUsage.UtilityMeter__r?.ServiceType__c != null &&
                fuelTypeMappings.containsKey(meterUsage.UtilityMeter__r?.ServiceType__c)
            ) {
                energyUse.FuelType = fuelTypeMappings.get(meterUsage.UtilityMeter__r?.ServiceType__c);
            } else {
                Logger.getInstance()
                    .log(
                        StationaryAssetEnergyUseService.class.getName(),
                        String.format(
                            Label.Conversion_Unsupported_FuelType,
                            new List<String>{ meterUsage.UtilityMeter__r?.ServiceType__c, meterUsage.Id }
                        )
                    );
                continue;
            }
            energyUse.FuelConsumption = (energyUse.StartDate.daysBetween(energyUse.EndDate) + 1) * perDayMeasure;
            energyUse.UtilityMeterUsage__c = meterUsage.Id;
            energyUse.Name =
                meterUsage.UtilityMeter__r?.StationaryAssetEnvironmentalSource__r?.Name +
                ' - ' +
                DateTime.newInstance(energyUse.StartDate.year(), energyUse.StartDate.month(), energyUse.StartDate.day())
                    .format('MMM') +
                ' - ' +
                String.valueOf(energyUse.StartDate.year());
        }
        return energyUses;
    }
}