force-app/main/default/objects/UtilityMeter__c/UtilityMeter__c.object-meta.xml
<CustomObject>
    <description>A custom object (created by the Urjanet Connect app) to store utility meter information</description>
    <label>Utility Meter</label>
    <nameField>
        <label>Utility Meter Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Meters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityMeter__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates if an meter is active (meaning Urjanet is considering the meter to be valid).</description>
    <inlineHelpText>Indicates if an meter is active (meaning Urjanet is considering the meter to be valid).</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UtilityMeter__c/fields/PodNumber__c.field-meta.xml
<CustomField>
    <fullName>PodNumber__c</fullName>
    <description>The point of delivery number in deregulated markets. This is an independent identifier for meter location and used by all utility companies in deregulated markets.</description>
    <inlineHelpText>The point of delivery number in deregulated markets. This is an independent identifier for meter location and used by all utility companies in deregulated markets.</inlineHelpText>
    <label>Pod Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityMeter__c/fields/ServiceType__c.field-meta.xml
<CustomField>
    <fullName>ServiceType__c</fullName>
    <description>The meter’s service type.</description>
    <inlineHelpText>The meter’s service type.</inlineHelpText>
    <label>Service Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityMeter__c/fields/StationaryAssetEnvironmentalSource__c.field-meta.xml
<CustomField>
    <fullName>StationaryAssetEnvironmentalSource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Stationary Asset Environmental Source for this Utility Meter.</description>
    <inlineHelpText>The Stationary Asset Environmental Source for this Utility Meter.</inlineHelpText>
    <label>Stationary Asset Environmental Source</label>
    <referenceTo>StnryAssetEnvrSrc</referenceTo>
    <relationshipLabel>Utility Meters</relationshipLabel>
    <relationshipName>UtilityMeters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityMeterUsage__c/UtilityMeterUsage__c.object-meta.xml
<CustomObject>
    <description>A custom object (created by the Urjanet Connect app) to store utility meter usage data.</description>
    <label>Utility Meter Usage</label>
    <nameField>
        <label>Utility Meter Usage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Meter Usages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityMeterUsage__c/fields/Arcadia_Statement_ID__c.field-meta.xml
<CustomField>
    <fullName>Arcadia_Statement_ID__c</fullName>
    <description>It is used to store the statement Id of meter usage</description>
    <inlineHelpText>Unique ID for the statement on Arcadia system</inlineHelpText>
    <label>Arcadia Statement ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityMeterUsage__c/fields/MeasuredUsage__c.field-meta.xml
<CustomField>
    <fullName>MeasuredUsage__c</fullName>
    <description>Represents actual consumption at the meter location.</description>
    <inlineHelpText
    >Represents actual consumption at the meter location. (Editing this field will trigger the "Manually Updated" field for this asset)</inlineHelpText>
    <label>Measured Usage</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UtilityMeterUsage__c/fields/MeasuredUsageInText__c.field-meta.xml
<CustomField>
    <fullName>MeasuredUsageInText__c</fullName>
    <description>Represents actual consumption at the meter location.</description>
    <inlineHelpText>Measured Usage in Text</inlineHelpText>
    <label>Measured Usage In Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>
    

force-app/main/default/objects/UtilityMeterUsage__c/fields/PeriodEnd__c.field-meta.xml
<CustomField>
    <fullName>PeriodEnd__c</fullName>
    <description>Date that the billing period ended.</description>
    <inlineHelpText
    >Date that the billing period ended. (Editing this field will trigger the "Manually Updated" field for this asset)</inlineHelpText>
    <label>Period End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/UtilityMeterUsage__c/fields/PeriodStart__c.field-meta.xml
<CustomField>
    <fullName>PeriodStart__c</fullName>
    <description>Date that the billing period started.</description>
    <inlineHelpText
    >Date that the billing period started. (Editing this field will trigger the "Manually Updated" field for this asset)
    </inlineHelpText>
    <label>Period Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/UtilityMeterUsage__c/fields/To_Be_Ignored__c.field-meta.xml
<CustomField>
    <fullName>To_Be_Ignored__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if an meter usage is to be ignored for downstream data creation (meaning Urjanet is considering the meter usage to be valid).</description>
    <inlineHelpText>Indicates if an meter usage is to be ignored for downstream data creation (meaning Urjanet is considering the meter usage to be valid).</inlineHelpText>
    <label>To Be Ignored</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UtilityMeterUsage__c/fields/UsageUnit__c.field-meta.xml
<CustomField>
    <fullName>UsageUnit__c</fullName>
    <description>The meter’s usage unit of measure.</description>
    <inlineHelpText
    >The meter’s usage unit of measure. (Editing this field will trigger the "Manually Updated" field for this asset)</inlineHelpText>
    <label>Usage Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityMeterUsage__c/fields/UtilityMeter__c.field-meta.xml
<CustomField>
    <fullName>UtilityMeter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Utility Meter for this Utility Meter Usage record.</description>
    <inlineHelpText>The Utility Meter for this Utility Meter Usage record.</inlineHelpText>
    <label>Utility Meter</label>
    <referenceTo>UtilityMeter__c</referenceTo>
    <relationshipLabel>Utility Meter Usages</relationshipLabel>
    <relationshipName>UtilityMeterUsages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UtilityMeterAndUsageUpdateBatch.cls
public with sharing class UtilityMeterAndUsageUpdateBatch implements Database.Batchable<sObject>, Database.AllowsCallouts {
    public UtilityMeterAndUsageUpdateBatch() {
    }

    public Database.Querylocator start(Database.BatchableContext bc) {
        UtilityMeterUsageSelector selector = new UtilityMeterUsageSelector(false, false, false);
        Logger.getInstance(false)
            .log(
                UtilityMeterAndUsageUpdateBatch.class.getName(),
                Logger.Level.INFO,
                'Utility Meter And Usage Update Sync Batch Started'
            );

        return selector.getUsagesToBeCheckedForDuplicacy();
    }

    public void execute(Database.BatchableContext bc, List<sObject> scope) {
        try {
            Set<Id> recordIds = new Set<Id>();
            for (sObject record : scope) {
                recordIds.add(record.Id);
            }
            // Querying to get the updated Records
            List<UtilityMeterUsage__c> updatedRecords = [
                SELECT
                    Id,
                    MeasuredUsage__c,
                    UsageUnit__c,
                    MeasuredUsageInText__c,
                    PeriodStart__c,
                    PeriodEnd__c,
                    Arcadia_Statement_ID__c,
                    To_Be_Ignored__c,
                    UtilityMeter__c,
                    UtilityMeter__r.PodNumber__c,
                    UtilityMeter__r.ServiceType__c,
                    UtilityMeter__r.StationaryAssetEnvironmentalSource__c,
                    UtilityMeter__r.Enabled__c
                FROM UtilityMeterUsage__c
                WHERE Id IN :recordIds AND To_Be_Ignored__c = FALSE AND UtilityMeter__r.Enabled__c = TRUE
                ORDER BY CreatedDate ASC
            ];

            if (!updatedRecords.isEmpty()) {
                UtilityMeterUsageService.validateMeterAndUsages(updatedRecords);
            }
        } catch (Exception e) {
            Logger.getInstance(false)
                .log(
                    UtilityMeterAndUsageUpdateBatch.class.getName(),
                    'Error in UtilityMeterAndUsageUpdateBatch: ' + e.getMessage() + ' ' + e.getStackTraceString()
                );
        }
    }

    public void finish(Database.BatchableContext bc) {
        Logger.getInstance(false)
            .log(
                UtilityMeterAndUsageUpdateBatch.class.getName(),
                Logger.Level.INFO,
                'Utility Meter And Usage Update Sync Batch Completed'
            );
        try {
            Database.executeBatch(new UsageAndDownstreamDataDeletionBatch());
        } catch (Exception e) {
            Logger.getInstance(false)
                .log(
                    UsageAndDownstreamDataDeletionBatch.class.getName(),
                    'Error in UsageAndDownstreamDataDeletionBatch: ' + e.getMessage() + ' ' + e.getStackTraceString()
                );
        }
    }
}