force-app/main/default/objects/UtilityMeterUsage__c/UtilityMeterUsage__c.object-meta.xml
<CustomObject>
    <description>A custom object (created by the Urjanet Connect app) to store utility meter usage data.</description>
    <label>Utility Meter Usage</label>
    <nameField>
        <label>Utility Meter Usage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Meter Usages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityMeterUsage__c/fields/UrjanetId__c.field-meta.xml
<CustomField>
    <fullName>UrjanetId__c</fullName>
    <description>Unique ID for the meter usage on Arcadia system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique ID for the meter usage on Arcadia system.</inlineHelpText>
    <label>ArcadiaId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/UpdateMeterUsageQueue.cls
public class UpdateMeterUsageQueue implements Queueable {
    private List<UtilityMeterUsage__c> meterUsageToUpdate;
    private List<Id> recordIDsToDeleteEnergy;
    private List<Id> recordIDsToDeleteWater;

    public UpdateMeterUsageQueue(
        List<UtilityMeterUsage__c> meterUsageToUpdate,
        List<Id> recordIDsToDeleteEnergy,
        List<Id> recordIDsToDeleteWater
    ) {
        this.meterUsageToUpdate = meterUsageToUpdate;
        this.recordIDsToDeleteEnergy = recordIDsToDeleteEnergy;
        this.recordIDsToDeleteWater = recordIDsToDeleteWater;
    }

    public void execute(QueueableContext context) {
        Database.DMLOptions option = new Database.DMLOptions();
        option.OptAllOrNone = false;

        if (!meterUsageToUpdate.isEmpty()) {
            try {
                Logger.getInstance(false)
                    .log(
                        UpdateMeterUsageQueue.class.getName(),
                        Logger.Level.DEBUG,
                        'Updating Meter Usage: ' + meterUsageToUpdate.size()
                    );
                Data.upsurt(
                    meterUsageToUpdate,
                    Schema.UtilityMeterUsage__c.fields.UrjanetId__c,
                    option,
                    false,
                    false,
                    false,
                    null
                );
            } catch (DmlException e) {
                Logger.getInstance().log(UpdateMeterUsageQueue.class.getName(), Logger.Level.ERROR, e.getMessage());
            }
        }
        UrjanetUtils.deleteMeterUsagesAndDownStreamData(recordIDsToDeleteEnergy, recordIDsToDeleteWater);
    }
}