force-app/main/CSLogger/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Log Object to catch successes and errors</description>
    <label>Arcadia Log</label>
    <nameField>
        <displayFormat>LOG-{0000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Arcadia Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier/fields/ElectricityEmissionsFactors__c.field-meta.xml
<CustomField>
    <fullName>ElectricityEmissionsFactors__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
    >A custom field so that the Urjanet app can create Stationary Asset Environmental Sources (since the emissions factor fields are required).</description>
    <inlineHelpText
    >The selection placed in this field will be used as the "Electricity Emissions Factors" field selection whenever the Urjanet App automatically creates Stationary Asset Environmental Sources from this Supplier.</inlineHelpText>
    <label>Electricity Emissions Factors</label>
    <referenceTo>ElectricityEmssnFctrSet</referenceTo>
    <relationshipLabel>Supplier</relationshipLabel>
    <relationshipName>Supplier</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier/fields/OtherEmissionsFactors__c.field-meta.xml
<CustomField>
    <fullName>OtherEmissionsFactors__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
    >A custom field so that the Urjanet app can create Stationary Asset Environmental Sources (since the emissions factor fields are required).</description>
    <inlineHelpText
    >The selection placed in this field will be used as the "Other Emissions Factors" field selection whenever the Urjanet App automatically creates Stationary Asset Environmental Sources from this Supplier.</inlineHelpText>
    <label>Other Emissions Factors</label>
    <referenceTo>OtherEmssnFctrSet</referenceTo>
    <relationshipLabel>Supplier</relationshipLabel>
    <relationshipName>Supplier</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/UtilityAccount__c.object-meta.xml
<CustomObject>
    <description>A custom object (created by the Urjanet Connect app) to store utility account information</description>
    <label>Utility Account</label>
    <nameField>
        <label>Utility Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityAccount__c/fields/LastModifiedInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedInUrjanet__c</fullName>
    <description>The date that an account was modified last in the Arcadia system.</description>
    <inlineHelpText>The date that an account was modified last in the Arcadia system.</inlineHelpText>
    <label>Last Modified in Arcadia</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Supplier</referenceTo>
    <relationshipLabel>Utility Accounts</relationshipLabel>
    <relationshipName>UtilityAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/fields/UtilityCredential__c.field-meta.xml
<CustomField>
    <fullName>UtilityCredential__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Utility Credential</label>
    <referenceTo>UtilityCredential__c</referenceTo>
    <relationshipLabel>Utility Accounts</relationshipLabel>
    <relationshipName>UtilityAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/UtilityCredential__c.object-meta.xml
<CustomObject>
    <description
    >A custom object (created by the Urjanet Connect app) to store status information about utility credentials</description>
    <label>Utility Credential</label>
    <nameField>
        <label>Utility Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityCredential__c/fields/LastModifiedInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedInUrjanet__c</fullName>
    <description>The date that a credential was modified last.</description>
    <inlineHelpText>The date that a credential was modified last.</inlineHelpText>
    <label>Last Modified in Arcadia</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/ProviderName__c.field-meta.xml
<CustomField>
    <fullName>ProviderName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The commonly known name for the utility company.</description>
    <inlineHelpText>The commonly known name for the utility company.</inlineHelpText>
    <label>Provider Name</label>
    <referenceTo>Supplier</referenceTo>
    <relationshipLabel>Utility Credentials</relationshipLabel>
    <relationshipName>UtilityCredentials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/UrjanetId__c.field-meta.xml
<CustomField>
    <fullName>UrjanetId__c</fullName>
    <description>Unique ID for the account on Arcadia system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique ID for the account on Arcadia system.</inlineHelpText>
    <label>ArcadiaId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/UtilityMeter__c/UtilityMeter__c.object-meta.xml
<CustomObject>
    <description>A custom object (created by the Urjanet Connect app) to store utility meter information</description>
    <label>Utility Meter</label>
    <nameField>
        <label>Utility Meter Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Meters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityMeter__c/fields/LastModifiedInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedInUrjanet__c</fullName>
    <description>The date that a meter was modified last in the Arcadia system.</description>
    <inlineHelpText>The date that a meter was modified last in the Arcadia system.</inlineHelpText>
    <label>Last Modified in Arcadia</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/UtilityMeter__c/fields/ProviderName__c.field-meta.xml
<CustomField>
    <fullName>ProviderName__c</fullName>
    <description>Provider Name for the meter on Arcadia System.</description>
    <externalId>true</externalId>
    <inlineHelpText>Provider Name for the meter on Arcadia System.</inlineHelpText>
    <label>Arcadia Utility Provider</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityMeter__c/fields/UrjanetId__c.field-meta.xml
<CustomField>
    <fullName>UrjanetId__c</fullName>
    <description>Unique ID for the meter on Arcadia system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique ID for the meter on Arcadia system.</inlineHelpText>
    <label>ArcadiaId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/testClasses/UtilityAccountTriggerTest.cls
@IsTest
public with sharing class UtilityAccountTriggerTest {
    @TestSetup
    static void makeData() {
        User adminUser = TestUtility.createUserAdmin('urjanetAdmin@urjanettest.com');
        System.runAs(adminUser) {
            List<SObject> lstElectricityEmissionFactorSet = Test.loadData(
                ElectricityEmssnFctrSet.sObjectType,
                'ElectricityEmissionFactorSet'
            );
            List<SObject> lstOtherEmissionFactorSet = Test.loadData(
                OtherEmssnFctrSet.sObjectType,
                'OtherEmissionFactorSet'
            );

            Account providerAccount = new Account();
            providerAccount.Name = 'Test Provider Account';
            insert providerAccount;

            Supplier provider = new Supplier();
            provider.Name = 'Test Provider';
            provider.OtherEmissionsFactors__c = lstOtherEmissionFactorSet[0].Id;
            provider.ElectricityEmissionsFactors__c = lstElectricityEmissionFactorSet[0].Id;
            provider.AccountId = providerAccount.Id;
            insert provider;

            UtilityCredential__c credential = new UtilityCredential__c();
            credential.UrjanetId__c = TestUtility.CREDENTIAL_ID;
            credential.ProviderName__c = provider.Id;
            insert credential;
        }
    }
    @IsTest
    static void UtilityAccountTriggerInsertTest() {
        User adminUser = [SELECT Id FROM User WHERE email = 'urjanetAdmin@urjanettest.com' LIMIT 1];
        Supplier supplierObj = [SELECT Id FROM Supplier LIMIT 1];

        System.runAs(adminUser) {
            UtilityCredential__c credential = [
                SELECT Id
                FROM UtilityCredential__c
                WHERE UrjanetId__c = :TestUtility.CREDENTIAL_ID
            ];
            UtilityAccount__c account = new UtilityAccount__c();
            account.UtilityCredential__c = credential.Id;
            account.UrjanetId__c = '1234abcd-2345-cd34-1234-1232434cdede';
            account.Supplier__c = supplierObj.Id;

            StaticResourceCalloutMock mock = TestUtility.getStaticResourceCalloutMock('MetersByAccountResponse', 200);
            Test.startTest();
            insert account;
            Test.stopTest();
            UtilityAccount__c accountQueried = [SELECT Id, UrjanetId__c FROM UtilityAccount__c LIMIT 1];
            CSUtils.itShouldBe(
                'Utility Account Urjanet Id ',
                '1234abcd-2345-cd34-1234-1232434cdede',
                accountQueried.UrjanetId__c
            );
        }
    }

    @IsTest
    static void UtilityAccountTriggerUpdateTest() {
        User adminUser = [SELECT Id FROM User WHERE email = 'urjanetAdmin@urjanettest.com' LIMIT 1];
        Supplier supplierObj = [SELECT Id FROM Supplier LIMIT 1];
        System.runAs(adminUser) {
            UtilityCredential__c credential = [
                SELECT Id
                FROM UtilityCredential__c
                WHERE UrjanetId__c = :TestUtility.CREDENTIAL_ID
            ];
            UtilityAccount__c account = new UtilityAccount__c();
            account.UtilityCredential__c = credential.Id;
            account.UrjanetId__c = '1234abcd-2345-cd34-1234-1232434cdede';
            account.Supplier__c = supplierObj.Id;
            account.LastModifiedInUrjanet__c = Datetime.now().addMinutes(-1);
            StaticResourceCalloutMock mock = TestUtility.getStaticResourceCalloutMock('MetersByAccountResponse', 200);
            insert account;

            account.Name = 'test Updated';
            account.LastModifiedInUrjanet__c = Datetime.now();
            Test.startTest();
            update account;
            Test.stopTest();
            UtilityAccount__c accountQueried = [SELECT Id, Name, UrjanetId__c FROM UtilityAccount__c LIMIT 1];
            CSUtils.itShouldBe('Utility Account Name ', 'test Updated', accountQueried.Name);
            List<UtilityMeter__c> meterQueried = [SELECT Id, UrjanetId__c FROM UtilityMeter__c];
            CSUtils.itShouldBe('Meter Id ', '1ecd6c27-b21e-d108-ba69-12345678', meterQueried[0].UrjanetId__c);
        }
    }

    @IsTest
    static void UtilityAccountTriggerUpdateTestErrorResponse() {
        User adminUser = [SELECT Id FROM User WHERE email = 'urjanetAdmin@urjanettest.com' LIMIT 1];
        Supplier supplierObj = [SELECT Id FROM Supplier LIMIT 1];
        System.runAs(adminUser) {
            UtilityCredential__c credential = [
                SELECT Id
                FROM UtilityCredential__c
                WHERE UrjanetId__c = :TestUtility.CREDENTIAL_ID
            ];
            TestUtility.insertLastSyncDetails();
            UtilityAccount__c account = new UtilityAccount__c();
            account.UtilityCredential__c = credential.Id;
            account.UrjanetId__c = '1234abcd-2345-cd34-1234-1232434cdede';
            account.Supplier__c = supplierObj.Id;

            StaticResourceCalloutMock mock = TestUtility.getStaticResourceCalloutMock(
                'MetersByAccountResponseFailure',
                400
            );
            insert account;
            List<Log__c> logbeforeAPICall = [SELECT Id FROM Log__c LIMIT 1];
            CSUtils.itShouldBe('Expected number of records in Log Object', 0, logBeforeAPICall.size());

            account.Name = 'test Updated';
            Test.startTest();
            update account;
            Test.stopTest();
            UtilityAccount__c accountQueried = [SELECT Id, Name, UrjanetId__c FROM UtilityAccount__c LIMIT 1];
            CSUtils.itShouldBe('Utility Account Name ', 'test Updated', accountQueried.Name);
            List<Log__c> logAfterAPICall = [SELECT Id, Message__c FROM Log__c LIMIT 1];
            CSUtils.itShouldBe('Error message', '400 Bad request', logAfterAPICall[0].Message__c.trim());
        }
    }
    @IsTest
    static void UtilityAccountTriggerUpdateTestNullId() {
        User adminUser = [SELECT Id FROM User WHERE email = 'urjanetAdmin@urjanettest.com' LIMIT 1];
        Supplier supplierObj = [SELECT Id FROM Supplier LIMIT 1];
        System.runAs(adminUser) {
            UtilityCredential__c credential = [
                SELECT Id
                FROM UtilityCredential__c
                WHERE UrjanetId__c = :TestUtility.CREDENTIAL_ID
            ];
            UtilityAccount__c account = new UtilityAccount__c();
            account.UtilityCredential__c = credential.Id;
            account.UrjanetId__c = '1234abcd-2345-cd34-1234-1232434cdede';
            account.Supplier__c = supplierObj.Id;

            insert account;
            List<Log__c> logbeforeAPICall = [SELECT Id FROM Log__c LIMIT 1];
            CSUtils.itShouldBe('Expected number of records in Log Object', 0, logBeforeAPICall.size());

            account.Name = 'test Updated';
            account.UrjanetId__c = null;

            Test.startTest();
            update account;
            Test.stopTest();
            UtilityAccount__c accountQueried = [SELECT Id, Name, UrjanetId__c FROM UtilityAccount__c LIMIT 1];
            CSUtils.itShouldBe('Utility Account Name ', 'test Updated', accountQueried.Name);
        }
    }
}