force-app/main/CSLogger/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Log Object to catch successes and errors</description>
    <label>Arcadia Log</label>
    <nameField>
        <displayFormat>LOG-{0000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Arcadia Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/CSLogger/objects/Log__c/fields/LogTitle__c.field-meta.xml
<CustomField>
    <fullName>LogTitle__c</fullName>
    <description>A field that will allow the end-user to search the log title</description>
    <label>Log Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/testClasses/GetCredentialsResponseParserTest.cls
@isTest
public with sharing class GetCredentialsResponseParserTest {
    @isTest
    static void getCredentialsExceptionTest() {
        List<Log__c> logbeforeAPICall = [SELECT Id FROM Log__c LIMIT 1];
        CSUtils.itShouldBe('Expected number of records in Log Object', 0, logBeforeAPICall.size());

        Test.startTest();
        UrjanetResponse response = new GetCredentialsResponseParser().parseResponse(null);
        Test.stopTest();

        List<Log__c> logAfterAPICall = [SELECT Id, Message__c, LogTitle__c FROM Log__c LIMIT 1];
        CSUtils.itShouldBe('Number of records in Log Object', 1, logAfterAPICall.size());
        CSUtils.itShouldBe('Error message', (response.ex).getMessage(), logAfterAPICall[0].Message__c.trim());
        CSUtils.itShouldBe(
            'Error message in Log title',
            UrjanetConstants.CREDENTIALS_API_ERROR_MESSAGE,
            logAfterAPICall[0].LogTitle__c
        );
    }

    @isTest
    static void getCredentialsResponseTest() {
        StaticResourceCalloutMock mock = TestUtility.getStaticResourceCalloutMock('GetCredentialsResponse', 200);
        HttpResponse mockHttpResponse = mock.respond(new HttpRequest());

        Test.startTest();
        UrjanetResponse response = new GetCredentialsResponseParser().parseResponse(mockHttpResponse);
        Test.stopTest();
        CSUtils.itShouldBe(
            'ResponseType should be Credential correlationId ',
            'CREDENTIALS_BY_CORRELATION_ID',
            response.responseType
        );
        CSUtils.itShouldBe('There should be no error message ', null, response.errorMsg);
        CSUtils.itShouldBe(
            'Username should be Test_Name_1 ',
            'Test_Name_1',
            ((GetCredentialsResponse) response).embedded.credentials[0].username
        );
        CSUtils.itShouldBe(
            'Staus should be OK ',
            'OK',
            ((GetCredentialsResponse) response).embedded.credentials[0].status
        );
        CSUtils.itShouldBe(
            'Correlation Id should match ',
            '001TestCorrelationId',
            ((GetCredentialsResponse) response).embedded.credentials[0].correlationId
        );
    }

    @isTest
    static void getCredentialsResponseErrorTest() {
        StaticResourceCalloutMock mock = TestUtility.getStaticResourceCalloutMock('GetCredentialsResponseFailure', 400);
        HttpResponse mockHttpResponse = mock.respond(new HttpRequest());

        Test.startTest();
        UrjanetResponse response = new GetCredentialsResponseParser().parseResponse(mockHttpResponse);
        Test.stopTest();

        CSUtils.itShouldBe('Message should be ', ' Message =Invalid search.', response.message);
        CSUtils.itShouldBe('Error message should be ', '400 Bad request', response.errorMsg);
    }
}