force-app/main/CSLogger/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Log Object to catch successes and errors</description>
    <label>Arcadia Log</label>
    <nameField>
        <displayFormat>LOG-{0000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Arcadia Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier/fields/ElectricityEmissionsFactors__c.field-meta.xml
<CustomField>
    <fullName>ElectricityEmissionsFactors__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
    >A custom field so that the Urjanet app can create Stationary Asset Environmental Sources (since the emissions factor fields are required).</description>
    <inlineHelpText
    >The selection placed in this field will be used as the "Electricity Emissions Factors" field selection whenever the Urjanet App automatically creates Stationary Asset Environmental Sources from this Supplier.</inlineHelpText>
    <label>Electricity Emissions Factors</label>
    <referenceTo>ElectricityEmssnFctrSet</referenceTo>
    <relationshipLabel>Supplier</relationshipLabel>
    <relationshipName>Supplier</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier/fields/OtherEmissionsFactors__c.field-meta.xml
<CustomField>
    <fullName>OtherEmissionsFactors__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
    >A custom field so that the Urjanet app can create Stationary Asset Environmental Sources (since the emissions factor fields are required).</description>
    <inlineHelpText
    >The selection placed in this field will be used as the "Other Emissions Factors" field selection whenever the Urjanet App automatically creates Stationary Asset Environmental Sources from this Supplier.</inlineHelpText>
    <label>Other Emissions Factors</label>
    <referenceTo>OtherEmssnFctrSet</referenceTo>
    <relationshipLabel>Supplier</relationshipLabel>
    <relationshipName>Supplier</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/UtilityCredential__c.object-meta.xml
<CustomObject>
    <description
    >A custom object (created by the Urjanet Connect app) to store status information about utility credentials</description>
    <label>Utility Credential</label>
    <nameField>
        <label>Utility Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityCredential__c/fields/LastUrjanetSyncDateTime__c.field-meta.xml
<CustomField>
    <fullName>LastUrjanetSyncDateTime__c</fullName>
    <description>Date and Time of the last sync with Arcadia</description>
    <inlineHelpText>Date and Time of the last sync with Arcadia</inlineHelpText>
    <label>Last Arcadia Sync</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/UrjanetId__c.field-meta.xml
<CustomField>
    <fullName>UrjanetId__c</fullName>
    <description>Unique ID for the account on Arcadia system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique ID for the account on Arcadia system.</inlineHelpText>
    <label>ArcadiaId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/testClasses/UtilityCredentialTriggerTest.cls
/**
 * Created by Alagu on 5/12/22.
 */

@IsTest
private class UtilityCredentialTriggerTest {
    @TestSetup
    static void makeData() {
        User adminUser = TestUtility.createUserAdmin('urjanetAdmin12@urjanettest.com');
        System.runAs(adminUser) {
            List<SObject> lstElectricityEmissionFactorSet = Test.loadData(
                ElectricityEmssnFctrSet.sObjectType,
                'ElectricityEmissionFactorSet'
            );
            List<SObject> lstOtherEmissionFactorSet = Test.loadData(
                OtherEmssnFctrSet.sObjectType,
                'OtherEmissionFactorSet'
            );

            Account providerAccount = new Account();
            providerAccount.Name = 'Test Provider Account';
            insert providerAccount;

            Supplier provider = new Supplier();
            provider.Name = 'Test Provider';
            provider.OtherEmissionsFactors__c = lstOtherEmissionFactorSet[0].Id;
            provider.ElectricityEmissionsFactors__c = lstElectricityEmissionFactorSet[0].Id;
            provider.AccountId = providerAccount.Id;
            insert provider;
        }
    }
    // This test is really just for coverage because triggers are required to have coverage. The logic performed
    // as a result of the triggers is tested thoroughly in test classes corresponding to the services that do the
    // work
    @IsTest
    static void givenUtilityCredentialRecordsInsertedUtilityCredentialRecordsExist() {
        User adminUser = [SELECT Id FROM User WHERE email = 'urjanetAdmin12@urjanettest.com' LIMIT 1];
        UtilityCredential__c credential = new UtilityCredential__c();

        System.runAs(adminUser) {
            credential.LastUrjanetSyncDateTime__c = Datetime.now();

            Test.startTest();
            insert credential;
            Test.stopTest();
        }

        List<UtilityCredential__c> credentials = [SELECT Id FROM UtilityCredential__c];
        CSUtils.itShouldBe('A credential record should exist', 1, credentials.size());
    }

    @IsTest
    static void givenUtilityCredentialRecordsUpdatedUtilityCredentialRecordsUpdatedOnDatabase() {
        User adminUser = [SELECT Id FROM User WHERE email = 'urjanetAdmin12@urjanettest.com' LIMIT 1];
        UtilityCredential__c credential = new UtilityCredential__c();
        credential.LastUrjanetSyncDateTime__c = Datetime.now();
        System.runAs(adminUser) {
            insert credential;

            credential.Name = 'Testcredential';

            Test.startTest();
            update credential;
            Test.stopTest();
        }

        List<UtilityCredential__c> credentials = [SELECT Id, Name FROM UtilityCredential__c];
        CSUtils.itShouldBe('credential name should be updated', 'Testcredential', credentials[0].Name);
    }
    @IsTest
    static void processMethodHandlesFaliureApiCall() {
        StaticResourceCalloutMock mock = TestUtility.getStaticResourceCalloutMock(
            'AccountsByCredsResponseFailure',
            200
        );
        HttpResponse mockHttpResponse = mock.respond(new HttpRequest());
        GetAccountsByCredsResponse response = (GetAccountsByCredsResponse) new GetAccountsByCredsResponseParser()
            .parseResponse(mockHttpResponse);

        User adminUser = [SELECT Id FROM User WHERE email = 'urjanetAdmin12@urjanettest.com' LIMIT 1];
        System.runAs(adminUser) {
            UtilityCredential__c credential = new UtilityCredential__c();
            credential.UrjanetId__c = TestUtility.CREDENTIAL_ID;

            Test.startTest();
            insert credential;
            Test.stopTest();
            List<Log__c> logAfterAPICall = [SELECT Id, Message__c FROM Log__c LIMIT 1];
            CSUtils.itShouldBe('Number of records in Log Object', 1, logAfterAPICall.size());
            CSUtils.itShouldBe('Error message', response.errorMsg, logAfterAPICall[0].Message__c.trim());
        }
    }
}