force-app/main/default/objects/UrjanetConfigurationSetting__mdt/UrjanetConfigurationSetting__mdt.object-meta.xml
<CustomObject>
    <description>Custom configuration settings for the Arcadia Application</description>
    <label>Arcadia Configuration Setting</label>
    <pluralLabel>Arcadia Configuration Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/UrjanetConfigurationSetting__mdt/fields/SettingValue__c.field-meta.xml
<CustomField>
    <fullName>SettingValue__c</fullName>
    <description>The value of this config setting. See documentation for recommended values and formats.</description>
    <inlineHelpText>The value of this config setting. See documentation for recommended values and formats.</inlineHelpText>
    <label>Setting Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UrjanetSettings__c/UrjanetSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for Arcadia Connect App</description>
    <label>Arcadia Settings</label>
</CustomObject>

force-app/main/default/objects/UrjanetSettings__c/fields/OrganizationId__c.field-meta.xml
<CustomField>
    <fullName>OrganizationId__c</fullName>
    <description
    >A field to store Arcadia’s Organization Id (which is the back part of the unique URL) https://connect.urjanet.com/&lt;Organization Id&gt;</description>
    <externalId>true</externalId>
    <label>Organization Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/UtilityCredential__c.object-meta.xml
<CustomObject>
    <description
    >A custom object (created by the Urjanet Connect app) to store status information about utility credentials</description>
    <label>Utility Credential</label>
    <nameField>
        <label>Utility Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityCredential__c/fields/CorrelationID__c.field-meta.xml
<CustomField>
    <fullName>CorrelationID__c</fullName>
    <description>A unique number to identify this utility credential record within Urjanet&apos;s sytem.</description>
    <externalId>true</externalId>
    <inlineHelpText>A unique number to identify this utility credential record within Urjanet&apos;s sytem.</inlineHelpText>
    <label>Correlation ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description
    >Credential-level statuses that let you know if there are any issues accessing the provider portal, the data, or with the credential itself.</description>
    <inlineHelpText
    >Credential-level statuses that let you know if there are any issues accessing the provider portal, the data, or with the credential itself.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>PENDING</fullName>
                <label>Pending</label>
            </value>
            <value>
                <fullName>SENT_TO_URJANET</fullName>
                <label>Sent To Arcadia</label>
            </value>
            <value>
                <fullName>ACTION_REQUIRED</fullName>
                <label>Action Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/UrjanetId__c.field-meta.xml
<CustomField>
    <fullName>UrjanetId__c</fullName>
    <description>Unique ID for the account on Arcadia system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique ID for the account on Arcadia system.</inlineHelpText>
    <label>ArcadiaId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/UrjanetCanvasApp/UrjanetCanvasAppService.cls
public with sharing class UrjanetCanvasAppService {
    public UrjanetCanvasAppService() {
    }
    public static Map<String, String> getAlternatePath(String credentialId) {
        UtilityCredentialSelector selector = new UtilityCredentialSelector();
        UtilityCredential__c credentialRecord = (UtilityCredential__c) selector.getRecordById(credentialId);
        Map<String, String> pathMap = new Map<String, String>();
        String alternatePath;

        if (credentialRecord != null) {
            if (String.isBlank(credentialRecord.Status__c)) {
                String orgId = getOrgId();
                alternatePath = buildAlternatePathforInitCred(orgId, credentialRecord.CorrelationId__c);
            } else if (credentialRecord.Status__c == UrjanetConstants.CREDENTIAL_STATUS) {
                alternatePath = null;
            } else {
                if (!String.isBlank(credentialRecord.UrjanetId__c)) {
                    List<String> requestParams = new List<String>{ credentialRecord.UrjanetId__c };
                    GetUpdateUrlByCredentialResponse response = (GetUpdateUrlByCredentialResponse) new UrjanetApiClient()
                        .getUrjanetResponse(
                            UrjanetEnums.RequestType.UPDATE_URL_BY_CREDENTIAL,
                            UrjanetEnums.ApiMethod.GET,
                            requestParams
                        );

                    if (response != null && !String.isBlank(response.updateUrl)) {
                        alternatePath = buildAlternatePathforReCred(response.updateUrl);
                    } else {
                        Logger.getInstance()
                            .log(
                                UrjanetCanvasAppService.class.getName(),
                                'Error in getting update url response : ' + response.toString()
                            );
                        alternatePath = null;
                    }
                }
            }
        }
        pathMap.put('path', alternatePath);
        return pathMap;
    }

    /**
     * Get the OrgId from Custom Setting
     *
     * @return	String - Org Id
     */
    public static String getOrgId() {
        // Get the Urjanet Org Id using Org Defaults
        UrjanetSettings__c settings = UrjanetSettings__c.getOrgDefaults();
        return settings.OrganizationId__c;
    }

    private static String buildAlternatePathforInitCred(String orgId, String correlationId) {
        PageReference pageRef = new PageReference(String.escapeSingleQuotes('/' + orgId + '/canvas'));
        pageRef.getParameters().put('salesforce', 'true');
        pageRef.getParameters().put('correlationId', correlationId);
        pageRef.getParameters().put('hideFinalButtons', 'true');
        return pageRef.getUrl();
    }

    private static String buildAlternatePathforReCred(String updateUrl) {
        String baseUrl = getBaseUrl();
        PageReference pageRef = new PageReference(String.escapeSingleQuotes(updateUrl.replace(baseUrl, '')));
        pageRef.getParameters().put('salesforce', 'true');
        pageRef.getParameters().put('hideFinalButtons', 'true');
        return pageRef.getUrl();
    }

    /**
     * Update the status for Utility Credentials
     *
     * @return	void
     */
    public static void updateCredentialStatus(String credentialId) {
        // Get the Urjanet Org Id using Org Defaults
        UtilityCredential__c credential = new UtilityCredential__c(Id = credentialId);
        credential.Status__c = UrjanetConstants.CREDENTIAL_STATUS;
        Data.upsurt(credential);
    }

    /**
     * Get the baseUrl from Custom Metadata
     *
     * @return	String - baseUrl
     */
    public static String getBaseUrl() {
        UrjanetConfigurationSetting__mdt urjanetSetting = UrjanetConfigurationSetting__mdt.getInstance('Base_Url');
        return urjanetSetting.SettingValue__c;
    }
}