force-app/main/default/objects/AccessToken__c/AccessToken__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used to save the Token Details</description>
    <label>Access Token</label>
</CustomObject>

force-app/main/default/objects/AccessToken__c/fields/ExpirationTime__c.field-meta.xml
<CustomField>
    <fullName>ExpirationTime__c</fullName>
    <description>This field will be saving the token expiry time</description>
    <label>ExpirationTime</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AccessToken__c/fields/Token1__c.field-meta.xml
<CustomField>
    <fullName>Token1__c</fullName>
    <description>This field will be saving the token received</description>
    <label>Token1</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/apiRequestClasses/requestBuilders/UrjanetRequestBuilder.cls
/****************************************************************************************
Name            : UrjanetRequestBuilder
Revision Log    : 2022-04-19 Abhi Tangudu - CodeScience
                :
                :
Use             :  Abstract class to build requests to make callout to Urjanet API
*****************************************************************************************/
public abstract class UrjanetRequestBuilder {
    protected HttpRequest request;
    protected UrjanetRequestArgs args;
    String token;
    public UrjanetRequestBuilder(UrjanetRequestArgs args) {
        this.args = args;
        HttpRequest request = new HttpRequest();
        AccessToken__c accessTokenSetting = AccessToken__c.getInstance(UserInfo.getProfileId());
        if (
            accessTokenSetting.Token1__c != null &&
            accessTokenSetting.ExpirationTime__c != null &&
            accessTokenSetting.ExpirationTime__c > DateTime.now()
        ) {
            token = UrjanetUtils.extractAccessToken(accessTokenSetting);
        } else {
            token = new UrjanetApiClient().getAccessToken().token;
        }
        request.setHeader('Authorization', 'Bearer ' + token);
        request.setMethod(args.apiMethod);
        this.request = request;
    }

    abstract public HttpRequest buildRequest();
}