force-app/main/default/objects/AccessToken__c/AccessToken__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used to save the Token Details</description>
    <label>Access Token</label>
</CustomObject>

force-app/main/default/objects/AccessToken__c/fields/ExpirationTime__c.field-meta.xml
<CustomField>
    <fullName>ExpirationTime__c</fullName>
    <description>This field will be saving the token expiry time</description>
    <label>ExpirationTime</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AccessToken__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>This field will be saving the message</description>
    <label>Message</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/AccessToken__c/fields/Token1__c.field-meta.xml
<CustomField>
    <fullName>Token1__c</fullName>
    <description>This field will be saving the token received</description>
    <label>Token1</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/UtilityCredential__c.object-meta.xml
<CustomObject>
    <description
    >A custom object (created by the Urjanet Connect app) to store status information about utility credentials</description>
    <label>Utility Credential</label>
    <nameField>
        <label>Utility Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityCredential__c/fields/CorrelationID__c.field-meta.xml
<CustomField>
    <fullName>CorrelationID__c</fullName>
    <description>A unique number to identify this utility credential record within Urjanet&apos;s sytem.</description>
    <externalId>true</externalId>
    <inlineHelpText>A unique number to identify this utility credential record within Urjanet&apos;s sytem.</inlineHelpText>
    <label>Correlation ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/NextScheduledRun__c.field-meta.xml
<CustomField>
    <fullName>NextScheduledRun__c</fullName>
    <description>The time that this credential is next scheduled to be ran in our system.</description>
    <inlineHelpText>The time that this credential is next scheduled to be ran in our system.</inlineHelpText>
    <label>Next Scheduled Run</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description
    >Credential-level statuses that let you know if there are any issues accessing the provider portal, the data, or with the credential itself.</description>
    <inlineHelpText
    >Credential-level statuses that let you know if there are any issues accessing the provider portal, the data, or with the credential itself.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>PENDING</fullName>
                <label>Pending</label>
            </value>
            <value>
                <fullName>SENT_TO_URJANET</fullName>
                <label>Sent To Arcadia</label>
            </value>
            <value>
                <fullName>ACTION_REQUIRED</fullName>
                <label>Action Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/StatusDetail__c.field-meta.xml
<CustomField>
    <fullName>StatusDetail__c</fullName>
    <description>A detailed status for the credential.</description>
    <inlineHelpText>A detailed status for the credential.</inlineHelpText>
    <label>Status Detail</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>PENDING</fullName>
                <label>Pending</label>
            </value>
            <value>
                <fullName>ACTION_REQUIRED</fullName>
                <label>Action Required</label>
            </value>
            <value>
                <fullName>ACCOUNT_LOCKED</fullName>
                <label>Account Locked</label>
            </value>
            <value>
                <fullName>E_BILL_REQUIRED</fullName>
                <label>E-Bill Required</label>
            </value>
            <value>
                <fullName>LOGIN_FAILURE</fullName>
                <label>Login Failure</label>
            </value>
            <value>
                <fullName>MULTIFACTOR_AUTH_FAILURE</fullName>
                <label>Multi-Factor Authentication Failure</label>
            </value>
            <value>
                <fullName>NAVIGATION_FAILURE</fullName>
                <label>Navigation Failure</label>
            </value>
            <value>
                <fullName>NO_ACCOUNTS_FOUND</fullName>
                <label>No Accounts Found</label>
            </value>
            <value>
                <fullName>NO_ACTION_REQUIRED</fullName>
                <label>No Action Required</label>
            </value>
            <value>
                <fullName>SECURITY_QUESTIONS</fullName>
                <label>Security Questions</label>
            </value>
            <value>
                <fullName>STATEMENT_UNAVAILABLE</fullName>
                <label>Statement Unavailable</label>
            </value>
            <value>
                <fullName>UNDER_REVIEW</fullName>
                <label>Under Review</label>
            </value>
            <value>
                <fullName>UNSUPPORTED_CAPTCHA</fullName>
                <label>Unsupported CAPTCHA</label>
            </value>
            <value>
                <fullName>USER_ACTION_REQUIRED</fullName>
                <label>User Action Required</label>
            </value>
            <value>
                <fullName>WEBSITE_DOWN</fullName>
                <label>Website Down</label>
            </value>
            <value>
                <fullName>ACCOUNT_SETUP_REQUIRED</fullName>
                <label>Account Setup Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/UrjanetId__c.field-meta.xml
<CustomField>
    <fullName>UrjanetId__c</fullName>
    <description>Unique ID for the account on Arcadia system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique ID for the account on Arcadia system.</inlineHelpText>
    <label>ArcadiaId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/Username2__c.field-meta.xml
<CustomField>
    <fullName>Username2__c</fullName>
    <description>Optional parameters required by some providers to access data. The provider object will denote which fields are required for each provider.</description>
    <inlineHelpText>Optional parameters required by some providers to access data. The provider object will denote which fields are required for each provider.</inlineHelpText>
    <label>Username2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/Username3__c.field-meta.xml
<CustomField>
    <fullName>Username3__c</fullName>
    <description>Optional parameters required by some providers to access data. The provider object will denote which fields are required for each provider.</description>
    <inlineHelpText>Optional parameters required by some providers to access data. The provider object will denote which fields are required for each provider.</inlineHelpText>
    <label>Username3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <description>The provider username.</description>
    <inlineHelpText>The provider username.</inlineHelpText>
    <label>Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/testClasses/UtilityCredentialSyncServiceTest.cls
@IsTest
public with sharing class UtilityCredentialSyncServiceTest {
    @TestSetup
    static void makeData() {
        User adminUser = TestUtility.createUserAdmin('urjanetAdmin@urjanettest.com');
        System.runAs(adminUser) {
            UtilityCredential__c credential = new UtilityCredential__c(
                Name = 'Test Utility Credential',
                CorrelationId__c = '001TestCorrelationId'
            );
            insert credential;
        }
    }
    @IsTest
    public static void utilityCredentialSyncTest() {
        User adminUser = [SELECT Id FROM User WHERE email = 'urjanetAdmin@urjanettest.com' LIMIT 1];
        System.runAs(adminUser) {
            UtilityCredential__c credential = [
                SELECT ID, CorrelationId__c
                FROM UtilityCredential__c
                WHERE Name = 'Test Utility Credential'
            ];

            CredentialResponseMock.credentialId = credential.CorrelationId__c;
            Integer batchSize = UrjanetUtils.getBatchSize(false);
            Test.setMock(HttpCalloutMock.class, new CredentialResponseMock());
            Test.startTest();
            Database.executeBatch(new UtilityCredentialSyncBatch(), batchSize);
            Test.stopTest();
            UtilityCredential__c updateCredential = [
                SELECT
                    ID,
                    Name,
                    CorrelationId__c,
                    NextScheduledRun__c,
                    Status__c,
                    StatusDetail__c,
                    Username__c,
                    Username2__c,
                    Username3__c,
                    urjanetId__c
                FROM UtilityCredential__c
                WHERE Id = :credential.Id
            ];
            CSUtils.itShouldBe('Correlation Id ', credential.CorrelationId__c, updateCredential.correlationId__c);
            CSUtils.itShouldBe('Status ', 'OK', updateCredential.Status__c);
            CSUtils.itShouldBe('Status Detail ', 'NO_ACTION_REQUIRED', updateCredential.StatusDetail__c);
            CSUtils.itShouldBe('Username ', 'Test_Name_1', updateCredential.Username__c);
            CSUtils.itShouldBe('Username 2 ', 'test_user_name2', updateCredential.Username2__c);
            CSUtils.itShouldBe('Username 3 ', 'test_user_name3', updateCredential.Username3__c);
            CSUtils.itShouldBe('Urjanet Id ', '1234abcd-1234-abc0-12ab-ab3242342332', updateCredential.urjanetId__c);
        }
    }

    @IsTest
    static void testSchedulable() {
        User adminUser = [SELECT Id FROM User WHERE email = 'urjanetAdmin@urjanettest.com' LIMIT 1];
        StaticResourceCalloutMock mock = TestUtility.getStaticResourceCalloutMock('LoginResponse', 200);
        System.runAs(adminUser) {
            UtilityCredential__c credential = [
                SELECT ID, CorrelationId__c
                FROM UtilityCredential__c
                WHERE Name = 'Test Utility Credential'
            ];
            CredentialResponseMock.credentialId = credential.CorrelationId__c;
            Test.setMock(HttpCalloutMock.class, new CredentialResponseMock());
            insertAccessToken();
            TestUtility.insertLastSyncDetails();
            Test.startTest();
            String jobId = System.schedule(
                'Test Utility Credential Sync',
                UrjanetUtils.getSchedulerExpression(DateTime.Now().addDays(1)),
                new UtilityCredentialSyncScheduler()
            );
            Test.stopTest();
            CronTrigger scheduledRec = [SELECT Id FROM CronTrigger WHERE Id = :jobId];
            CSUtils.itShouldBe('Job Id ', jobId, scheduledRec.Id);
        }
    }

    @IsTest
    static void testScheduleJob() {
        User adminUser = [SELECT Id FROM User WHERE email = 'urjanetAdmin@urjanettest.com' LIMIT 1];
        StaticResourceCalloutMock mock = TestUtility.getStaticResourceCalloutMock('LoginResponse', 200);
        System.runAs(adminUser) {
            UtilityCredential__c credential = [
                SELECT ID, CorrelationId__c
                FROM UtilityCredential__c
                WHERE Name = 'Test Utility Credential'
            ];
            CredentialResponseMock.credentialId = credential.CorrelationId__c;
            Test.setMock(HttpCalloutMock.class, new CredentialResponseMock());
            insertAccessToken();
            TestUtility.insertLastSyncDetails();
            Test.startTest();
            String jobId = UtilityCredentialSyncScheduler.scheduleJob();
            Test.stopTest();
            CronTrigger scheduledRec = [SELECT Id FROM CronTrigger WHERE Id = :jobId];
            CSUtils.itShouldBe('Job Id ', jobId, scheduledRec.Id);
        }
    }

    @IsTest
    static void testScheduleJobWithCron() {
        User adminUser = [SELECT Id FROM User WHERE email = 'urjanetAdmin@urjanettest.com' LIMIT 1];
        StaticResourceCalloutMock mock = TestUtility.getStaticResourceCalloutMock('LoginResponse', 200);
        System.runAs(adminUser) {
            UtilityCredential__c credential = [
                SELECT ID, CorrelationId__c
                FROM UtilityCredential__c
                WHERE Name = 'Test Utility Credential'
            ];
            CredentialResponseMock.credentialId = credential.CorrelationId__c;
            Test.setMock(HttpCalloutMock.class, new CredentialResponseMock());
            insertAccessToken();
            TestUtility.insertLastSyncDetails();
            Test.startTest();
            String jobId = UtilityCredentialSyncScheduler.scheduleJob(
                'test schedule job',
                UrjanetUtils.getSchedulerExpression(DateTime.Now().addDays(1))
            );
            Test.stopTest();
            CronTrigger scheduledRec = [SELECT Id FROM CronTrigger WHERE Id = :jobId];
            CSUtils.itShouldBe('Job Id ', jobId, scheduledRec.Id);
        }
    }
    public static void insertAccessToken() {
        DateTime dt = System.Now();
        AccessToken__c accessTokenSetting = new AccessToken__c(
            Name = 'Default',
            Token1__c = 'This is token',
            Message__c = 'This is message',
            ExpirationTime__c = Datetime.newInstance(dt.year(), dt.month(), dt.day(), dt.hour() + 1, dt.minute(), 0)
        );
        insert accessTokenSetting;
    }
}