force-app/main/default/objects/AccessToken__c/AccessToken__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used to save the Token Details</description>
    <label>Access Token</label>
</CustomObject>

force-app/main/default/objects/AccessToken__c/fields/ExpirationTime__c.field-meta.xml
<CustomField>
    <fullName>ExpirationTime__c</fullName>
    <description>This field will be saving the token expiry time</description>
    <label>ExpirationTime</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AccessToken__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>This field will be saving the message</description>
    <label>Message</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/AccessToken__c/fields/Token1__c.field-meta.xml
<CustomField>
    <fullName>Token1__c</fullName>
    <description>This field will be saving the token received</description>
    <label>Token1</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/AccessToken__c/fields/Token2__c.field-meta.xml
<CustomField>
    <fullName>Token2__c</fullName>
    <description>This field will be saving the token received</description>
    <label>Token2</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/AccessToken__c/fields/Token3__c.field-meta.xml
<CustomField>
    <fullName>Token3__c</fullName>
    <description>This field will be saving the token received</description>
    <label>Token3</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/AccessToken__c/fields/Token4__c.field-meta.xml
<CustomField>
    <fullName>Token4__c</fullName>
    <description>This field will be saving the token received</description>
    <label>Token4</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/AccessToken__c/fields/Token5__c.field-meta.xml
<CustomField>
    <fullName>Token5__c</fullName>
    <description>This field will be saving the token received</description>
    <label>Token5</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/AccessToken__c/fields/Token6__c.field-meta.xml
<CustomField>
    <fullName>Token6__c</fullName>
    <description>This field will be saving the token received</description>
    <label>Token6</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/AccessToken__c/fields/Token7__c.field-meta.xml
<CustomField>
    <fullName>Token7__c</fullName>
    <description>This field will be saving the token received</description>
    <label>Token7</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/AccessToken__c/fields/Token8__c.field-meta.xml
<CustomField>
    <fullName>Token8__c</fullName>
    <description>This field will be saving the token received</description>
    <label>Token8</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/AccessToken__c/fields/Token9__c.field-meta.xml
<CustomField>
    <fullName>Token9__c</fullName>
    <description>This field will be saving the token received</description>
    <label>Token9</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/testClasses/UrjanetRequestBuilderTest.cls
@IsTest
private class UrjanetRequestBuilderTest {
    @TestSetup
    static void makeData() {
        User adminUser = TestUtility.createUserAdmin('urjanetAdmin@urjanettest.com');
        System.runAs(adminUser) {
            AccessToken__c accessTokenSetting = AccessToken__c.getInstance(UserInfo.getProfileId());
            accessTokenSetting.Token1__c = ' Token 1 Part ';
            accessTokenSetting.Token2__c = ' Token 2 Part ';
            accessTokenSetting.Token3__c = ' Token 3 Part ';
            accessTokenSetting.Token4__c = ' Token 4 Part ';
            accessTokenSetting.Token5__c = ' Token 5 Part ';
            accessTokenSetting.Token6__c = ' Token 6 Part ';
            accessTokenSetting.Token7__c = ' Token 7 Part ';
            accessTokenSetting.Token8__c = ' Token 8 Part ';
            accessTokenSetting.Token9__c = ' Token 9 Part ';
            accessTokenSetting.Name = 'Default';
            accessTokenSetting.ExpirationTime__c = Datetime.now().addMinutes(5);
            accessTokenSetting.Message__c = 'Authentication Successful';
            insert accessTokenSetting;
        }
    }
    @IsTest
    static void testBuildRequest() {
        Test.startTest();
        UrjanetRequestArgs args = new UrjanetRequestArgs();
        args.requestType = UrjanetEnums.RequestType.STATEMENT_FILES_BY_ENTITY_ID;
        args.apiMethod = UrjanetEnums.ApiMethod.GET.name();
        args.requestParams = new List<String>{ 'FileId' };
        UrjanetRequestBuilder requestBuilder = new RequestBuilderFactory().getRequestBuilder(args);
        HttpRequest request = requestBuilder.buildRequest();
        Test.stopTest();
        CSUtils.itShouldBe(
            'Authorization Header',
            'Bearer Token 1 PartToken 2 PartToken 3 PartToken 4 PartToken 5 PartToken 6 PartToken 7 PartToken 8 PartToken 9 Part',
            request.getHeader('Authorization')
        );
    }
}