force-app/main/default/objects/AccessToken__c/AccessToken__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used to save the Token Details</description>
    <label>Access Token</label>
</CustomObject>

force-app/main/CS-QueueScience/objects/QueueItem__c/QueueItem__c.object-meta.xml
<CustomObject>
    <label>Queue Item</label>
    <nameField>
        <displayFormat>QI-{000000000}</displayFormat>
        <label>Queue Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Queue Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/CS-QueueScience/objects/QueueItem__c/fields/ErrorCount__c.field-meta.xml
<CustomField>
    <fullName>ErrorCount__c</fullName>
    <externalId>true</externalId>
    <label>Error Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/UtilityCredentialSyncBatchController.cls
public with sharing class UtilityCredentialSyncBatchController {
    @AuraEnabled
    public static void executeBatchJob(Boolean isTesting) {
        AccessToken__c accessToken = Urjanetutils.checkAndUpdateAccessToken();

        if (null != accessToken) {
            try {
                Integer batchSize = isTesting ? UrjanetUtils.getBatchSize(true) : UrjanetUtils.getBatchSize(false);
                Logger.getInstance()
                    .log(UtilityCredentialSyncBatchController.class.getName(), Logger.Level.INFO, 'Sync Started');
                UrjanetUtils.upsertLastSuccessfulSyncDate();
                UrjanetUtils.updateMeasuredUsageInText();

                Database.executeBatch(new UtilityCredentialSyncBatch(), batchSize);

                //batch for accounts with no credentials
                Database.executeBatch(new UtilityAccountSyncBatch(), batchSize);

                //batch for files
                Database.executeBatch(new UtilityStatementFileSyncBatch(), batchSize);

                Database.executeBatch(new UtilityMeterSyncBatch(), batchSize);

                //For Processing Credential Deletion Logs
                Database.executeBatch(new CredentialDeletionJobBatch(), batchSize);

                Database.executeBatch(new UtilityMeterAndUsageUpdateBatch(), batchSize);
            } catch (Exception e) {
                AuraHandledException ahe = new AuraHandledException(e.getMessage());
                ahe.setMessage(e.getMessage());
                throw ahe;
            }
        }
    }

    @AuraEnabled
    public static void pushSitesToUrjanet() {
        try {
            StationaryAssetSourceService.createQueueItemsToSendStationaryAssetSource();
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Boolean isBatchExecutionCompleted(Boolean isTesting) {
        Boolean batchCompleted = false;
        String query = 'SELECT COUNT() FROM AsyncApexJob WHERE JobType = \'BatchApex\' AND Status IN (\'Queued\', \'Preparing\', \'Processing\')';
        
        if (!isTesting) {
            query += ' AND ApexClass.NameSpacePrefix= \'urjanet\'';
        }
        Integer enqueuedJobs = Database.countQuery(query);

        Integer queueItems = [
            SELECT COUNT()
            FROM QueueItem__c
            WHERE ErrorCount__c = NULL
        ];
        if (enqueuedJobs > 0) {
            Logger.getInstance()
                .log(
                    UtilityCredentialSyncBatchController.class.getName(),
                    Logger.Level.WARN,
                    'Jobs execution is not completed'
                );
        } else if (queueItems > 0) {
            Logger.getInstance()
                .log(
                    UtilityCredentialSyncBatchController.class.getName(),
                    Logger.Level.WARN,
                    'Queue items processing is not completed'
                );
        } else {
            batchCompleted = true;
            Logger.getInstance()
                .log(
                    UtilityCredentialSyncBatchController.class.getName(),
                    Logger.Level.DEBUG,
                    'No pending jobs to be completed'
                );
        }
        return batchCompleted;
    }
}