force-app/main/default/objects/UtilityCredential__c/UtilityCredential__c.object-meta.xml
<CustomObject>
    <description
    >A custom object (created by the Urjanet Connect app) to store status information about utility credentials</description>
    <label>Utility Credential</label>
    <nameField>
        <label>Utility Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityCredential__c/fields/CorrelationID__c.field-meta.xml
<CustomField>
    <fullName>CorrelationID__c</fullName>
    <description>A unique number to identify this utility credential record within Urjanet&apos;s sytem.</description>
    <externalId>true</externalId>
    <inlineHelpText>A unique number to identify this utility credential record within Urjanet&apos;s sytem.</inlineHelpText>
    <label>Correlation ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/testClasses/UtilityCredentialDomainTest.cls
@isTest
public with sharing class UtilityCredentialDomainTest {
    @TestSetup
    static void makeData() {
        User adminUser = TestUtility.createUserAdmin('urjanetAdmin@urjanettest.com');
    }

    @IsTest
    public static void utilityCredentialInsertTest() {
        User adminUser = [SELECT Id FROM User WHERE email = 'urjanetAdmin@urjanettest.com' LIMIT 1];
        System.runAs(adminUser) {
            UtilityCredential__c credential = new UtilityCredential__c();
            credential.Name = 'Test Utility Credential';
            Test.startTest();
            insert credential;
            Test.stopTest();
            UtilityCredential__c credentialQueried = [
                SELECT Id, CorrelationId__c
                FROM UtilityCredential__c
                WHERE Id = :credential.Id
            ];
            CSUtils.itShouldBe(
                'Utility Credential Correlation Id ',
                'NZC-ARC-' + credential.Id,
                credentialQueried.CorrelationId__c
            );
        }
    }

    @IsTest
    public static void utilityCredentialUpdateTest() {
        User adminUser = [SELECT Id FROM User WHERE email = 'urjanetAdmin@urjanettest.com' LIMIT 1];
        System.runAs(adminUser) {
            UtilityCredential__c credential = new UtilityCredential__c();
            credential.Name = 'Test Utility Credential';
            insert credential;
            Test.startTest();
            credential.CorrelationId__c = '';
            update credential;
            Test.stopTest();
            UtilityCredential__c credentialQueried = [
                SELECT Id, CorrelationId__c
                FROM UtilityCredential__c
                WHERE Id = :credential.Id
            ];
            CSUtils.itShouldBe(
                'Utility Credential Correlation Id ',
                'NZC-ARC-' + credentialQueried.Id,
                credentialQueried.CorrelationId__c
            );
        }
    }
}