force-app/main/default/objects/UtilityCredential__c/UtilityCredential__c.object-meta.xml
<CustomObject>
    <description
    >A custom object (created by the Urjanet Connect app) to store status information about utility credentials</description>
    <label>Utility Credential</label>
    <nameField>
        <label>Utility Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityCredential__c/fields/ArcadiaServiceProviderId__c.field-meta.xml
<CustomField>
    <fullName>ArcadiaServiceProviderId__c</fullName>
    <description>Unique Id for the Provider in Arcadia system</description>
    <inlineHelpText>Unique Id for the Provider in Arcadia system</inlineHelpText>
    <label>ArcadiaServiceProviderId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/CorrelationID__c.field-meta.xml
<CustomField>
    <fullName>CorrelationID__c</fullName>
    <description>A unique number to identify this utility credential record within Urjanet&apos;s sytem.</description>
    <externalId>true</externalId>
    <inlineHelpText>A unique number to identify this utility credential record within Urjanet&apos;s sytem.</inlineHelpText>
    <label>Correlation ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/CreatedByInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>CreatedByInUrjanet__c</fullName>
    <description>The system user responsible for creating a credential.</description>
    <inlineHelpText>The system user responsible for creating a credential.</inlineHelpText>
    <label>Created By in Arcadia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether data will continue to be extracted behind this credential.</description>
    <inlineHelpText>Indicates whether data will continue to be extracted behind this credential.</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/LastModifiedByInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedByInUrjanet__c</fullName>
    <description>The system user responsible for modifying a credential most recently.</description>
    <inlineHelpText>The system user responsible for modifying a credential most recently.</inlineHelpText>
    <label>Last Modified By in Arcadia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/LastModifiedInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedInUrjanet__c</fullName>
    <description>The date that a credential was modified last.</description>
    <inlineHelpText>The date that a credential was modified last.</inlineHelpText>
    <label>Last Modified in Arcadia</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/LastUrjanetSyncDateTime__c.field-meta.xml
<CustomField>
    <fullName>LastUrjanetSyncDateTime__c</fullName>
    <description>Date and Time of the last sync with Arcadia</description>
    <inlineHelpText>Date and Time of the last sync with Arcadia</inlineHelpText>
    <label>Last Arcadia Sync</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/NextScheduledRun__c.field-meta.xml
<CustomField>
    <fullName>NextScheduledRun__c</fullName>
    <description>The time that this credential is next scheduled to be ran in our system.</description>
    <inlineHelpText>The time that this credential is next scheduled to be ran in our system.</inlineHelpText>
    <label>Next Scheduled Run</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description
    >Credential-level statuses that let you know if there are any issues accessing the provider portal, the data, or with the credential itself.</description>
    <inlineHelpText
    >Credential-level statuses that let you know if there are any issues accessing the provider portal, the data, or with the credential itself.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>PENDING</fullName>
                <label>Pending</label>
            </value>
            <value>
                <fullName>SENT_TO_URJANET</fullName>
                <label>Sent To Arcadia</label>
            </value>
            <value>
                <fullName>ACTION_REQUIRED</fullName>
                <label>Action Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/StatusDetail__c.field-meta.xml
<CustomField>
    <fullName>StatusDetail__c</fullName>
    <description>A detailed status for the credential.</description>
    <inlineHelpText>A detailed status for the credential.</inlineHelpText>
    <label>Status Detail</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>PENDING</fullName>
                <label>Pending</label>
            </value>
            <value>
                <fullName>ACTION_REQUIRED</fullName>
                <label>Action Required</label>
            </value>
            <value>
                <fullName>ACCOUNT_LOCKED</fullName>
                <label>Account Locked</label>
            </value>
            <value>
                <fullName>E_BILL_REQUIRED</fullName>
                <label>E-Bill Required</label>
            </value>
            <value>
                <fullName>LOGIN_FAILURE</fullName>
                <label>Login Failure</label>
            </value>
            <value>
                <fullName>MULTIFACTOR_AUTH_FAILURE</fullName>
                <label>Multi-Factor Authentication Failure</label>
            </value>
            <value>
                <fullName>NAVIGATION_FAILURE</fullName>
                <label>Navigation Failure</label>
            </value>
            <value>
                <fullName>NO_ACCOUNTS_FOUND</fullName>
                <label>No Accounts Found</label>
            </value>
            <value>
                <fullName>NO_ACTION_REQUIRED</fullName>
                <label>No Action Required</label>
            </value>
            <value>
                <fullName>SECURITY_QUESTIONS</fullName>
                <label>Security Questions</label>
            </value>
            <value>
                <fullName>STATEMENT_UNAVAILABLE</fullName>
                <label>Statement Unavailable</label>
            </value>
            <value>
                <fullName>UNDER_REVIEW</fullName>
                <label>Under Review</label>
            </value>
            <value>
                <fullName>UNSUPPORTED_CAPTCHA</fullName>
                <label>Unsupported CAPTCHA</label>
            </value>
            <value>
                <fullName>USER_ACTION_REQUIRED</fullName>
                <label>User Action Required</label>
            </value>
            <value>
                <fullName>WEBSITE_DOWN</fullName>
                <label>Website Down</label>
            </value>
            <value>
                <fullName>ACCOUNT_SETUP_REQUIRED</fullName>
                <label>Account Setup Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/UrjanetId__c.field-meta.xml
<CustomField>
    <fullName>UrjanetId__c</fullName>
    <description>Unique ID for the account on Arcadia system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique ID for the account on Arcadia system.</inlineHelpText>
    <label>ArcadiaId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/Username2__c.field-meta.xml
<CustomField>
    <fullName>Username2__c</fullName>
    <description>Optional parameters required by some providers to access data. The provider object will denote which fields are required for each provider.</description>
    <inlineHelpText>Optional parameters required by some providers to access data. The provider object will denote which fields are required for each provider.</inlineHelpText>
    <label>Username2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/Username3__c.field-meta.xml
<CustomField>
    <fullName>Username3__c</fullName>
    <description>Optional parameters required by some providers to access data. The provider object will denote which fields are required for each provider.</description>
    <inlineHelpText>Optional parameters required by some providers to access data. The provider object will denote which fields are required for each provider.</inlineHelpText>
    <label>Username3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/Username4__c.field-meta.xml
<CustomField>
    <fullName>Username4__c</fullName>
    <description>Optional parameters required by some providers to access data. The provider object will denote which fields are required for each provider.</description>
    <inlineHelpText>Optional parameters required by some providers to access data. The provider object will denote which fields are required for each provider.</inlineHelpText>
    <label>Username4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <description>The provider username.</description>
    <inlineHelpText>The provider username.</inlineHelpText>
    <label>Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/apiResponseClasses/reponseMessages/GetCredentialsResponse.cls
/****************************************************************************************
Name            : GetCredentialsResponse
Revision Log    : 2022-04-28 Abhi Tangudu - CodeScience
                :
                :
Use             :  Urjanet API Callout Response - Get Credential Response
*****************************************************************************************/
public class GetCredentialsResponse extends UrjanetResponse {
    public GetCredentialsResponse() {
    }

    public Embedded embedded { get; set; }

    public class Credentials {
        public String entityId { get; set; }
        public String username { get; set; }
        public String username2 { get; set; }
        public String username3 { get; set; }
        public String username4 { get; set; }
        public String correlationId { get; set; }
        public String status { get; set; }
        public String statusDetail { get; set; }
        public Boolean enabled { get; set; }
        public String nextScheduledRun { get; set; }
        public String providerName { get; set; }
        public Boolean runHistory { get; set; }
        public Boolean mock { get; set; }
        public String customData { get; set; }
        public Integer totalAccounts { get; set; }
        public String createdDate { get; set; }
        public String createdBy { get; set; }
        public String lastModifiedDate { get; set; }
        public String lastModifiedBy { get; set; }
        public Provider provider { get; set; }
        public InnerLinks links { get; set; }

        public UtilityCredential__c toRecord() {
            UtilityCredential__c credential = new UtilityCredential__c();
            credential.CorrelationID__c = this.correlationId;
            credential.CreatedByInUrjanet__c = this.createdBy;
            credential.CreatedDateInUrjanet__c = UrjanetUtils.getDateTime(this.createdDate);
            credential.Enabled__c = this.enabled;
            credential.LastModifiedByInUrjanet__c = this.lastModifiedBy;
            credential.LastModifiedInUrjanet__c = UrjanetUtils.getDateTime(this.lastModifiedDate);
            credential.LastUrjanetSyncDateTime__c = Datetime.now();
            credential.NextScheduledRun__c = UrjanetUtils.getDateTime(this.nextScheduledRun);
            credential.Status__c = this.status;
            credential.StatusDetail__c = this.statusDetail;
            credential.urjanetId__c = this.entityId;
            credential.Username__c = this.username;
            credential.Username2__c = this.username2;
            credential.Username3__c = this.username3;
            credential.Username4__c = this.username4;
            credential.ArcadiaServiceProviderId__c = this.provider?.entityId;
            return credential;
        }
    }

    public class InnerLinks {
        public Href self { get; set; }
        public Href accounts { get; set; }
        public Href consent { get; set; }
        public Href events { get; set; }
        public Href passwords { get; set; }
        public Href provider { get; set; }
        public Href updateUrl { get; set; }
    }

    public class Embedded {
        public List<Credentials> credentials { get; set; }
    }

    public class Provider {
        public String entityId { get; set; }
    }
}