force-app/main/default/objects/Utility_File_Account_Association__c/Utility_File_Account_Association__c.object-meta.xml
<CustomObject>
    <description>Association between Utility Accounts and Utility Statements</description>
    <label>Utility File Account Association</label>
    <nameField>
        <displayFormat>FA-{00000}</displayFormat>
        <label>Utility File Account Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utility File Account Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Utility_File_Account_Association__c/fields/Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Unique_Id__c</fullName>
    <description>Unique id field used for Duplicate Check</description>
    <label>Unique ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Utility_File_Account_Association__c/fields/Utility_Account__c.field-meta.xml
<CustomField>
    <fullName>Utility_Account__c</fullName>
    <description>Utility Account</description>
    <label>Utility Account</label>
    <referenceTo>UtilityAccount__c</referenceTo>
    <relationshipLabel>Utility File Account Associations</relationshipLabel>
    <relationshipName>Utility_File_Account_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Utility_File_Account_Association__c/fields/Utility_Statement_File__c.field-meta.xml
<CustomField>
    <fullName>Utility_Statement_File__c</fullName>
    <description>Utilty Statement File</description>
    <label>Utility Statement File</label>
    <referenceTo>UtilityStatementFile__c</referenceTo>
    <relationshipLabel>Utility File Account Associations</relationshipLabel>
    <relationshipName>Utility_File_Account_Associations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/UtilityAccount__c.object-meta.xml
<CustomObject>
    <description>A custom object (created by the Urjanet Connect app) to store utility account information</description>
    <label>Utility Account</label>
    <nameField>
        <label>Utility Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityAccount__c/fields/AccountNumber__c.field-meta.xml
<CustomField>
    <fullName>AccountNumber__c</fullName>
    <description>The Account number as extracted from the source.</description>
    <inlineHelpText>The Account number as extracted from the source.</inlineHelpText>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/fields/CreatedByInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>CreatedByInUrjanet__c</fullName>
    <description>The system user responsible for creating the account in Arcadia&apos;s system.</description>
    <inlineHelpText>The system user responsible for creating the account in Arcadia&apos;s system.</inlineHelpText>
    <label>Created By in Arcadia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/fields/CreatedDateInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>CreatedDateInUrjanet__c</fullName>
    <description>The Date the account was registered in Arcadia’s system.</description>
    <inlineHelpText>The Date the account was registered in Arcadia’s system.</inlineHelpText>
    <label>Created Date in Arcadia</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if an account is active (meaning Urjanet is actively monitoring the account).</description>
    <inlineHelpText>Indicates if an account is active (meaning Urjanet is actively monitoring the account).</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/fields/LastModifiedByInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedByInUrjanet__c</fullName>
    <description>The system user responsible for modifying an account most recently in the Arcadia system.</description>
    <inlineHelpText
    >The system user responsible for modifying an account most recently in the Arcadia system.</inlineHelpText>
    <label>Last Modified By in Arcadia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/fields/LastModifiedInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedInUrjanet__c</fullName>
    <description>The date that an account was modified last in the Arcadia system.</description>
    <inlineHelpText>The date that an account was modified last in the Arcadia system.</inlineHelpText>
    <label>Last Modified in Arcadia</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/fields/LatestNewStatement__c.field-meta.xml
<CustomField>
    <fullName>LatestNewStatement__c</fullName>
    <description>This represents when Urjanet most recently stored any newly extracted data for this account.</description>
    <inlineHelpText>This represents when Urjanet most recently stored any newly extracted data for this account.</inlineHelpText>
    <label>Latest New Statement</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/fields/LatestStatementDate__c.field-meta.xml
<CustomField>
    <fullName>LatestStatementDate__c</fullName>
    <description>This is the most recent statement date among all statements extracted for this account.</description>
    <inlineHelpText
    >This is the most recent statement date among all statements extracted for this account.</inlineHelpText>
    <label>Latest Statement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/fields/Prepaid__c.field-meta.xml
<CustomField>
    <fullName>Prepaid__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that an account is prepaid.</description>
    <inlineHelpText>Indicates that an account is prepaid.</inlineHelpText>
    <label>Prepaid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Account-level statuses that let you know if there are any issues accessing the account or the statement behind the account.</description>
    <inlineHelpText>Account-level statuses that let you know if there are any issues accessing the account or the statement behind the account.</inlineHelpText>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/fields/StatusDetail__c.field-meta.xml
<CustomField>
    <fullName>StatusDetail__c</fullName>
    <description>A detailed status for the account.</description>
    <inlineHelpText>A detailed status for the account.</inlineHelpText>
    <label>Status Detail</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Supplier</referenceTo>
    <relationshipLabel>Utility Accounts</relationshipLabel>
    <relationshipName>UtilityAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/fields/UtilityCredential__c.field-meta.xml
<CustomField>
    <fullName>UtilityCredential__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Utility Credential</label>
    <referenceTo>UtilityCredential__c</referenceTo>
    <relationshipLabel>Utility Accounts</relationshipLabel>
    <relationshipName>UtilityAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/UtilityCredential__c.object-meta.xml
<CustomObject>
    <description
    >A custom object (created by the Urjanet Connect app) to store status information about utility credentials</description>
    <label>Utility Credential</label>
    <nameField>
        <label>Utility Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityCredential__c/fields/CreatedByInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>CreatedByInUrjanet__c</fullName>
    <description>The system user responsible for creating a credential.</description>
    <inlineHelpText>The system user responsible for creating a credential.</inlineHelpText>
    <label>Created By in Arcadia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether data will continue to be extracted behind this credential.</description>
    <inlineHelpText>Indicates whether data will continue to be extracted behind this credential.</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/LastModifiedByInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedByInUrjanet__c</fullName>
    <description>The system user responsible for modifying a credential most recently.</description>
    <inlineHelpText>The system user responsible for modifying a credential most recently.</inlineHelpText>
    <label>Last Modified By in Arcadia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/LastModifiedInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedInUrjanet__c</fullName>
    <description>The date that a credential was modified last.</description>
    <inlineHelpText>The date that a credential was modified last.</inlineHelpText>
    <label>Last Modified in Arcadia</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/ProviderName__c.field-meta.xml
<CustomField>
    <fullName>ProviderName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The commonly known name for the utility company.</description>
    <inlineHelpText>The commonly known name for the utility company.</inlineHelpText>
    <label>Provider Name</label>
    <referenceTo>Supplier</referenceTo>
    <relationshipLabel>Utility Credentials</relationshipLabel>
    <relationshipName>UtilityCredentials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description
    >Credential-level statuses that let you know if there are any issues accessing the provider portal, the data, or with the credential itself.</description>
    <inlineHelpText
    >Credential-level statuses that let you know if there are any issues accessing the provider portal, the data, or with the credential itself.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>PENDING</fullName>
                <label>Pending</label>
            </value>
            <value>
                <fullName>SENT_TO_URJANET</fullName>
                <label>Sent To Arcadia</label>
            </value>
            <value>
                <fullName>ACTION_REQUIRED</fullName>
                <label>Action Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/UrjanetId__c.field-meta.xml
<CustomField>
    <fullName>UrjanetId__c</fullName>
    <description>Unique ID for the account on Arcadia system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique ID for the account on Arcadia system.</inlineHelpText>
    <label>ArcadiaId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/UtilityStatementFile__c/UtilityStatementFile__c.object-meta.xml
<CustomObject>
    <label>Utility Statement File</label>
    <nameField>
        <label>Utility Statement File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Statement Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityStatementFile__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Supplier</referenceTo>
    <relationshipLabel>Utility Statement Files</relationshipLabel>
    <relationshipName>UtilityStatementFiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UtilityAccountService.cls
public with sharing class UtilityAccountService {
    public static void createAccountFromDataResponse(
        GetAccountsByCredsResponse response,
        UtilityCredential__c credential
    ) {
        List<UtilityAccount__c> accountRecords = new List<UtilityAccount__c>();
        if (response != null && response.embedded != null && response.embedded.accounts != null) {
            for (GetAccountsByCredsResponse.Account account : response.embedded.accounts) {
                UtilityAccount__c utilityAccount = toObject(account);
                utilityAccount.UtilityCredential__r = new UtilityCredential__c(UrjanetId__c = credential.UrjanetId__c);
                utilityAccount.Supplier__c = credential.ProviderName__c;
                accountRecords.add(utilityAccount);
            }
        }

        if (!accountRecords.isEmpty()) {
            try {
                // This will be running as a system process that should complete
                // no matter who kicked it off
                Database.DMLOptions option = new Database.DMLOptions();
                option.OptAllOrNone = false;
                Logger.getInstance()
                    .log(
                        UtilityAccountService.class.getName(),
                        UrjanetUtils.getSObjectName(Schema.UtilityAccount__c.SObjectType),
                        Data.upsurt(
                            accountRecords,
                            Schema.UtilityAccount__c.fields.UrjanetId__c,
                            option,
                            false,
                            false,
                            false,
                            null
                        )
                    );
            } catch (DmlException e) {
                Logger.getInstance(false).log(UtilityAccountService.class.getName(), e);
            }
        }
    }

    public static void createAccountFromDataResponse(
        GetAccountsByCredsResponse response,
        UtilityStatementFile__c utilityStatementFileObj
    ) {
        List<UtilityAccount__c> accountRecords = new List<UtilityAccount__c>();
        if (response != null && response.embedded != null && response.embedded.accounts != null) {
            for (GetAccountsByCredsResponse.Account account : response.embedded.accounts) {
                UtilityAccount__c utilityAccount = toObject(account);
                utilityAccount.Supplier__c = utilityStatementFileObj.Supplier__c;
                accountRecords.add(utilityAccount);
            }
        }

        if (!accountRecords.isEmpty()) {
            try {
                // This will be running as a system process that should complete
                // no matter who kicked it off
                Database.DMLOptions option = new Database.DMLOptions();
                option.OptAllOrNone = false;
                Logger.getInstance()
                    .log(
                        UtilityAccountService.class.getName(),
                        UrjanetUtils.getSObjectName(Schema.UtilityAccount__c.SObjectType),
                        Data.upsurt(
                            accountRecords,
                            Schema.UtilityAccount__c.fields.UrjanetId__c,
                            option,
                            false,
                            false,
                            false,
                            null
                        )
                    );
                List<Utility_File_Account_Association__c> fileAccountRecords = new List<Utility_File_Account_Association__c>();

                for (UtilityAccount__c utilityAccount : accountRecords) {
                    Utility_File_Account_Association__c fileAccount = new Utility_File_Account_Association__c();
                    fileAccount.Unique_Id__c = utilityAccount.Id + ' ' + utilityStatementFileObj.Id;
                    fileAccount.Utility_Account__c = utilityAccount.Id;
                    fileAccount.Utility_Statement_File__c = utilityStatementFileObj.Id;
                    fileAccountRecords.add(fileAccount);
                }
                try {
                    insert fileAccountRecords;
                } catch (Exception e) {
                    if (!e.getMessage().contains('DUPLICATE_VALUE')) {
                        Logger.getInstance(false).log(UtilityAccountService.class.getName() + '_Files', e);
                        // No need for Logs in case of duplicate records
                    }
                }
            } catch (DmlException e) {
                Logger.getInstance(false).log(UtilityAccountService.class.getName() + '_Files', e);
            }
        }
    }

    @TestVisible
    private static UtilityAccount__c toObject(GetAccountsByCredsResponse.Account account) {
        UtilityAccount__c utilityAccount = new UtilityAccount__c();
        utilityAccount.CreatedDateInUrjanet__c = UrjanetUtils.getDateTime(account.createdDate);
        utilityAccount.CreatedByInUrjanet__c = account.createdBy;
        utilityAccount.Enabled__c = account.enabled;
        utilityAccount.LastModifiedInUrjanet__c = UrjanetUtils.getDateTime(account?.lastModifiedDate);
        utilityAccount.LastModifiedByInUrjanet__c = account.lastModifiedBy;
        utilityAccount.LatestNewStatement__c = UrjanetUtils.getDateTime(account.latestNewStatement);
        utilityAccount.LatestStatementDate__c = (account.latestStatementDate == null
            ? null
            : Date.valueOf(account.latestStatementDate));
        utilityAccount.AccountNumber__c = account.normalizedAccountNumber;
        utilityAccount.Prepaid__c = account.prepaid;
        utilityAccount.Status__c = account.status;
        utilityAccount.StatusDetail__c = account.statusDetail;
        utilityAccount.Type__c = account.type;
        utilityAccount.UrjanetId__c = account.entityId;
        utilityAccount.LastUrjanetSyncDateTime__c = Datetime.now();
        String name = account.providerName + ' - ' + account.normalizedAccountNumber;
        utilityAccount.Name = name.abbreviate(80);
        return utilityAccount;
    }

    public static void createQueueItemsForUtilityAccounts(List<UtilityAccount__c> records) {
        createQueueItemsForUtilityAccounts(records, null);
    }

    public static void createQueueItemsForUtilityAccounts(
        List<UtilityAccount__c> records,
        Map<Id, UtilityAccount__c> oldMap
    ) {
        List<UtilityAccount__c> updatedAccounts = getAccountsToRefresh(records, oldMap);
        Type processorClass = QueueItemProcessorFactory.getProcessorType(UtilityAccount__c.SObjectType);
        List<Database.SaveResult> saveResults = new QueueItemsBuilder(updatedAccounts, processorClass)
            .buildQueueItemsPerRecord()
            .createRecords();
        UrjanetUtils.logFailures(
            UtilityAccountService.class.getName(),
            String.valueOf(UtilityAccount__c.SObjectType),
            saveResults
        );
    }

    @TestVisible
    private static List<UtilityAccount__c> getAccountsToRefresh(
        List<UtilityAccount__c> records,
        Map<Id, UtilityAccount__c> oldMap
    ) {
        List<UtilityAccount__c> updatedUtilityAccounts = new List<UtilityAccount__c>();
        if (oldMap == null) {
            updatedUtilityAccounts.addAll(records);
        } else {
            SObjectField syncField = UtilityAccount__c.LastModifiedInUrjanet__c;
            for (UtilityAccount__c account : records) {
                if (UrjanetUtils.hasSyncFieldUpdated(account, oldMap, syncField)) {
                    updatedUtilityAccounts.add(account);
                }
            }
        }
        return updatedUtilityAccounts;
    }
}