force-app/main/default/objects/Utility_File_Account_Association__c/Utility_File_Account_Association__c.object-meta.xml
<CustomObject>
    <description>Association between Utility Accounts and Utility Statements</description>
    <label>Utility File Account Association</label>
    <nameField>
        <displayFormat>FA-{00000}</displayFormat>
        <label>Utility File Account Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utility File Account Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Utility_File_Account_Association__c/fields/Utility_Statement_File__c.field-meta.xml
<CustomField>
    <fullName>Utility_Statement_File__c</fullName>
    <description>Utilty Statement File</description>
    <label>Utility Statement File</label>
    <referenceTo>UtilityStatementFile__c</referenceTo>
    <relationshipLabel>Utility File Account Associations</relationshipLabel>
    <relationshipName>Utility_File_Account_Associations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UtilityStatementFile__c/UtilityStatementFile__c.object-meta.xml
<CustomObject>
    <label>Utility Statement File</label>
    <nameField>
        <label>Utility Statement File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Statement Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityStatementFile__c/fields/EntityId__c.field-meta.xml
<CustomField>
    <fullName>EntityId__c</fullName>
    <externalId>true</externalId>
    <label>Entity ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityStatementFile__c/fields/StatementId__c.field-meta.xml
<CustomField>
    <fullName>StatementId__c</fullName>
    <label>Statement Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UtilityStatementFileSyncBatch.cls
public with sharing class UtilityStatementFileSyncBatch implements Database.Batchable<sObject>, Database.AllowsCallouts {
    public UtilityStatementFileSyncBatch() {
    }

    /**
     * Start implementation
     * @param bc
     *
     * @return
     */
    public Database.Querylocator start(Database.BatchableContext bc) {
        //CRUD / FLS is ignored to ensure that query runs in system context in order to sync over records to Urjanet.
        Logger.getInstance(false)
            .log(
                UtilityStatementFileSyncBatch.class.getName(),
                Logger.Level.INFO,
                'Utility Statement File Sync Batch Started'
            );
        UtilityStatementFileSelector selector = new UtilityStatementFileSelector(false, false, false);
        return selector.getRecordsForUtilStatementFileSyncBatch();
    }

    /**
     * @description process the Utility Statement Files
     * @param  bc    bc description
     * @param  scope scope description
     */
    public void execute(Database.BatchableContext bc, List<sObject> scope) {
        //Run schedule job process
        UtilityStatementFileService.getUtilityStatementFiles(scope);
    }

    public void finish(Database.BatchableContext bc) {
        List<UtilityStatementFile__c> statements = [
            SELECT Id
            FROM UtilityStatementFile__c
            WHERE
                EntityId__c != NULL
                AND StatementId__c != NULL
                AND Status__c = 'SUCCESS'
                AND Id NOT IN (SELECT Utility_Statement_File__c FROM Utility_File_Account_Association__c)
        ];

        if (!statements.isEmpty()) {
            UtilityStatementFileService.linkUtilityStatementFilesWithAccount(statements);
        }
        Logger.getInstance(false)
            .log(
                UtilityStatementFileSyncBatch.class.getName(),
                Logger.Level.INFO,
                'Utility Statement File Sync Batch Completed'
            );
    }
}