force-app/main/default/objects/UtilityMeterUsageProcessorSetting__mdt/UtilityMeterUsageProcessorSetting__mdt.object-meta.xml
<CustomObject>
    <description>Custom Metadata used to store the processor class name to be used for each service type</description>
    <label>Utility Meter Usage Processor Setting</label>
    <pluralLabel>Utility Meter Usage Processor Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/UtilityMeterUsageProcessorSetting__mdt/fields/ProcessorClassName__c.field-meta.xml
<CustomField>
    <fullName>ProcessorClassName__c</fullName>
    <description>Salesforce Processor Class Name</description>
    <inlineHelpText>Salesforce Processor Class Name</inlineHelpText>
    <label>Processor Class Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ServiceToProcessorTypeMappingSelector.cls
public with sharing class ServiceToProcessorTypeMappingSelector extends Selector {
    public ServiceToProcessorTypeMappingSelector() {
        super(Schema.UtilityMeterUsageProcessorSetting__mdt.SObjectType);
    }
    public ServiceToProcessorTypeMappingSelector(Boolean enforceCRUD, Boolean enforceFLS, Boolean enforceShr) {
        super(Schema.UtilityMeterUsageProcessorSetting__mdt.SObjectType, enforceCRUD, enforceFLS, enforceShr);
    }

    /**
     * Returns a Set that has all of the default fields.
     * @return   Set of Strings that contain the default fields for this object
     */
    public override Set<String> getDefaultFields() {
        return new Set<String>{ 'Id', 'DeveloperName', 'ProcessorClassName__c', 'ServiceType__c' };
    }
}