force-app/main/default/objects/UtilityStatementFile__c/UtilityStatementFile__c.object-meta.xml
<CustomObject>
    <label>Utility Statement File</label>
    <nameField>
        <label>Utility Statement File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Statement Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityStatementFile__c/fields/EntityId__c.field-meta.xml
<CustomField>
    <fullName>EntityId__c</fullName>
    <externalId>true</externalId>
    <label>Entity ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityStatementFile__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Supplier</referenceTo>
    <relationshipLabel>Utility Statement Files</relationshipLabel>
    <relationshipName>UtilityStatementFiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ArcadiaStatementUploadService.cls
public with sharing class ArcadiaStatementUploadService {
    @future(callout=true)
    public static void uploadFile(String jsonFileDetails, String supplierId, String fileName) {
        try {
            ArcadiaStatementUploadCalloutService aracadiaCalloutService = ArcadiaStatementUploadCalloutService.getInstance();
            ArcadiaStatementUploadCalloutResources.UploadStatementResponse fileUploadResult = aracadiaCalloutService.uploadStatement(
                jsonFileDetails,
                fileName
            );
            UtilityStatementFile__c utilityStatementObj = fileUploadResult.toUtilityStatementRecord();
            utilityStatementObj.Supplier__c = supplierId;
            utilityStatementObj.Name = fileName.abbreviate(80);

            List<Database.UpsertResult> lstUpsertResults = Data.upsurt(
                new List<UtilityStatementFile__c>{ utilityStatementObj },
                Schema.UtilityStatementFile__c.fields.EntityId__c,
                false,
                false,
                false,
                null
            );

            //verify that the upsert happened without issues
            ArcadiaGenericController.handleDMLErrors(lstUpsertResults[0]);
        } catch (Exception e) {
            Logger.getPlatformLogger().log('ArcadiaStatementUploadService', e);
        }
    }
}