force-app/main/default/objects/UtilityStatementFile__c/UtilityStatementFile__c.object-meta.xml
<CustomObject>
    <label>Utility Statement File</label>
    <nameField>
        <label>Utility Statement File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Statement Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityStatementFile__c/fields/CreatedDateInArcadia__c.field-meta.xml
<CustomField>
    <fullName>CreatedDateInArcadia__c</fullName>
    <label>Created Date in Arcadia</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/UtilityStatementFile__c/fields/EntityId__c.field-meta.xml
<CustomField>
    <fullName>EntityId__c</fullName>
    <externalId>true</externalId>
    <label>Entity ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityStatementFile__c/fields/StatementId__c.field-meta.xml
<CustomField>
    <fullName>StatementId__c</fullName>
    <label>Statement Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityStatementFile__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Supplier</referenceTo>
    <relationshipLabel>Utility Statement Files</relationshipLabel>
    <relationshipName>UtilityStatementFiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UtilityStatementFileSelector.cls
public with sharing class UtilityStatementFileSelector extends Selector {
    public UtilityStatementFileSelector() {
        this(true, true, true);
    }

    public UtilityStatementFileSelector(Boolean enforceCRUD, Boolean enforceFLS, Boolean enforceShr) {
        super(Schema.UtilityStatementFile__c.SObjectType, enforceCRUD, enforceFLS, enforceShr);
    }

    /**
     * Returns a Set that has all of the default fields.
     * @return   Set of Strings that contain the default fields for this object
     */
    public override Set<String> getDefaultFields() {
        Set<String> defaultFields = new Set<String>{
            'Id',
            'Name',
            'CreatedDateInArcadia__c',
            'EntityId__c',
            'Status__c',
            'Supplier__c',
            'Name',
            'StatementId__c'
        };
        return defaultFields;
    }

    /**
     * Gets UtilityStatementFile records that need the details synced from Urjanet
     * @return Database.QueryLocator
     */
    public Database.QueryLocator getRecordsForUtilStatementFileSyncBatch() {
        Map<String, Object> params = new Map<String, Object>();

        //we need to get the utilit Statement files with Pending Status or Failure Status
        //For failure status we will get the ones that got crated in Arcadia in the last 90 days including today (Last N months, was ignoring the current month)
        String query = getDefaultQuery();
        query += ' WHERE EntityId__c != null and (Status__c IN (\'PENDING\' , \'QUEUED\' , \'COVERAGE_REQUEST\' , \'IN_PROGRESS\') or (Status__c IN (\'FAILURE\', \'REJECTED\') and CreatedDateInArcadia__c = LAST_N_DAYS:90))';
        return Data.Locator(query, params, this.isEnforcingCRUD(), this.isEnforcingFLS(), this.isEnforcingShr());
    }
}