force-app/main/default/objects/UtilityStatementFile__c/UtilityStatementFile__c.object-meta.xml
<CustomObject>
    <label>Utility Statement File</label>
    <nameField>
        <label>Utility Statement File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Statement Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityStatementFile__c/fields/CreatedDateInArcadia__c.field-meta.xml
<CustomField>
    <fullName>CreatedDateInArcadia__c</fullName>
    <label>Created Date in Arcadia</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/UtilityStatementFile__c/fields/EntityId__c.field-meta.xml
<CustomField>
    <fullName>EntityId__c</fullName>
    <externalId>true</externalId>
    <label>Entity ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityStatementFile__c/fields/StatementId__c.field-meta.xml
<CustomField>
    <fullName>StatementId__c</fullName>
    <label>Statement Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/apiResponseClasses/reponseMessages/GetUtilityStatementFilesResponse.cls
public with sharing class GetUtilityStatementFilesResponse extends UrjanetResponse {
    public GetUtilityStatementFilesResponse() {
    }

    public Embedded embedded { get; set; }

    public class Embedded {
        public List<Files> files;
    }

    public class Files {
        public String createdDate;
        public String createdBy;
        public String entityId;
        public List<String> fileDetails;
        public String fileName;
        public String fileStatus;
        public String id;
        public Provider provider;
        public String providerName;
        public InnerLinks links;

        public UtilityStatementFile__c toRecord() {
            UtilityStatementFile__c utilityStatementObj = new UtilityStatementFile__c();
            utilityStatementObj.Name = this.fileName.abbreviate(80);
            utilityStatementObj.EntityId__c = this.id;
            utilityStatementObj.Status__c = this.fileStatus;
            utilityStatementObj.CreatedDateInArcadia__c = UrjanetUtils.getDateTime(this.createdDate);
            utilityStatementObj.StatementId__c = '';

            if (
                this.links != null &&
                this.links.statement != null &&
                !String.isEmpty(this.links.statement.href) &&
                !String.isEmpty(this.links.statement.href.substringAfter('/statements/'))
            ) {
                utilityStatementObj.StatementId__c = this.links.statement.href.substringAfter('/statements/');
            }
            return utilityStatementObj;
        }
    }

    public class InnerLinks {
        public Href self { get; set; }
        public Href source { get; set; }
        public Href statement { get; set; }
        public Href accounts { get; set; }
        public Href meters { get; set; }
    }

    public class Provider {
        public String country;
        public String entityId;
        public String providerName;
        public Boolean supportsCredentialValidation;
        public String website;
    }
}