force-app/main/default/objects/UtilityAccount__c/UtilityAccount__c.object-meta.xml
<CustomObject>
    <description>A custom object (created by the Urjanet Connect app) to store utility account information</description>
    <label>Utility Account</label>
    <nameField>
        <label>Utility Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityAccount__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Supplier</referenceTo>
    <relationshipLabel>Utility Accounts</relationshipLabel>
    <relationshipName>UtilityAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/fields/UtilityCredential__c.field-meta.xml
<CustomField>
    <fullName>UtilityCredential__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Utility Credential</label>
    <referenceTo>UtilityCredential__c</referenceTo>
    <relationshipLabel>Utility Accounts</relationshipLabel>
    <relationshipName>UtilityAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/UtilityCredential__c.object-meta.xml
<CustomObject>
    <description
    >A custom object (created by the Urjanet Connect app) to store status information about utility credentials</description>
    <label>Utility Credential</label>
    <nameField>
        <label>Utility Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityCredential__c/fields/ProviderName__c.field-meta.xml
<CustomField>
    <fullName>ProviderName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The commonly known name for the utility company.</description>
    <inlineHelpText>The commonly known name for the utility company.</inlineHelpText>
    <label>Provider Name</label>
    <referenceTo>Supplier</referenceTo>
    <relationshipLabel>Utility Credentials</relationshipLabel>
    <relationshipName>UtilityCredentials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UtilityAccountSyncBatch.cls
public with sharing class UtilityAccountSyncBatch implements Database.Batchable<sObject>, Database.AllowsCallouts {
    public UtilityAccountSyncBatch() {
    }

    /**
     * Start implementation
     * @param bc
     *
     * @return
     */
    public Database.Querylocator start(Database.BatchableContext bc) {
        //CRUD / FLS is ignored to ensure that query runs in system context in order to sync over records to Urjanet.
        Logger.getInstance(false)
            .log(UtilityAccountSyncBatch.class.getName(), Logger.Level.INFO, 'Utility Account Sync Batch Started');
        UtilityAccountSelector selector = new UtilityAccountSelector(false, false, false);
        return selector.getUtilAccountsSyncBatchWithoutCredential();
    }

    /**
     * @description process the correlationIds
     * @param  bc    bc description
     * @param  scope scope description
     */
    public void execute(Database.BatchableContext bc, List<sObject> scope) {
        //Run schedule job process
        UtilityAccountService.createQueueItemsForUtilityAccounts(scope);
    }

    public void finish(Database.BatchableContext bc) {
        // Backfill Supplier id field for accounts where supplier id is null
        List<UtilityAccount__c> accountsToUpdate = [
            SELECT Id, UtilityCredential__r.ProviderName__c
            FROM UtilityAccount__c
            WHERE Supplier__c = NULL AND UtilityCredential__r.ProviderName__c != NULL
        ];
        if (!accountsToUpdate.isEmpty()) {
            for (UtilityAccount__c account : accountsToUpdate) {
                account.Supplier__c = account.UtilityCredential__r.ProviderName__c;
            }
            update accountsToUpdate;

            Logger.getInstance(false)
                .log(
                    UtilityAccountSyncBatch.class.getName(),
                    Logger.Level.INFO,
                    'Updated Supplier for ' + accountsToUpdate.size() + ' Utility Accounts'
                );
        }

        Logger.getInstance(false)
            .log(
                UtilityAccountSyncBatch.class.getName(),
                Logger.Level.INFO,
                'QueueItems Successfully Created for Accounts Processing'
            );
    }
}