force-app/main/default/objects/UtilityAccount__c/UtilityAccount__c.object-meta.xml
<CustomObject>
    <description>A custom object (created by the Urjanet Connect app) to store utility account information</description>
    <label>Utility Account</label>
    <nameField>
        <label>Utility Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityAccount__c/fields/CreatedByInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>CreatedByInUrjanet__c</fullName>
    <description>The system user responsible for creating the account in Arcadia&apos;s system.</description>
    <inlineHelpText>The system user responsible for creating the account in Arcadia&apos;s system.</inlineHelpText>
    <label>Created By in Arcadia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/fields/CreatedDateInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>CreatedDateInUrjanet__c</fullName>
    <description>The Date the account was registered in Arcadia’s system.</description>
    <inlineHelpText>The Date the account was registered in Arcadia’s system.</inlineHelpText>
    <label>Created Date in Arcadia</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if an account is active (meaning Urjanet is actively monitoring the account).</description>
    <inlineHelpText>Indicates if an account is active (meaning Urjanet is actively monitoring the account).</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/fields/LastModifiedByInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedByInUrjanet__c</fullName>
    <description>The system user responsible for modifying an account most recently in the Arcadia system.</description>
    <inlineHelpText
    >The system user responsible for modifying an account most recently in the Arcadia system.</inlineHelpText>
    <label>Last Modified By in Arcadia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/fields/LastModifiedInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedInUrjanet__c</fullName>
    <description>The date that an account was modified last in the Arcadia system.</description>
    <inlineHelpText>The date that an account was modified last in the Arcadia system.</inlineHelpText>
    <label>Last Modified in Arcadia</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Account-level statuses that let you know if there are any issues accessing the account or the statement behind the account.</description>
    <inlineHelpText>Account-level statuses that let you know if there are any issues accessing the account or the statement behind the account.</inlineHelpText>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/fields/StatusDetail__c.field-meta.xml
<CustomField>
    <fullName>StatusDetail__c</fullName>
    <description>A detailed status for the account.</description>
    <inlineHelpText>A detailed status for the account.</inlineHelpText>
    <label>Status Detail</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/fields/UtilityCredential__c.field-meta.xml
<CustomField>
    <fullName>UtilityCredential__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Utility Credential</label>
    <referenceTo>UtilityCredential__c</referenceTo>
    <relationshipLabel>Utility Accounts</relationshipLabel>
    <relationshipName>UtilityAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/UtilityCredential__c.object-meta.xml
<CustomObject>
    <description
    >A custom object (created by the Urjanet Connect app) to store status information about utility credentials</description>
    <label>Utility Credential</label>
    <nameField>
        <label>Utility Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityCredential__c/fields/ArcadiaServiceProviderId__c.field-meta.xml
<CustomField>
    <fullName>ArcadiaServiceProviderId__c</fullName>
    <description>Unique Id for the Provider in Arcadia system</description>
    <inlineHelpText>Unique Id for the Provider in Arcadia system</inlineHelpText>
    <label>ArcadiaServiceProviderId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/CorrelationID__c.field-meta.xml
<CustomField>
    <fullName>CorrelationID__c</fullName>
    <description>A unique number to identify this utility credential record within Urjanet&apos;s sytem.</description>
    <externalId>true</externalId>
    <inlineHelpText>A unique number to identify this utility credential record within Urjanet&apos;s sytem.</inlineHelpText>
    <label>Correlation ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/CreatedByInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>CreatedByInUrjanet__c</fullName>
    <description>The system user responsible for creating a credential.</description>
    <inlineHelpText>The system user responsible for creating a credential.</inlineHelpText>
    <label>Created By in Arcadia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether data will continue to be extracted behind this credential.</description>
    <inlineHelpText>Indicates whether data will continue to be extracted behind this credential.</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/LastModifiedByInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedByInUrjanet__c</fullName>
    <description>The system user responsible for modifying a credential most recently.</description>
    <inlineHelpText>The system user responsible for modifying a credential most recently.</inlineHelpText>
    <label>Last Modified By in Arcadia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/LastModifiedInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedInUrjanet__c</fullName>
    <description>The date that a credential was modified last.</description>
    <inlineHelpText>The date that a credential was modified last.</inlineHelpText>
    <label>Last Modified in Arcadia</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/LastUrjanetSyncDateTime__c.field-meta.xml
<CustomField>
    <fullName>LastUrjanetSyncDateTime__c</fullName>
    <description>Date and Time of the last sync with Arcadia</description>
    <inlineHelpText>Date and Time of the last sync with Arcadia</inlineHelpText>
    <label>Last Arcadia Sync</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/NextScheduledRun__c.field-meta.xml
<CustomField>
    <fullName>NextScheduledRun__c</fullName>
    <description>The time that this credential is next scheduled to be ran in our system.</description>
    <inlineHelpText>The time that this credential is next scheduled to be ran in our system.</inlineHelpText>
    <label>Next Scheduled Run</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/ProviderName__c.field-meta.xml
<CustomField>
    <fullName>ProviderName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The commonly known name for the utility company.</description>
    <inlineHelpText>The commonly known name for the utility company.</inlineHelpText>
    <label>Provider Name</label>
    <referenceTo>Supplier</referenceTo>
    <relationshipLabel>Utility Credentials</relationshipLabel>
    <relationshipName>UtilityCredentials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description
    >Credential-level statuses that let you know if there are any issues accessing the provider portal, the data, or with the credential itself.</description>
    <inlineHelpText
    >Credential-level statuses that let you know if there are any issues accessing the provider portal, the data, or with the credential itself.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>PENDING</fullName>
                <label>Pending</label>
            </value>
            <value>
                <fullName>SENT_TO_URJANET</fullName>
                <label>Sent To Arcadia</label>
            </value>
            <value>
                <fullName>ACTION_REQUIRED</fullName>
                <label>Action Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/StatusDetail__c.field-meta.xml
<CustomField>
    <fullName>StatusDetail__c</fullName>
    <description>A detailed status for the credential.</description>
    <inlineHelpText>A detailed status for the credential.</inlineHelpText>
    <label>Status Detail</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>PENDING</fullName>
                <label>Pending</label>
            </value>
            <value>
                <fullName>ACTION_REQUIRED</fullName>
                <label>Action Required</label>
            </value>
            <value>
                <fullName>ACCOUNT_LOCKED</fullName>
                <label>Account Locked</label>
            </value>
            <value>
                <fullName>E_BILL_REQUIRED</fullName>
                <label>E-Bill Required</label>
            </value>
            <value>
                <fullName>LOGIN_FAILURE</fullName>
                <label>Login Failure</label>
            </value>
            <value>
                <fullName>MULTIFACTOR_AUTH_FAILURE</fullName>
                <label>Multi-Factor Authentication Failure</label>
            </value>
            <value>
                <fullName>NAVIGATION_FAILURE</fullName>
                <label>Navigation Failure</label>
            </value>
            <value>
                <fullName>NO_ACCOUNTS_FOUND</fullName>
                <label>No Accounts Found</label>
            </value>
            <value>
                <fullName>NO_ACTION_REQUIRED</fullName>
                <label>No Action Required</label>
            </value>
            <value>
                <fullName>SECURITY_QUESTIONS</fullName>
                <label>Security Questions</label>
            </value>
            <value>
                <fullName>STATEMENT_UNAVAILABLE</fullName>
                <label>Statement Unavailable</label>
            </value>
            <value>
                <fullName>UNDER_REVIEW</fullName>
                <label>Under Review</label>
            </value>
            <value>
                <fullName>UNSUPPORTED_CAPTCHA</fullName>
                <label>Unsupported CAPTCHA</label>
            </value>
            <value>
                <fullName>USER_ACTION_REQUIRED</fullName>
                <label>User Action Required</label>
            </value>
            <value>
                <fullName>WEBSITE_DOWN</fullName>
                <label>Website Down</label>
            </value>
            <value>
                <fullName>ACCOUNT_SETUP_REQUIRED</fullName>
                <label>Account Setup Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/UrjanetId__c.field-meta.xml
<CustomField>
    <fullName>UrjanetId__c</fullName>
    <description>Unique ID for the account on Arcadia system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique ID for the account on Arcadia system.</inlineHelpText>
    <label>ArcadiaId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/Username2__c.field-meta.xml
<CustomField>
    <fullName>Username2__c</fullName>
    <description>Optional parameters required by some providers to access data. The provider object will denote which fields are required for each provider.</description>
    <inlineHelpText>Optional parameters required by some providers to access data. The provider object will denote which fields are required for each provider.</inlineHelpText>
    <label>Username2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/Username3__c.field-meta.xml
<CustomField>
    <fullName>Username3__c</fullName>
    <description>Optional parameters required by some providers to access data. The provider object will denote which fields are required for each provider.</description>
    <inlineHelpText>Optional parameters required by some providers to access data. The provider object will denote which fields are required for each provider.</inlineHelpText>
    <label>Username3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/Username4__c.field-meta.xml
<CustomField>
    <fullName>Username4__c</fullName>
    <description>Optional parameters required by some providers to access data. The provider object will denote which fields are required for each provider.</description>
    <inlineHelpText>Optional parameters required by some providers to access data. The provider object will denote which fields are required for each provider.</inlineHelpText>
    <label>Username4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <description>The provider username.</description>
    <inlineHelpText>The provider username.</inlineHelpText>
    <label>Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UtilityCredentialSelector.cls
public with sharing class UtilityCredentialSelector extends Selector {
    public UtilityCredentialSelector() {
        this(true, true, true);
    }

    public UtilityCredentialSelector(Boolean enforceCRUD, Boolean enforceFLS, Boolean enforceShr) {
        super(Schema.UtilityCredential__c.SObjectType, enforceCRUD, enforceFLS, enforceShr);
    }

    /**
     * Returns a Set that has all of the default fields.
     * @return   Set of Strings that contain the default fields for this object
     */
    public override Set<String> getDefaultFields() {
        Set<String> defaultFields = new Set<String>{
            'Id',
            'Name',
            'CorrelationID__c',
            'CreatedByInUrjanet__c',
            'CreatedDateInUrjanet__c',
            'Enabled__c',
            'LastModifiedByInUrjanet__c',
            'LastModifiedInUrjanet__c',
            'LastUrjanetSyncDateTime__c',
            'NextScheduledRun__c',
            'Status__c',
            'StatusDetail__c',
            'urjanetId__c',
            'Username__c',
            'Username2__c',
            'Username3__c',
            'Username4__c',
            'ProviderName__c',
            'ArcadiaServiceProviderId__c'
        };
        return defaultFields;
    }

    /**
     * Gets UtilityCredential records that need the details synced from Urjanet
     * @return Database.QueryLocator
     */
    public Database.QueryLocator getRecordsForCredentialSyncBatch() {
        Map<String, Object> params = new Map<String, Object>();

        String query = getDefaultQuery();
        query += ' WHERE CorrelationID__c != null';

        return Data.Locator(query, params, this.isEnforcingCRUD(), this.isEnforcingFLS(), this.isEnforcingShr());
    }

    public List<UtilityCredential__c> getUtilityCredentialsByIds(Set<Id> setCredentialIds) {
        List<String> queryFields = new List<String>(this.getDefaultFields());

        Map<String, Object> queryArgs = new Map<String, Object>{ 'setCredentialIds' => setCredentialIds };

        String query =
            'SELECT ' +
            String.join(queryFields, ', ') +
            ' FROM UtilityCredential__c' +
            ' WHERE Id IN :setCredentialIds';

        return new List<UtilityCredential__c>(
            (List<UtilityCredential__c>) Data.read(
                query,
                queryArgs,
                this.isEnforcingCRUD(),
                this.isEnforcingFLS(),
                this.isEnforcingShr()
            )
        );
    }

    public List<UtilityCredential__c> getAllUtilityCredentials() {
        List<String> queryFields = new List<String>(this.getDefaultFields());
        Map<String, Object> queryArgs = new Map<String, Object>{};

        String query = 'SELECT ' + String.join(queryFields, ', ') + ' FROM UtilityCredential__c';

        return new List<UtilityCredential__c>(
            (List<UtilityCredential__c>) Data.read(
                query,
                queryArgs,
                this.isEnforcingCRUD(),
                this.isEnforcingFLS(),
                this.isEnforcingShr()
            )
        );
    }

    public List<UtilityCredential__c> getCredentialAndRelatedAccounts(String credentialId, String actionParamter) {
        String query =
            'SELECT Id, UrjanetId__c, (SELECT Id FROM UtilityAccounts__r)' +
            ' FROM UtilityCredential__c' +
            ' WHERE' +
            (actionParamter == UrjanetConstants.DELETE_IN_BOTH
                ? ' UrjanetId__c = :credentialId'
                : ' Id =:credentialId');
        Map<String, Object> queryArgs = new Map<String, Object>{ 'credentialId' => credentialId };
        return new List<UtilityCredential__c>(
            (List<UtilityCredential__c>) Data.read(
                query,
                queryArgs,
                this.isEnforcingCRUD(),
                this.isEnforcingFLS(),
                this.isEnforcingShr()
            )
        );
    }
}