force-app/main/default/objects/UtilityAccount__c/UtilityAccount__c.object-meta.xml
<CustomObject>
    <description>A custom object (created by the Urjanet Connect app) to store utility account information</description>
    <label>Utility Account</label>
    <nameField>
        <label>Utility Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityAccount__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Supplier</referenceTo>
    <relationshipLabel>Utility Accounts</relationshipLabel>
    <relationshipName>UtilityAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/fields/UtilityCredential__c.field-meta.xml
<CustomField>
    <fullName>UtilityCredential__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Utility Credential</label>
    <referenceTo>UtilityCredential__c</referenceTo>
    <relationshipLabel>Utility Accounts</relationshipLabel>
    <relationshipName>UtilityAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/UtilityCredential__c.object-meta.xml
<CustomObject>
    <description
    >A custom object (created by the Urjanet Connect app) to store status information about utility credentials</description>
    <label>Utility Credential</label>
    <nameField>
        <label>Utility Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityCredential__c/fields/ProviderName__c.field-meta.xml
<CustomField>
    <fullName>ProviderName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The commonly known name for the utility company.</description>
    <inlineHelpText>The commonly known name for the utility company.</inlineHelpText>
    <label>Provider Name</label>
    <referenceTo>Supplier</referenceTo>
    <relationshipLabel>Utility Credentials</relationshipLabel>
    <relationshipName>UtilityCredentials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/UrjanetId__c.field-meta.xml
<CustomField>
    <fullName>UrjanetId__c</fullName>
    <description>Unique ID for the account on Arcadia system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique ID for the account on Arcadia system.</inlineHelpText>
    <label>ArcadiaId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <description>The provider username.</description>
    <inlineHelpText>The provider username.</inlineHelpText>
    <label>Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/testClasses/UtilityAccountSyncBatchTest.cls
@IsTest
public with sharing class UtilityAccountSyncBatchTest {
    @TestSetup
    static void makeData() {
        User adminUser = TestUtility.createUserAdmin('urjanetAdmin@urjanettest.com');
        System.runAs(adminUser) {
            Account account = new Account();
            account.Name = 'Test Account';
            insert account;

            Supplier supplier = new Supplier();
            supplier.Name = 'Test Supplier';
            supplier.AccountId = account.Id;
            insert supplier;

            UtilityCredential__c credential = new UtilityCredential__c();
            credential.Name = 'Test Credential';
            credential.Username__c = 'test';
            credential.ProviderName__c = supplier.Id;
            insert credential;

            UtilityAccount__c utilityAccount = new UtilityAccount__c();
            utilityAccount.UrjanetId__c = 'AccountId';
            utilityAccount.UtilityCredential__c = credential.Id;
            insert utilityAccount;
        }
    }
    @IsTest
    public static void utilityAccountSyncTest() {
        User adminUser = [SELECT Id FROM User WHERE email = 'urjanetAdmin@urjanettest.com' LIMIT 1];
        System.runAs(adminUser) {
            Supplier supplier = [SELECT Id FROM Supplier LIMIT 1];

            Integer batchSize = UrjanetUtils.getBatchSize(false);
            Test.startTest();
            Database.executeBatch(new UtilityAccountSyncBatch(), batchSize);
            Test.stopTest();
            List<AsyncApexJob> AsyncApexJobList = [
                SELECT Id, Status, JobType, ApexClass.Name
                FROM AsyncApexJob
                WHERE JobType = 'BatchApex'
            ];
            CSUtils.itShouldBe('AsyncApexJobList size ', 1, AsyncApexJobList.size());
            CSUtils.itShouldBe(
                'AsyncApexJobList.ApexClass name ',
                'UtilityAccountSyncBatch',
                AsyncApexJobList[0].ApexClass.Name
            );

            UtilityAccount__c result = [
                SELECT Id, UrjanetId__c, Supplier__c
                FROM UtilityAccount__c
                WHERE UrjanetId__c = 'AccountId'
            ];
            CSUtils.itShouldBe('UtilityAccount__c.Supplier Id ', supplier.Id, result.Supplier__c);
        }
    }
}