force-app/main/default/objects/StnryAssetEnrgyUse/fields/UtilityMeterUsage__c.field-meta.xml
<CustomField>
    <fullName>UtilityMeterUsage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A custom field for the meter usage data from which this record was derived.</description>
    <inlineHelpText>A custom field for the meter usage data from which this record was derived.</inlineHelpText>
    <label>Utility Meter Usage</label>
    <referenceTo>UtilityMeterUsage__c</referenceTo>
    <relationshipLabel>Stationary Asset Energy Uses</relationshipLabel>
    <relationshipName>StationaryAssetEnergyUses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityMeterUsage__c/UtilityMeterUsage__c.object-meta.xml
<CustomObject>
    <description>A custom object (created by the Urjanet Connect app) to store utility meter usage data.</description>
    <label>Utility Meter Usage</label>
    <nameField>
        <label>Utility Meter Usage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Meter Usages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityMeterUsage__c/fields/To_Be_Ignored__c.field-meta.xml
<CustomField>
    <fullName>To_Be_Ignored__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if an meter usage is to be ignored for downstream data creation (meaning Urjanet is considering the meter usage to be valid).</description>
    <inlineHelpText>Indicates if an meter usage is to be ignored for downstream data creation (meaning Urjanet is considering the meter usage to be valid).</inlineHelpText>
    <label>To Be Ignored</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UtilityMeterUsage__c/fields/UrjanetId__c.field-meta.xml
<CustomField>
    <fullName>UrjanetId__c</fullName>
    <description>Unique ID for the meter usage on Arcadia system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique ID for the meter usage on Arcadia system.</inlineHelpText>
    <label>ArcadiaId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BaseMeterUsageUpdater.cls
public class BaseMeterUsageUpdater implements IUtilityMeterUsageUpdater {
    public void updateUtilityMeterUsageToBeIgnored(List<Id> meterUsageIds) {
        Database.DMLOptions option = new Database.DMLOptions();
        option.OptAllOrNone = false;
        try {
            List<StnryAssetEnrgyUse> energy = [
                SELECT Id
                FROM StnryAssetEnrgyUse
                WHERE UtilityMeterUsage__r.Id IN :meterUsageIds
            ];
            List<UtilityMeterUsage__c> usageRecords = [
                SELECT Id, UrjanetId__c, To_Be_Ignored__c
                FROM UtilityMeterUsage__c
                WHERE Id IN :meterUsageIds
            ];

            for (UtilityMeterUsage__c usageRecord : usageRecords) {
                usageRecord.To_Be_Ignored__c = true;
            }

            Logger.getInstance(false)
                .log(
                    BaseMeterUsageUpdater.class.getName(),
                    Logger.Level.DEBUG,
                    'Deleting Energy Usage: ' + energy.size()
                );
            Logger.getInstance(false)
                .log(
                    BaseMeterUsageUpdater.class.getName(),
                    Logger.Level.DEBUG,
                    'Updating Meter Usage: ' + meterUsageIds.size()
                );
            Data.remove(energy, false, false, false);

            if (!usageRecords.isEmpty()) {
                
                Logger.getInstance(false)
                    .log(
                        UtilityMeterUsageService.class.getName(),
                        UrjanetUtils.getSObjectName(Schema.UtilityMeterUsage__c.SObjectType),
                        Data.upsurt(
                            usageRecords,
                            Schema.UtilityMeterUsage__c.fields.UrjanetId__c,
                            option,
                            false,
                            false,
                            false,
                            null
                        )
                    );
            }
        } catch (DmlException e) {
            Logger.getInstance()
                .log(
                    BaseMeterUsageUpdater.class.getName(),
                    Logger.Level.ERROR,
                    'DmlException in updateUtilityMeterUsageToBeIgnored Energy : ' + e.getMessage()
                );
        }
        catch (Exception e) {
            Logger.getInstance()
                .log(
                    BaseMeterUsageUpdater.class.getName(),
                    Logger.Level.ERROR,
                    'Exception in updateUtilityMeterUsageToBeIgnored Energy : ' + e.getMessage()
                );
        }
    } 
    
}