force-app/main/default/objects/UtilityMeterProcessorSetting__mdt/UtilityMeterProcessorSetting__mdt.object-meta.xml
<CustomObject>
    <description
    >Custom Metadata used to store the Meter processor class name to be used for each service type</description>
    <label>Utility Meter Processor Setting</label>
    <pluralLabel>Utility Meter Processor Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/UtilityMeterProcessorSetting__mdt/fields/ProcessorClassName__c.field-meta.xml
<CustomField>
    <fullName>ProcessorClassName__c</fullName>
    <description>Meter Processor Class Name</description>
    <inlineHelpText>Meter Processor Class Name</inlineHelpText>
    <label>Meter Processor Class Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityMeterProcessorSetting__mdt/fields/ServiceType__c.field-meta.xml
<CustomField>
    <fullName>ServiceType__c</fullName>
    <description>Meter Service Type</description>
    <inlineHelpText>Meter Service Type</inlineHelpText>
    <label>Meter Service Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MeterProcessorMappingSelector.cls
public with sharing class MeterProcessorMappingSelector extends Selector {
    public MeterProcessorMappingSelector() {
        super(Schema.UtilityMeterProcessorSetting__mdt.SObjectType);
    }
    public MeterProcessorMappingSelector(Boolean enforceCRUD, Boolean enforceFLS, Boolean enforceShr) {
        super(Schema.UtilityMeterProcessorSetting__mdt.SObjectType, enforceCRUD, enforceFLS, enforceShr);
    }

    /**
     * Returns a Set that has all of the default fields.
     * @return   Set of Strings that contain the default fields for this object
     */
    public override Set<String> getDefaultFields() {
        return new Set<String>{ 'Id', 'DeveloperName', 'ProcessorClassName__c', 'ServiceType__c' };
    }
}