force-app/main/default/objects/ServiceTypeToFuelTypeMapping__mdt/ServiceTypeToFuelTypeMapping__mdt.object-meta.xml
<CustomObject>
    <description>Custom mappings for UtilityMeter &quot;Service Type&quot; to Stationary Asset Energy Use &quot;Fuel Type&quot;</description>
    <label>Service Type to Fuel Type Mapping</label>
    <pluralLabel>Service Type to Fuel Type Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/ServiceTypeToFuelTypeMapping__mdt/fields/FuelType__c.field-meta.xml
<CustomField>
    <fullName>FuelType__c</fullName>
    <description>NZC Fuel Type</description>
    <inlineHelpText>NZC Fuel Type</inlineHelpText>
    <label>Fuel Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTypeToFuelTypeMapping__mdt/fields/ServiceType__c.field-meta.xml
<CustomField>
    <fullName>ServiceType__c</fullName>
    <description>Urjanet Service Type</description>
    <inlineHelpText>Urjanet Service Type</inlineHelpText>
    <label>Service Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ServiceTypeToFuelTypeMappingSelector.cls
public with sharing class ServiceTypeToFuelTypeMappingSelector extends Selector {
    public ServiceTypeToFuelTypeMappingSelector() {
        super(Schema.ServiceTypeToFuelTypeMapping__mdt.SObjectType);
    }
    public ServiceTypeToFuelTypeMappingSelector(Boolean enforceCRUD, Boolean enforceFLS, Boolean enforceShr) {
        super(Schema.ServiceTypeToFuelTypeMapping__mdt.SObjectType, enforceCRUD, enforceFLS, enforceShr);
    }

    /**
     * Returns a Set that has all of the default fields.
     * @return   Set of Strings that contain the default fields for this object
     */
    public override Set<String> getDefaultFields() {
        return new Set<String>{ 'Id', 'DeveloperName', 'FuelType__c', 'ServiceType__c' };
    }
}