force-app/main/default/objects/Credential_Deletion_Log__c/Credential_Deletion_Log__c.object-meta.xml
<CustomObject>
    <label>Credential Deletion Log</label>
    <nameField>
        <displayFormat>CDL-{00000}</displayFormat>
        <label>Credential Deletion Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credential Deletion Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credential_Deletion_Log__c/fields/Credential_Id__c.field-meta.xml
<CustomField>
    <fullName>Credential_Id__c</fullName>
    <label>Credential Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credential_Deletion_Log__c/fields/Deletion_Log_Id__c.field-meta.xml
<CustomField>
    <fullName>Deletion_Log_Id__c</fullName>
    <label>Deletion Log Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Credential_Deletion_Log__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Credential_Deletion_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CredentialDeletionJobSelector.cls
public with sharing class CredentialDeletionJobSelector extends Selector {
    public CredentialDeletionJobSelector() {
        this(true, true, true);
    }
    public CredentialDeletionJobSelector(Boolean enforceCRUD, Boolean enforceFLS, Boolean enforceShr) {
        super(Schema.Credential_Deletion_Log__c.SObjectType, enforceCRUD, enforceFLS, enforceShr);
    }

    /**
     * Returns a Set that has all of the default fields.
     * @return   Set of Strings that contain the default fields for this object
     */
    public override Set<String> getDefaultFields() {
        Set<String> defaultFields = new Set<String>{
            'Id',
            'Name',
            'Credential_Id__c',
            'Deletion_Log_Id__c',
            'Error_Message__c',
            'Status__c'
        };
        return defaultFields;
    }

    /**
     * Gets UtilityCredential records that need the details synced from Urjanet
     * @return Database.QueryLocator
     */
    public Database.QueryLocator getRecordsForCredentialDeletionLogBatch() {
        Map<String, Object> params = new Map<String, Object>();

        String query = getDefaultQuery();
        query += ' WHERE Status__c = \'In Progress\'';
        return Data.Locator(query, params, this.isEnforcingCRUD(), this.isEnforcingFLS(), this.isEnforcingShr());
    }

    /**
     * Gets CredentialDeletion record based on Deletion LogID
     * @return Credential_Deletion_Log__c
     */
    public List<Credential_Deletion_Log__c> getCredentialDeletionLogBasedonDeletionLogId(String deletionLog) {
        String query = getDefaultQuery();
        query += ' WHERE Deletion_Log_Id__c = :deletionLog limit 1';
        Map<String, Object> queryArgs = new Map<String, Object>{ 'deletionLog' => deletionLog };
        return new List<Credential_Deletion_Log__c>(
            (List<Credential_Deletion_Log__c>) Data.read(
                query,
                queryArgs,
                this.isEnforcingCRUD(),
                this.isEnforcingFLS(),
                this.isEnforcingShr()
            )
        );
    }
}