force-app/main/default/objects/Credential_Deletion_Log__c/Credential_Deletion_Log__c.object-meta.xml
<CustomObject>
    <label>Credential Deletion Log</label>
    <nameField>
        <displayFormat>CDL-{00000}</displayFormat>
        <label>Credential Deletion Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credential Deletion Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityAccount__c/UtilityAccount__c.object-meta.xml
<CustomObject>
    <description>A custom object (created by the Urjanet Connect app) to store utility account information</description>
    <label>Utility Account</label>
    <nameField>
        <label>Utility Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityAccount__c/fields/UtilityCredential__c.field-meta.xml
<CustomField>
    <fullName>UtilityCredential__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Utility Credential</label>
    <referenceTo>UtilityCredential__c</referenceTo>
    <relationshipLabel>Utility Accounts</relationshipLabel>
    <relationshipName>UtilityAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/UtilityCredential__c.object-meta.xml
<CustomObject>
    <description
    >A custom object (created by the Urjanet Connect app) to store status information about utility credentials</description>
    <label>Utility Credential</label>
    <nameField>
        <label>Utility Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityMeter__c/UtilityMeter__c.object-meta.xml
<CustomObject>
    <description>A custom object (created by the Urjanet Connect app) to store utility meter information</description>
    <label>Utility Meter</label>
    <nameField>
        <label>Utility Meter Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Meters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityMeterUsage__c/UtilityMeterUsage__c.object-meta.xml
<CustomObject>
    <description>A custom object (created by the Urjanet Connect app) to store utility meter usage data.</description>
    <label>Utility Meter Usage</label>
    <nameField>
        <label>Utility Meter Usage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Meter Usages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityMeterUsage__c/fields/UtilityMeter__c.field-meta.xml
<CustomField>
    <fullName>UtilityMeter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Utility Meter for this Utility Meter Usage record.</description>
    <inlineHelpText>The Utility Meter for this Utility Meter Usage record.</inlineHelpText>
    <label>Utility Meter</label>
    <referenceTo>UtilityMeter__c</referenceTo>
    <relationshipLabel>Utility Meter Usages</relationshipLabel>
    <relationshipName>UtilityMeterUsages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityStatementFile__c/UtilityStatementFile__c.object-meta.xml
<CustomObject>
    <label>Utility Statement File</label>
    <nameField>
        <label>Utility Statement File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Statement Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/QueueItemProcessorFactory.cls
/**
 * Created by mike on 5/10/22.
 */

public with sharing class QueueItemProcessorFactory {
    public static Type getProcessorType(SObjectType objectType) {
        if (objectType == UtilityMeter__c.SObjectType) {
            return UtilityMeterProcessor.class;
        } else if (objectType == UtilityMeterUsage__c.SObjectType) {
            return UtilityMeterUsageProcessor.class;
        } else if (objectType == UtilityCredential__c.SObjectType) {
            return UtilityCredentialProcessor.class;
        } else if (objectType == UtilityAccount__c.SObjectType) {
            return UtilityAccountProcessor.class;
        } else if (objectType == UtilityStatementFile__c.SObjectType) {
            return UtilityStatementFileProcessor.class;
        } else if (objectType == Credential_Deletion_Log__c.SObjectType) {
            return CredentialDeletionJobProcessor.class;
        } else {
            throw new NoProcessorDefinedException();
        }
    }

    public class NoProcessorDefinedException extends Exception {
    }
}