force-app/main/default/objects/Credential_Deletion_Log__c/Credential_Deletion_Log__c.object-meta.xml
<CustomObject>
    <label>Credential Deletion Log</label>
    <nameField>
        <displayFormat>CDL-{00000}</displayFormat>
        <label>Credential Deletion Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credential Deletion Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credential_Deletion_Log__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Credential_Deletion_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CredentialDeletionJobService.cls
public with sharing class CredentialDeletionJobService {
    //default constructor

    public static void createQueueItemsForCredentialDeletionLogs(
        List<Credential_Deletion_Log__c> credentialDeletionLogs
    ) {
        Type processorClass = QueueItemProcessorFactory.getProcessorType(Credential_Deletion_Log__c.SObjectType);
        List<Database.SaveResult> saveResults = new QueueItemsBuilder(credentialDeletionLogs, processorClass)
            .buildQueueItemsPerRecord()
            .createRecords();
        UrjanetUtils.logFailures(
            CredentialDeletionJobService.class.getName(),
            String.valueOf(Credential_Deletion_Log__c.SObjectType),
            saveResults
        );
    }

    public static void deleteCredentialDeletionLog(String deletionLogId) {
        List<Credential_Deletion_Log__c> credentialDeletionLogs = (List<Credential_Deletion_Log__c>) new CredentialDeletionJobSelector()
            .getCredentialDeletionLogBasedonDeletionLogId(deletionLogId);
        if (credentialDeletionLogs != null && !credentialDeletionLogs.isEmpty()) {
            Data.remove(credentialDeletionLogs, false, false, false);
        }
    }

    public static void updateCredentialDeletionLogWithError(String deletionLogId, String errorMsg) {
        List<Credential_Deletion_Log__c> credentialDeletionLogs = (List<Credential_Deletion_Log__c>) new CredentialDeletionJobSelector()
            .getCredentialDeletionLogBasedonDeletionLogId(deletionLogId);
        if (credentialDeletionLogs != null && !credentialDeletionLogs.isEmpty()) {
            credentialDeletionLogs[0].Error_Message__c = errorMsg;
            credentialDeletionLogs[0].Status__c = UrjanetConstants.CRED_DEL_STATUS_FAILED;
            DATA.modify(credentialDeletionLogs[0], false, false, false);
        }
    }
}