force-app/main/default/objects/Credential_Deletion_Log__c/Credential_Deletion_Log__c.object-meta.xml
<CustomObject>
    <label>Credential Deletion Log</label>
    <nameField>
        <displayFormat>CDL-{00000}</displayFormat>
        <label>Credential Deletion Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credential Deletion Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credential_Deletion_Log__c/fields/Credential_Id__c.field-meta.xml
<CustomField>
    <fullName>Credential_Id__c</fullName>
    <label>Credential Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credential_Deletion_Log__c/fields/Deletion_Log_Id__c.field-meta.xml
<CustomField>
    <fullName>Deletion_Log_Id__c</fullName>
    <label>Deletion Log Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Credential_Deletion_Log__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Credential_Deletion_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utility_Account_Meter_Relation__c/Utility_Account_Meter_Relation__c.object-meta.xml
<CustomObject>
    <label>Utility Account Meter Relation</label>
    <nameField>
        <label>Utility_Account_Meter_Relation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Meter Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Utility_Account_Meter_Relation__c/fields/Utility_Account__c.field-meta.xml
<CustomField>
    <fullName>Utility_Account__c</fullName>
    <label>Utility Account</label>
    <referenceTo>UtilityAccount__c</referenceTo>
    <relationshipLabel>Utility Account Meter Relations</relationshipLabel>
    <relationshipName>Utility_Account_Meter_Relations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Utility_Account_Meter_Relation__c/fields/Utility_Meter__c.field-meta.xml
<CustomField>
    <fullName>Utility_Meter__c</fullName>
    <label>Utility Meter</label>
    <referenceTo>UtilityMeter__c</referenceTo>
    <relationshipLabel>Utility Account Meter Relations</relationshipLabel>
    <relationshipName>Utility_Account_Meter_Relations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/UtilityAccount__c.object-meta.xml
<CustomObject>
    <description>A custom object (created by the Urjanet Connect app) to store utility account information</description>
    <label>Utility Account</label>
    <nameField>
        <label>Utility Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityAccount__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Account-level statuses that let you know if there are any issues accessing the account or the statement behind the account.</description>
    <inlineHelpText>Account-level statuses that let you know if there are any issues accessing the account or the statement behind the account.</inlineHelpText>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/fields/UtilityCredential__c.field-meta.xml
<CustomField>
    <fullName>UtilityCredential__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Utility Credential</label>
    <referenceTo>UtilityCredential__c</referenceTo>
    <relationshipLabel>Utility Accounts</relationshipLabel>
    <relationshipName>UtilityAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/UtilityCredential__c.object-meta.xml
<CustomObject>
    <description
    >A custom object (created by the Urjanet Connect app) to store status information about utility credentials</description>
    <label>Utility Credential</label>
    <nameField>
        <label>Utility Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityCredential__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description
    >Credential-level statuses that let you know if there are any issues accessing the provider portal, the data, or with the credential itself.</description>
    <inlineHelpText
    >Credential-level statuses that let you know if there are any issues accessing the provider portal, the data, or with the credential itself.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>PENDING</fullName>
                <label>Pending</label>
            </value>
            <value>
                <fullName>SENT_TO_URJANET</fullName>
                <label>Sent To Arcadia</label>
            </value>
            <value>
                <fullName>ACTION_REQUIRED</fullName>
                <label>Action Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/UrjanetId__c.field-meta.xml
<CustomField>
    <fullName>UrjanetId__c</fullName>
    <description>Unique ID for the account on Arcadia system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique ID for the account on Arcadia system.</inlineHelpText>
    <label>ArcadiaId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/UtilityMeter__c/UtilityMeter__c.object-meta.xml
<CustomObject>
    <description>A custom object (created by the Urjanet Connect app) to store utility meter information</description>
    <label>Utility Meter</label>
    <nameField>
        <label>Utility Meter Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Meters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityMeter__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(
    ISBLANK(StationaryAssetEnvironmentalSource__c),
    IMAGE(
        IF(
            $Setup.UrjanetSettings__c.DevelopmentOrg__c = FALSE,
            &quot;/resource/urjanet__UrjanetNZCAssets/UrjanetNZCAssets/img/arcadia_wrong_symbol.png&quot;,
            &quot;/resource/UrjanetNZCAssets/UrjanetNZCAssets/img/arcadia_wrong_symbol.png&quot;
        ),
        &quot;Cross Image&quot;,
        10,
        10
    ) &amp; &quot; Must be linked to stationary asset&quot;,
    IMAGE(
        IF(
            $Setup.UrjanetSettings__c.DevelopmentOrg__c = FALSE,
            &quot;/resource/urjanet__UrjanetNZCAssets/UrjanetNZCAssets/img/arcadia_right_symbol.png&quot;,
            &quot;/resource/UrjanetNZCAssets/UrjanetNZCAssets/img/arcadia_right_symbol.png&quot;
        ),
        &quot;Tick Image&quot;,
        10,
        10
    ) &amp; &quot; OK&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Connection Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityMeter__c/fields/UrjanetId__c.field-meta.xml
<CustomField>
    <fullName>UrjanetId__c</fullName>
    <description>Unique ID for the meter on Arcadia system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique ID for the meter on Arcadia system.</inlineHelpText>
    <label>ArcadiaId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/DeleteCredentialApiController.cls
public without sharing class DeleteCredentialApiController {
    @AuraEnabled
    public static DeletePlugApiResponse.DeleteApiUiResponse deleteCredentialMethod(
        String credentialId,
        String actionParameter
    ) {
        DeletePlugApiResponse.DeleteApiUiResponse uiResponse = new DeletePlugApiResponse.DeleteApiUiResponse();
        try {
            UtilityCredential__c credentialRecord = (UtilityCredential__c) new UtilityCredentialSelector()
                .getRecordById(credentialId);
            if (actionParameter == UrjanetConstants.DELETE_IN_BOTH) {
                if (credentialRecord != null && credentialRecord.UrjanetId__c != null) {
                    uiResponse = deleteCredentialApiCallout(credentialRecord.UrjanetId__c);
                } else {
                    String errorMessage = 'Unable to Process the Credential :' + credentialId + ' as ArcadiaId is null';
                    Logger.getInstance()
                        .log(DeleteCredentialApiController.class.getName(), Logger.Level.ERROR, errorMessage);
                    uiResponse.statusCode = UrjanetConstants.FAILURE_MESSAGE;
                    uiResponse.message = errorMessage;
                }
            }
            if (actionParameter == UrjanetConstants.DELETE_IN_SFDC) {
                deleteCredentialsAndRelatedRecords(credentialRecord.Id, UrjanetConstants.DELETE_IN_SFDC);
                uiResponse.message = 'Credential and related Records Deleted Successfully in Net Zero Cloud!!';
                uiResponse.statusCode = UrjanetConstants.SUCCESS_MESSAGE;
            }
        } catch (Exception e) {
            Logger.getInstance().log(DeleteCredentialApiController.class.getName(), e);
            throw new AuraHandledException(e.getMessage());
        }
        return uiResponse;
    }

    /**
     * this method is used by the Delete Action to call Delete API by sending the credential id to delete the credentials & realted records
     */
    public static DeletePlugApiResponse.DeleteApiUiResponse deleteCredentialApiCallout(String credentialIdToBeDeleted) {
        DeletePlugApiResponse.DeleteApiUiResponse uiResponse = new DeletePlugApiResponse.DeleteApiUiResponse();
        List<Credential_Deletion_Log__c> existingDelLogs = new List<Credential_Deletion_Log__c>();
        String deletionJobId = '';

        //Before calling the Delete API we are calling Disable API for disabling the credenitals and other associated records in ODIN so that these records will not be available for sync
        DisablePlugApiResponse disableRes;
        existingDelLogs = checkForExistingCredentialDeletionLogs(credentialIdToBeDeleted);
        if (existingDelLogs != null && !existingDelLogs.isEmpty()) {
            deleteCredentialsAndRelatedRecords(credentialIdToBeDeleted, UrjanetConstants.DELETE_IN_BOTH);
            uiResponse.message = 'Credential and related Records Deleted Successfully';
            uiResponse.statusCode = UrjanetConstants.SUCCESS_MESSAGE;
            return uiResponse;
        } else {
            disableRes = DisableCredentialApiController.disableCredentialApiCallout(credentialIdToBeDeleted);
        }
        if (disableRes != null && disableRes.statusCode == 202 && disableRes.id != null) {
            DeletePlugApiResponse deleteResponse = (DeletePlugApiResponse) new UrjanetApiClient()
                .getUrjanetResponse(
                    UrjanetEnums.RequestType.DELETE_CREDENTIAL,
                    UrjanetEnums.ApiMethod.DELETE_METHOD,
                    new List<String>{ credentialIdToBeDeleted }
                );

            if (deleteResponse.statusCode == 200 && deleteResponse.id != null && deleteResponse.id.contains('del_')) {
                deletionJobId = deleteResponse.id.substringAfter('del_');
                if (
                    deleteResponse.status != null &&
                    (deleteResponse.status == UrjanetConstants.DELETE_API_STATUS_SCHEDULED ||
                    deleteResponse.status == UrjanetConstants.DELETE_API_STATUS_PENDING)
                ) {
                    //Before deleting the Credential in sfdc we are storing the deletion job id from ODIN to track the status of the Deletion Job
                    Credential_Deletion_Log__c credLog = createDeletionLog(credentialIdToBeDeleted, deletionJobId);
                    deleteCredentialsAndRelatedRecords(credentialIdToBeDeleted, UrjanetConstants.DELETE_IN_BOTH);
                    uiResponse.message = 'Credential and related Records Deleted Successfully';
                    uiResponse.statusCode = UrjanetConstants.SUCCESS_MESSAGE;
                }
            } else {
                throw new ArcadiaCalloutServiceException(
                    UrjanetConstants.FAILED_TO_DELETE_CREDENTIAL +
                        credentialIdToBeDeleted +
                        ' , ' +
                        (deleteResponse.statusCode != null
                            ? ' Status Code :' + String.valueOf(deleteResponse.statusCode)
                            : '') +
                        +' , ' +
                        (deleteResponse.errorMsg != null ? deleteResponse.errorMsg : '')
                );
            }
        } else {
            throw new ArcadiaCalloutServiceException(
                UrjanetConstants.FAILED_TO_DISABLE_CREDENTIAL +
                    credentialIdToBeDeleted +
                    +' , ' +
                    (disableRes.statusCode != null ? ' Status Code :' + String.valueOf(disableRes.statusCode) : '') +
                    +' , ' +
                    (disableRes.errorMsg != null ? disableRes.errorMsg : '')
            );
        }
        return uiResponse;
    }

    /**
     * to Create the Deletion log record to track the status of the deletion log
     */
    private static Credential_Deletion_Log__c createDeletionLog(String credentialIdToBeDeleted, String deletionJobId) {
        Credential_Deletion_Log__c credLog = prepareCredentialDeletionLogRecord(
            credentialIdToBeDeleted,
            deletionJobId,
            ''
        );
        Database.DMLOptions option = new Database.DMLOptions();
        option.OptAllOrNone = false;
        Logger.getInstance(false)
            .log(
                UtilityCredentialService.class.getName(),
                UrjanetUtils.getSObjectName(Schema.Credential_Deletion_Log__c.SObjectType),
                Data.create(new List<sObject>{ credLog }, option, false, false, false)
            );
        return credLog;
    }

    @testVisible
    private static Credential_Deletion_Log__c prepareCredentialDeletionLogRecord(
        String credId,
        String delId,
        String errMessage
    ) {
        Credential_Deletion_Log__c credDeletionLog = new Credential_Deletion_Log__c();
        credDeletionLog.Credential_Id__c = credId;
        credDeletionLog.Deletion_Log_Id__c = delId;
        credDeletionLog.Error_Message__c = errMessage;
        credDeletionLog.Status__c = UrjanetConstants.CRED_DEL_STATUS_INPROGRESS;
        return credDeletionLog;
    }

    /**
     * check for existing deletion log , if exist which means the deletion request is already sent
     */
    private static List<Credential_Deletion_Log__c> checkForExistingCredentialDeletionLogs(String credentialID) {
        List<Credential_Deletion_Log__c> exisitingCredDeletionLogs = [
            SELECT Id, Credential_Id__c, Deletion_Log_Id__c
            FROM Credential_Deletion_Log__c
            WHERE Credential_Id__c = :credentialID AND Status__c = :UrjanetConstants.CRED_DEL_STATUS_INPROGRESS
            LIMIT 1
        ];
        return exisitingCredDeletionLogs;
    }

    /**
     * This method will delete the Credential record and its associated Utility Accounts , Utility Meters , Usages
     */
    private static void deleteCredentialsAndRelatedRecords(String credentialId, String actionParameter) {
        List<UtilityCredential__c> credentialRecords = (List<UtilityCredential__c>) new UtilityCredentialSelector()
            .getCredentialAndRelatedAccounts(credentialId, actionParameter);
        if (credentialRecords != null && !credentialRecords.isEmpty()) {
            List<Utility_Account_Meter_Relation__c> utilityMeterRelations = new List<Utility_Account_Meter_Relation__c>();
            List<UtilityMeter__c> utilityMeters = new List<UtilityMeter__c>();

            if (credentialRecords[0].UtilityAccounts__r != null && !credentialRecords[0].UtilityAccounts__r.isEmpty()) {
                utilityMeterRelations = [
                    SELECT Id, Utility_Account__c, Utility_Meter__c
                    FROM Utility_Account_Meter_Relation__c
                    WHERE Utility_Account__c IN :credentialRecords[0].UtilityAccounts__r
                ];
            }
            Set<Id> meterIdSet = new Set<Id>();
            for (Utility_Account_Meter_Relation__c meterRelation : utilityMeterRelations) {
                if (meterRelation.Utility_Meter__c != null) {
                    meterIdSet.add(meterRelation.Utility_Meter__c);
                }
            }
            if (meterIdSet != null && !meterIdSet.isEmpty()) {
                utilityMeters = [
                    SELECT Id
                    FROM UtilityMeter__c
                    WHERE Id IN :meterIdSet
                ];
            }

            if (utilityMeters != null && !utilityMeters.isEmpty()) {
                //Method already exist for Deleting meters and Usages reusing it here
                UtilityMeterUsageService.checkForMeterWithUsageIdNullAndDelete(utilityMeters);
                Data.remove(utilityMeters, false, false, false);
            }

            if (credentialRecords[0].UtilityAccounts__r != null && !credentialRecords[0].UtilityAccounts__r.isEmpty()) {
                Data.remove(credentialRecords[0].UtilityAccounts__r, false, false, false);
            }
            Data.remove(credentialRecords[0], false, false, false);
        }
    }
}