force-app/main/default/objects/Credential_Deletion_Log__c/Credential_Deletion_Log__c.object-meta.xml
<CustomObject>
    <label>Credential Deletion Log</label>
    <nameField>
        <displayFormat>CDL-{00000}</displayFormat>
        <label>Credential Deletion Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credential Deletion Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credential_Deletion_Log__c/fields/Deletion_Log_Id__c.field-meta.xml
<CustomField>
    <fullName>Deletion_Log_Id__c</fullName>
    <label>Deletion Log Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/CS-QueueScience/objects/QueueItem__c/QueueItem__c.object-meta.xml
<CustomObject>
    <label>Queue Item</label>
    <nameField>
        <displayFormat>QI-{000000000}</displayFormat>
        <label>Queue Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Queue Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/CS-QueueScience/objects/QueueItem__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <description>Contains the SFDC Id of the record to be processed.</description>
    <externalId>true</externalId>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CredentialDeletionJobProcessor.cls
public with sharing class CredentialDeletionJobProcessor extends QueueItemWorkerBase {
    public override QueueItem__c process(QueueItem__c queueItem) {
        // Ignoring security here since this is a system process
        Credential_Deletion_Log__c credentialJobToProcess = (Credential_Deletion_Log__c) new CredentialDeletionJobSelector(
                false,
                false,
                false
            )
            .getRecordById(queueItem.RecordId__c);

        if (credentialJobToProcess == null || credentialJobToProcess.Deletion_Log_Id__c == null) {
            Logger.getInstance()
                .log(
                    CredentialDeletionJobProcessor.class.getName(),
                    Logger.Level.WARN,
                    'Unable to Process Credential Deletionlog as Deletion_Log_Id__c is null : ' + queueItem.RecordId__c
                );
            return queueItem;
        }

        CredentialDeletionJobApiResponse deletionJobResponse = (CredentialDeletionJobApiResponse) new UrjanetApiClient()
            .getUrjanetResponse(
                UrjanetEnums.RequestType.GET_DELETION_JOB_STATUS,
                UrjanetEnums.ApiMethod.GET,
                new List<String>{ credentialJobToProcess.Deletion_Log_Id__c }
            );
        if (
            deletionJobResponse.id != null &&
            (deletionJobResponse.status == UrjanetConstants.CRED_DELETION_JOB_STATUS_COMPLETED ||
            deletionJobResponse.status == UrjanetConstants.CRED_DELETION_JOB_STATUS_SUCCESS)
        ) {
            CredentialDeletionJobService.deleteCredentialDeletionLog(credentialJobToProcess.Deletion_Log_Id__c);
        }

        if (deletionJobResponse.errorMsg != null) {
            Logger.getInstance()
                .log(
                    CredentialDeletionJobProcessor.class.getName(),
                    Logger.Level.ERROR,
                    UrjanetConstants.ERROR_IN_PROCESSING_CREDENTIAL_DELETION_JOB +
                        credentialJobToProcess.Deletion_Log_Id__c +
                        (deletionJobResponse.statusCode != null
                            ? ' Status Code :' + String.valueOf(deletionJobResponse.statusCode)
                            : ' ') +
                        deletionJobResponse.errorMsg
                );

            CredentialDeletionJobService.updateCredentialDeletionLogWithError(
                credentialJobToProcess.Deletion_Log_Id__c,
                deletionJobResponse.errorMsg
            );
        }
        return queueItem;
    }
}