force-app/main/default/objects/Credential_Deletion_Log__c/Credential_Deletion_Log__c.object-meta.xml
<CustomObject>
    <label>Credential Deletion Log</label>
    <nameField>
        <displayFormat>CDL-{00000}</displayFormat>
        <label>Credential Deletion Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credential Deletion Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credential_Deletion_Log__c/fields/Credential_Id__c.field-meta.xml
<CustomField>
    <fullName>Credential_Id__c</fullName>
    <label>Credential Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credential_Deletion_Log__c/fields/Deletion_Log_Id__c.field-meta.xml
<CustomField>
    <fullName>Deletion_Log_Id__c</fullName>
    <label>Deletion Log Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Credential_Deletion_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/UtilityCredential__c.object-meta.xml
<CustomObject>
    <description
    >A custom object (created by the Urjanet Connect app) to store status information about utility credentials</description>
    <label>Utility Credential</label>
    <nameField>
        <label>Utility Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityCredential__c/fields/CorrelationID__c.field-meta.xml
<CustomField>
    <fullName>CorrelationID__c</fullName>
    <description>A unique number to identify this utility credential record within Urjanet&apos;s sytem.</description>
    <externalId>true</externalId>
    <inlineHelpText>A unique number to identify this utility credential record within Urjanet&apos;s sytem.</inlineHelpText>
    <label>Correlation ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description
    >Credential-level statuses that let you know if there are any issues accessing the provider portal, the data, or with the credential itself.</description>
    <inlineHelpText
    >Credential-level statuses that let you know if there are any issues accessing the provider portal, the data, or with the credential itself.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>PENDING</fullName>
                <label>Pending</label>
            </value>
            <value>
                <fullName>SENT_TO_URJANET</fullName>
                <label>Sent To Arcadia</label>
            </value>
            <value>
                <fullName>ACTION_REQUIRED</fullName>
                <label>Action Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/UrjanetId__c.field-meta.xml
<CustomField>
    <fullName>UrjanetId__c</fullName>
    <description>Unique ID for the account on Arcadia system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique ID for the account on Arcadia system.</inlineHelpText>
    <label>ArcadiaId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CredentialDeletionJobBatchTest.cls
@isTest
public class CredentialDeletionJobBatchTest {
    @testSetup
    static void testSetupMethod() {
        User adminUser = TestUtility.createUserAdmin('arcadiaAdmin1@test.com');
        System.runAs(adminUser) {
            UtilityCredential__c cred = new UtilityCredential__c(
                UrjanetId__c = TestUtility.CREDENTIAL_ID,
                CorrelationId__c = 'test-correlation-Id',
                Name = 'Test Cred'
            );
            insert cred;
            List<Credential_Deletion_Log__c> deletionLogs = new List<Credential_Deletion_Log__c>();
            Credential_Deletion_Log__c deletionLog = new Credential_Deletion_Log__c(
                Status__c = UrjanetConstants.CRED_DEL_STATUS_INPROGRESS,
                Credential_Id__c = cred.Id,
                Deletion_Log_Id__c = 'test-deletionlog-id'
            );
            deletionLogs.add(deletionLog);
            Credential_Deletion_Log__c deletionLogWithOutDeleiotnLogId = new Credential_Deletion_Log__c(
                Status__c = UrjanetConstants.CRED_DEL_STATUS_INPROGRESS,
                Credential_Id__c = cred.Id
            );
            deletionLogs.add(deletionLogWithOutDeleiotnLogId);
            insert deletionLogs;
        }
    }
    @isTest
    static void testCredentialDeletionJobBatch() {
        User adminUser = [SELECT Id FROM User WHERE email = 'arcadiaAdmin1@test.com' LIMIT 1];
        System.runAs(adminUser) {
            Test.StartTest();
            TestUtility.getStaticResourceCalloutMock('CredentialDeletionJobApiResponse', 200);
            Integer batchSize = UrjanetUtils.getBatchSize(false);
            try {
                CredentialDeletionJobBatch batch = new CredentialDeletionJobBatch();
                Database.executeBatch(batch, batchSize);
            } catch (Exception e) {
                system.debug('Exception :' + e.getMessage());
            }
            Test.stopTest();
            List<AsyncApexJob> AsyncApexJobList = [
                SELECT Id, Status, JobType, ApexClass.Name
                FROM AsyncApexJob
                WHERE JobType = 'BatchApex'
            ];
            CSUtils.itShouldBe('AsyncApexJobList size ', 1, AsyncApexJobList.size());
            CSUtils.itShouldBe(
                'AsyncApexJobList.ApexClass name ',
                'CredentialDeletionJobBatch',
                AsyncApexJobList[0].ApexClass.Name
            );
            List<Credential_Deletion_Log__c> deletionLogs = [SELECT Id FROM Credential_Deletion_Log__c];
            CSUtils.itShouldBe('deletionLogs size should be 1 as one gets deleted ', 1, deletionLogs.size());
        }

    }
    @isTest
    static void testCredentialDeletionJobBatchFailure() {
        User adminUser = [SELECT Id FROM User WHERE email = 'arcadiaAdmin1@test.com' LIMIT 1];
        System.runAs(adminUser) {
            Test.StartTest();
            Integer batchSize = UrjanetUtils.getBatchSize(false);
            TestUtility.getStaticResourceCalloutMock('GenericFailureResponse', 400);
            try {
                CredentialDeletionJobBatch batch = new CredentialDeletionJobBatch();
                Database.executeBatch(batch, batchSize);
            } catch (Exception e) {
            }
            Test.stopTest();
            List<AsyncApexJob> AsyncApexJobList = [
                SELECT Id, Status, JobType, ApexClass.Name
                FROM AsyncApexJob
                WHERE JobType = 'BatchApex'
            ];
            CSUtils.itShouldBe('AsyncApexJobList size ', 1, AsyncApexJobList.size());
            CSUtils.itShouldBe(
                'AsyncApexJobList.ApexClass name ',
                'CredentialDeletionJobBatch',
                AsyncApexJobList[0].ApexClass.Name
            );
            List<Credential_Deletion_Log__c> deletionLogs = [SELECT Id FROM Credential_Deletion_Log__c];
            CSUtils.itShouldBe('deletionLogs size should be 2 as no one gets deleted ', 2, deletionLogs.size());
        }
    }
    @isTest
    static void testCredentialDeletionJobBatchMalformedJson() {
        User adminUser = [SELECT Id FROM User WHERE email = 'arcadiaAdmin1@test.com' LIMIT 1];
        System.runAs(adminUser) {
            CredentialDeletionJobResponseParser parser = new CredentialDeletionJobResponseParser();
            Test.startTest();
            HttpResponse response = new HttpResponse();
            response.setStatusCode(200);
            response.setBody('[{"correlationId":""}]');
            UrjanetResponse res = new UrjanetResponse();
            try {
                res = parser.parseResponse(response);
            } catch (Exception e) {
                system.debug('Exception ' + e.getMessage());
            }
            Test.stopTest();
            CSUtils.itShouldBe(
                'Error message should contain Malformed JSON:',
                true,
                res.ex.getMessage().contains('Malformed JSON:')
            );
        }
    }
}