force-app/main/default/objects/Supplier/fields/ElectricityEmissionsFactors__c.field-meta.xml
<CustomField>
    <fullName>ElectricityEmissionsFactors__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
    >A custom field so that the Urjanet app can create Stationary Asset Environmental Sources (since the emissions factor fields are required).</description>
    <inlineHelpText
    >The selection placed in this field will be used as the "Electricity Emissions Factors" field selection whenever the Urjanet App automatically creates Stationary Asset Environmental Sources from this Supplier.</inlineHelpText>
    <label>Electricity Emissions Factors</label>
    <referenceTo>ElectricityEmssnFctrSet</referenceTo>
    <relationshipLabel>Supplier</relationshipLabel>
    <relationshipName>Supplier</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier/fields/OtherEmissionsFactors__c.field-meta.xml
<CustomField>
    <fullName>OtherEmissionsFactors__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
    >A custom field so that the Urjanet app can create Stationary Asset Environmental Sources (since the emissions factor fields are required).</description>
    <inlineHelpText
    >The selection placed in this field will be used as the "Other Emissions Factors" field selection whenever the Urjanet App automatically creates Stationary Asset Environmental Sources from this Supplier.</inlineHelpText>
    <label>Other Emissions Factors</label>
    <referenceTo>OtherEmssnFctrSet</referenceTo>
    <relationshipLabel>Supplier</relationshipLabel>
    <relationshipName>Supplier</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Utility_File_Account_Association__c/Utility_File_Account_Association__c.object-meta.xml
<CustomObject>
    <description>Association between Utility Accounts and Utility Statements</description>
    <label>Utility File Account Association</label>
    <nameField>
        <displayFormat>FA-{00000}</displayFormat>
        <label>Utility File Account Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utility File Account Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Utility_File_Account_Association__c/fields/Utility_Account__c.field-meta.xml
<CustomField>
    <fullName>Utility_Account__c</fullName>
    <description>Utility Account</description>
    <label>Utility Account</label>
    <referenceTo>UtilityAccount__c</referenceTo>
    <relationshipLabel>Utility File Account Associations</relationshipLabel>
    <relationshipName>Utility_File_Account_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Utility_File_Account_Association__c/fields/Utility_Statement_File__c.field-meta.xml
<CustomField>
    <fullName>Utility_Statement_File__c</fullName>
    <description>Utilty Statement File</description>
    <label>Utility Statement File</label>
    <referenceTo>UtilityStatementFile__c</referenceTo>
    <relationshipLabel>Utility File Account Associations</relationshipLabel>
    <relationshipName>Utility_File_Account_Associations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/UtilityAccount__c.object-meta.xml
<CustomObject>
    <description>A custom object (created by the Urjanet Connect app) to store utility account information</description>
    <label>Utility Account</label>
    <nameField>
        <label>Utility Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityAccount__c/fields/LastModifiedInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedInUrjanet__c</fullName>
    <description>The date that an account was modified last in the Arcadia system.</description>
    <inlineHelpText>The date that an account was modified last in the Arcadia system.</inlineHelpText>
    <label>Last Modified in Arcadia</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/fields/StatusDetail__c.field-meta.xml
<CustomField>
    <fullName>StatusDetail__c</fullName>
    <description>A detailed status for the account.</description>
    <inlineHelpText>A detailed status for the account.</inlineHelpText>
    <label>Status Detail</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Supplier</referenceTo>
    <relationshipLabel>Utility Accounts</relationshipLabel>
    <relationshipName>UtilityAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/fields/UtilityCredential__c.field-meta.xml
<CustomField>
    <fullName>UtilityCredential__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Utility Credential</label>
    <referenceTo>UtilityCredential__c</referenceTo>
    <relationshipLabel>Utility Accounts</relationshipLabel>
    <relationshipName>UtilityAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/UtilityCredential__c.object-meta.xml
<CustomObject>
    <description
    >A custom object (created by the Urjanet Connect app) to store status information about utility credentials</description>
    <label>Utility Credential</label>
    <nameField>
        <label>Utility Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityCredential__c/fields/LastModifiedInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedInUrjanet__c</fullName>
    <description>The date that a credential was modified last.</description>
    <inlineHelpText>The date that a credential was modified last.</inlineHelpText>
    <label>Last Modified in Arcadia</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/ProviderName__c.field-meta.xml
<CustomField>
    <fullName>ProviderName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The commonly known name for the utility company.</description>
    <inlineHelpText>The commonly known name for the utility company.</inlineHelpText>
    <label>Provider Name</label>
    <referenceTo>Supplier</referenceTo>
    <relationshipLabel>Utility Credentials</relationshipLabel>
    <relationshipName>UtilityCredentials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/StatusDetail__c.field-meta.xml
<CustomField>
    <fullName>StatusDetail__c</fullName>
    <description>A detailed status for the credential.</description>
    <inlineHelpText>A detailed status for the credential.</inlineHelpText>
    <label>Status Detail</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>PENDING</fullName>
                <label>Pending</label>
            </value>
            <value>
                <fullName>ACTION_REQUIRED</fullName>
                <label>Action Required</label>
            </value>
            <value>
                <fullName>ACCOUNT_LOCKED</fullName>
                <label>Account Locked</label>
            </value>
            <value>
                <fullName>E_BILL_REQUIRED</fullName>
                <label>E-Bill Required</label>
            </value>
            <value>
                <fullName>LOGIN_FAILURE</fullName>
                <label>Login Failure</label>
            </value>
            <value>
                <fullName>MULTIFACTOR_AUTH_FAILURE</fullName>
                <label>Multi-Factor Authentication Failure</label>
            </value>
            <value>
                <fullName>NAVIGATION_FAILURE</fullName>
                <label>Navigation Failure</label>
            </value>
            <value>
                <fullName>NO_ACCOUNTS_FOUND</fullName>
                <label>No Accounts Found</label>
            </value>
            <value>
                <fullName>NO_ACTION_REQUIRED</fullName>
                <label>No Action Required</label>
            </value>
            <value>
                <fullName>SECURITY_QUESTIONS</fullName>
                <label>Security Questions</label>
            </value>
            <value>
                <fullName>STATEMENT_UNAVAILABLE</fullName>
                <label>Statement Unavailable</label>
            </value>
            <value>
                <fullName>UNDER_REVIEW</fullName>
                <label>Under Review</label>
            </value>
            <value>
                <fullName>UNSUPPORTED_CAPTCHA</fullName>
                <label>Unsupported CAPTCHA</label>
            </value>
            <value>
                <fullName>USER_ACTION_REQUIRED</fullName>
                <label>User Action Required</label>
            </value>
            <value>
                <fullName>WEBSITE_DOWN</fullName>
                <label>Website Down</label>
            </value>
            <value>
                <fullName>ACCOUNT_SETUP_REQUIRED</fullName>
                <label>Account Setup Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/UrjanetId__c.field-meta.xml
<CustomField>
    <fullName>UrjanetId__c</fullName>
    <description>Unique ID for the account on Arcadia system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique ID for the account on Arcadia system.</inlineHelpText>
    <label>ArcadiaId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/UtilityStatementFile__c/UtilityStatementFile__c.object-meta.xml
<CustomObject>
    <label>Utility Statement File</label>
    <nameField>
        <label>Utility Statement File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Statement Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityStatementFile__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Supplier</referenceTo>
    <relationshipLabel>Utility Statement Files</relationshipLabel>
    <relationshipName>UtilityStatementFiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/testClasses/UtilityAccountServiceTest.cls
@IsTest
private class UtilityAccountServiceTest {
    @TestSetup
    static void setup() {
        User adminUser = TestUtility.createUserAdmin('urjanetAdmin@urjanettest.com');
        System.runAs(adminUser) {
            List<SObject> lstElectricityEmissionFactorSet = Test.loadData(
                ElectricityEmssnFctrSet.sObjectType,
                'ElectricityEmissionFactorSet'
            );
            List<SObject> lstOtherEmissionFactorSet = Test.loadData(
                OtherEmssnFctrSet.sObjectType,
                'OtherEmissionFactorSet'
            );

            Account providerAccount = new Account();
            providerAccount.Name = 'Test Provider Account';
            insert providerAccount;

            Supplier provider = new Supplier();
            provider.Name = 'Test Provider';
            provider.OtherEmissionsFactors__c = lstOtherEmissionFactorSet[0].Id;
            provider.ElectricityEmissionsFactors__c = lstElectricityEmissionFactorSet[0].Id;
            provider.AccountId = providerAccount.Id;
            insert provider;

            UtilityCredential__c credential = new UtilityCredential__c();
            credential.UrjanetId__c = TestUtility.CREDENTIAL_ID;
            credential.ProviderName__c = provider.id;
            insert credential;

            UtilityStatementFile__c statementFile = new UtilityStatementFile__c();
            statementFile.Name = 'My Utility Statement';
            statementFile.Supplier__c = provider.Id;
            insert statementFile;
        }
    }

    @IsTest
    static void newUtilityCredentialsIsConsideredForUpdate() {
        String randomId = TestUtility.getRandomId(UtilityAccount__c.SObjectType);
        UtilityAccount__c updatedAccount = new UtilityAccount__c();
        updatedAccount.LastModifiedInUrjanet__c = Datetime.now();
        updatedAccount.Id = Id.valueOf(randomId);

        UtilityAccount__c oldAccount = new UtilityAccount__c();
        oldAccount.LastModifiedInUrjanet__c = Datetime.now().addMinutes(-1);
        oldAccount.Id = Id.valueOf(randomId);

        Map<Id, UtilityAccount__c> oldMap = new Map<Id, UtilityAccount__c>();
        oldMap.put(Id.valueOf(randomId), oldAccount);

        Test.startTest();
        List<UtilityAccount__c> AccountsToRefresh = UtilityAccountService.getAccountsToRefresh(
            new List<UtilityAccount__c>{ updatedAccount, oldAccount },
            oldMap
        );
        Test.stopTest();
        CSUtils.itShouldBe('Accounts to refresh should have 1 record', 1, AccountsToRefresh.size());
    }

    @IsTest
    static void givenNoExistingAcctRecordsWhenCreateAcctRecordsAllCreated() {
        UtilityCredential__c credential = [SELECT Id, UrjanetId__c, ProviderName__c FROM UtilityCredential__c LIMIT 1];

        GetAccountsByCredsResponse mockResponse = getMockDetailsResponse();

        System.runAs(TestUtility.createUserAdmin('123123123131231@test.com')) {
            Test.startTest();
            UtilityAccountService.createAccountFromDataResponse(mockResponse, credential);
            Test.stopTest();
            Integer utilityAccountCount = [SELECT COUNT() FROM UtilityAccount__c];
            System.assertEquals(true, utilityAccountCount > 0, 'Should be utilityaccount records created');
        }
    }

    @IsTest
    static void givenExistingAcctRecordsWhenUpdateAcctRecordsAllUpdated() {
        UtilityCredential__c credential = [SELECT Id, UrjanetId__c, ProviderName__c FROM UtilityCredential__c LIMIT 1];

        GetAccountsByCredsResponse mockResponse = getMockDetailsResponse();
        mockResponse.embedded.accounts[0].statusDetail = 'Test Status Detail';

        System.runAs(TestUtility.createUserAdmin('123123123131231@test.com')) {
            Test.startTest();
            UtilityAccountService.createAccountFromDataResponse(mockResponse, credential);
            Test.stopTest();
            List<UtilityAccount__c> utilityAccountList = [SELECT Id, StatusDetail__c FROM UtilityAccount__c LIMIT 1];
            System.assertEquals(
                'Test Status Detail',
                utilityAccountList[0].StatusDetail__c,
                'Should be utilityaccount records updated'
            );
        }
    }

    private static GetAccountsByCredsResponse getMockDetailsResponse() {
        StaticResourceCalloutMock mock = TestUtility.getStaticResourceCalloutMock('AccountsByCredsResponse', 200);

        HttpResponse mockHttpResponse = mock.respond(new HttpRequest());
        GetAccountsByCredsResponse mockResponse = (GetAccountsByCredsResponse) new GetAccountsByCredsResponseParser()
            .parseResponse(mockHttpResponse);
        return mockResponse;
    }

    @IsTest
    static void testCreateAccountFromDataResponseStatement() {
        UtilityStatementFile__c stateFile = [SELECT Id, Name, Supplier__c FROM UtilityStatementFile__c LIMIT 1];
        GetAccountsByCredsResponse mockResponse = getMockDetailsResponse();
        Test.StartTest();
        UtilityAccountService.createAccountFromDataResponse(mockResponse, stateFile);
        Test.StopTest();

        List<UtilityAccount__c> utilityAccountList = [SELECT Id, StatusDetail__c FROM UtilityAccount__c LIMIT 1];
        CSUtils.itShouldBe(
            'Status Detail should be matched ',
            'NO_ACTION_REQUIRED',
            utilityAccountList[0].StatusDetail__c
        );
    }

    @IsTest
    static void testCreateAccountFromDataResponseStatementDuplicate() {
        UtilityStatementFile__c stateFile = [SELECT Id, Name, Supplier__c FROM UtilityStatementFile__c LIMIT 1];
        GetAccountsByCredsResponse mockResponse = getMockDetailsResponse();
        Test.StartTest();
        UtilityAccountService.createAccountFromDataResponse(mockResponse, stateFile);
        // call 2 times to check duplicate
        UtilityAccountService.createAccountFromDataResponse(mockResponse, stateFile);
        Test.StopTest();

        List<UtilityAccount__c> utilityAccountList = [SELECT Id, StatusDetail__c FROM UtilityAccount__c];
        CSUtils.itShouldBe('utilityAccountList size ', 1, utilityAccountList.size());
        CSUtils.itShouldBe(
            'Status Detail should be matched ',
            'NO_ACTION_REQUIRED',
            utilityAccountList[0].StatusDetail__c
        );
        List<Utility_File_Account_Association__c> fileAccounts = [
            SELECT Id, Utility_Statement_File__c, Utility_Account__c
            FROM Utility_File_Account_Association__c
        ];
        CSUtils.itShouldBe('fileAccounts size ', 1, fileAccounts.size());
        CSUtils.itShouldBe('Utility Account Id', utilityAccountList[0].Id, fileAccounts[0].Utility_Account__c);
        CSUtils.itShouldBe('Utility Statement Id', stateFile.Id, fileAccounts[0].Utility_Statement_File__c);
    }
}