force-app/main/default/objects/Supplier/fields/ElectricityEmissionsFactors__c.field-meta.xml
<CustomField>
    <fullName>ElectricityEmissionsFactors__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
    >A custom field so that the Urjanet app can create Stationary Asset Environmental Sources (since the emissions factor fields are required).</description>
    <inlineHelpText
    >The selection placed in this field will be used as the "Electricity Emissions Factors" field selection whenever the Urjanet App automatically creates Stationary Asset Environmental Sources from this Supplier.</inlineHelpText>
    <label>Electricity Emissions Factors</label>
    <referenceTo>ElectricityEmssnFctrSet</referenceTo>
    <relationshipLabel>Supplier</relationshipLabel>
    <relationshipName>Supplier</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier/fields/OtherEmissionsFactors__c.field-meta.xml
<CustomField>
    <fullName>OtherEmissionsFactors__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
    >A custom field so that the Urjanet app can create Stationary Asset Environmental Sources (since the emissions factor fields are required).</description>
    <inlineHelpText
    >The selection placed in this field will be used as the "Other Emissions Factors" field selection whenever the Urjanet App automatically creates Stationary Asset Environmental Sources from this Supplier.</inlineHelpText>
    <label>Other Emissions Factors</label>
    <referenceTo>OtherEmssnFctrSet</referenceTo>
    <relationshipLabel>Supplier</relationshipLabel>
    <relationshipName>Supplier</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/UtilityAccount__c.object-meta.xml
<CustomObject>
    <description>A custom object (created by the Urjanet Connect app) to store utility account information</description>
    <label>Utility Account</label>
    <nameField>
        <label>Utility Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityAccount__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Supplier</referenceTo>
    <relationshipLabel>Utility Accounts</relationshipLabel>
    <relationshipName>UtilityAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/fields/UtilityCredential__c.field-meta.xml
<CustomField>
    <fullName>UtilityCredential__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Utility Credential</label>
    <referenceTo>UtilityCredential__c</referenceTo>
    <relationshipLabel>Utility Accounts</relationshipLabel>
    <relationshipName>UtilityAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/UtilityCredential__c.object-meta.xml
<CustomObject>
    <description
    >A custom object (created by the Urjanet Connect app) to store status information about utility credentials</description>
    <label>Utility Credential</label>
    <nameField>
        <label>Utility Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityCredential__c/fields/ProviderName__c.field-meta.xml
<CustomField>
    <fullName>ProviderName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The commonly known name for the utility company.</description>
    <inlineHelpText>The commonly known name for the utility company.</inlineHelpText>
    <label>Provider Name</label>
    <referenceTo>Supplier</referenceTo>
    <relationshipLabel>Utility Credentials</relationshipLabel>
    <relationshipName>UtilityCredentials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/UrjanetId__c.field-meta.xml
<CustomField>
    <fullName>UrjanetId__c</fullName>
    <description>Unique ID for the account on Arcadia system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique ID for the account on Arcadia system.</inlineHelpText>
    <label>ArcadiaId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/UtilityAccountSelector.cls
public with sharing class UtilityAccountSelector extends Selector {
    public UtilityAccountSelector() {
        super(Schema.UtilityAccount__c.SObjectType);
    }

    public UtilityAccountSelector(Boolean enforceCRUD, Boolean enforceFLS, Boolean enforceShr) {
        super(Schema.UtilityAccount__c.SObjectType, enforceCRUD, enforceFLS, EnforceShr);
    }

    public override Set<String> getDefaultFields() {
        return new Set<String>{
            'Id',
            'Name',
            'UrjanetId__c',
            'UtilityCredential__c',
            'UtilityCredential__r.ProviderName__c',
            'UtilityCredential__r.ProviderName__r.Name',
            'UtilityCredential__r.ProviderName__r.ElectricityEmissionsFactors__c',
            'UtilityCredential__r.ProviderName__r.OtherEmissionsFactors__c',
            'Supplier__c',
            'Supplier__r.Name',
            'Supplier__r.ElectricityEmissionsFactors__c',
            'Supplier__r.OtherEmissionsFactors__c'
        };
    }

    /**
     * Gets UtilityAccount__c records that need the details synced from Arcadia that are not linked to Credentials
     * @return Database.QueryLocator
     */
    public Database.QueryLocator getUtilAccountsSyncBatchWithoutCredential() {
        Map<String, Object> params = new Map<String, Object>();

        //we need to get the utility account records that are not linked to Utility Credentials
        String query = getDefaultQuery();
        query += ' WHERE UrjanetId__c != null and UtilityCredential__c=null';
        return Data.Locator(query, params, this.isEnforcingCRUD(), this.isEnforcingFLS(), this.isEnforcingShr());
    }
}