force-app/main/CS-QueueScience/objects/QueueItem__c/QueueItem__c.object-meta.xml
<CustomObject>
    <label>Queue Item</label>
    <nameField>
        <displayFormat>QI-{000000000}</displayFormat>
        <label>Queue Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Queue Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QueueItem__c/fields/PageNumber__c.field-meta.xml
<CustomField>
    <fullName>PageNumber__c</fullName>
    <description>This field is used with API pagination to indicate the next page number to retrieve</description>
    <label>Page Number</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/CS-QueueScience/objects/QueueItem__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <description>Contains the SFDC Id of the record to be processed.</description>
    <externalId>true</externalId>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QueueItem__c/fields/RequestType__c.field-meta.xml
<CustomField>
    <fullName>RequestType__c</fullName>
    <description>This field is used with API pagination to store the type of API we need to execute when the Queue Item record is processed.</description>
    <label>Request Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/UtilityAccount__c.object-meta.xml
<CustomObject>
    <description>A custom object (created by the Urjanet Connect app) to store utility account information</description>
    <label>Utility Account</label>
    <nameField>
        <label>Utility Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityAccount__c/fields/UtilityCredential__c.field-meta.xml
<CustomField>
    <fullName>UtilityCredential__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Utility Credential</label>
    <referenceTo>UtilityCredential__c</referenceTo>
    <relationshipLabel>Utility Accounts</relationshipLabel>
    <relationshipName>UtilityAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/UtilityCredential__c.object-meta.xml
<CustomObject>
    <description
    >A custom object (created by the Urjanet Connect app) to store status information about utility credentials</description>
    <label>Utility Credential</label>
    <nameField>
        <label>Utility Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityCredential__c/fields/UrjanetId__c.field-meta.xml
<CustomField>
    <fullName>UrjanetId__c</fullName>
    <description>Unique ID for the account on Arcadia system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique ID for the account on Arcadia system.</inlineHelpText>
    <label>ArcadiaId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/UtilityCredentialProcessor.cls
public with sharing class UtilityCredentialProcessor extends QueueItemWorkerBase {
    public override QueueItem__c process(QueueItem__c queueItem) {
        // Ignoring security here since this is a system process
        UtilityCredential__c credentialToProcess = (UtilityCredential__c) new UtilityCredentialSelector(
                false,
                false,
                false
            )
            .getRecordById(queueItem.RecordId__c);
        if (credentialToProcess.UrjanetId__c == null) {
            Logger.getInstance()
                .log(
                    UtilityCredentialProcessor.class.getName(),
                    Logger.Level.WARN,
                    'Unable to Process Credential as ArcadiaId is null : ' + queueItem.RecordId__c
                );
            return queueItem;
        }

        // Get Account data from urjanet
        String pageSize = UrjanetUtils.getAPIPageSize();
        String pageNumber = (queueItem.PageNumber__c == null
            ? '0'
            : String.valueOf(Integer.valueOf(queueItem.PageNumber__c)));

        List<String> requestParams = new List<String>{ credentialToProcess.UrjanetId__c, pageSize, pageNumber };

        if (
            queueItem.RequestType__c == null ||
            queueItem.RequestType__c == UrjanetEnums.RequestType.ACCOUNTS_BY_CREDS.name()
        ) {
            GetAccountsByCredsResponse response = (GetAccountsByCredsResponse) new UrjanetApiClient()
                .getUrjanetResponse(
                    UrjanetEnums.RequestType.ACCOUNTS_BY_CREDS,
                    UrjanetEnums.ApiMethod.GET,
                    requestParams
                );
            if (response.errorMsg != null) {
                UrjanetUtils.handleApiError(
                    queueItem,
                    response.errorMsg,
                    response.message,
                    response.status,
                    UtilityCredentialProcessor.class.getName()
                );
            } else {
                // write UtilityAccount__c records
                UtilityAccountService.createAccountFromDataResponse(response, credentialToProcess);
                //check if needed for pagination to create queue items for the other pages
                UrjanetUtils.createPaginationQueueItemFromAPIResponse(
                    response.page,
                    credentialToProcess.Id,
                    UrjanetEnums.RequestType.ACCOUNTS_BY_CREDS.name(),
                    QueueItemProcessorFactory.getProcessorType(UtilityCredential__c.SObjectType)
                );
            }
        }

        return queueItem;
    }
}