force-app/main/CS-QueueScience/objects/QueueItem__c/QueueItem__c.object-meta.xml
<CustomObject>
    <label>Queue Item</label>
    <nameField>
        <displayFormat>QI-{000000000}</displayFormat>
        <label>Queue Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Queue Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/CS-QueueScience/objects/QueueItem__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <description>Contains the SFDC Id of the record to be processed.</description>
    <externalId>true</externalId>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/UtilityAccount__c.object-meta.xml
<CustomObject>
    <description>A custom object (created by the Urjanet Connect app) to store utility account information</description>
    <label>Utility Account</label>
    <nameField>
        <label>Utility Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityStatementFile__c/UtilityStatementFile__c.object-meta.xml
<CustomObject>
    <label>Utility Statement File</label>
    <nameField>
        <label>Utility Statement File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Statement Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityStatementFile__c/fields/StatementId__c.field-meta.xml
<CustomField>
    <fullName>StatementId__c</fullName>
    <label>Statement Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UtilityStatementFileProcessor.cls
public with sharing class UtilityStatementFileProcessor extends QueueItemWorkerBase {
    public override QueueItem__c process(QueueItem__c queueItem) {
        // Ignoring security here since this is a system process
        UtilityStatementFile__c utilityStatementFileToProcess = (UtilityStatementFile__c) new UtilityStatementFileSelector(
                false,
                false,
                false
            )
            .getRecordById(queueItem.RecordId__c);
        if (utilityStatementFileToProcess.StatementId__c == null) {
            Logger.getInstance()
                .log(
                    UtilityStatementFileProcessor.class.getName(),
                    Logger.Level.WARN,
                    'Unable to Process Utility Statement File as StatementId is null : ' + queueItem.RecordId__c
                );
            return queueItem;
        }

        // Get Account data from urjanet for the file statement
        List<String> requestParams = new List<String>{ utilityStatementFileToProcess.StatementId__c };
        GetAccountsByCredsResponse response = (GetAccountsByCredsResponse) new UrjanetApiClient()
            .getUrjanetResponse(
                UrjanetEnums.RequestType.ACCOUNTS_BY_STATEMENTIDS,
                UrjanetEnums.ApiMethod.GET,
                requestParams
            );
        if (response.errorMsg != null) {
            UrjanetUtils.handleApiError(
                queueItem,
                response.errorMsg,
                response.message,
                response.status,
                UtilityStatementFileProcessor.class.getName()
            );
        } else {
            // write UtilityAccount__c records
            UtilityAccountService.createAccountFromDataResponse(response, utilityStatementFileToProcess);
        }

        return queueItem;
    }
}