force-app/main/CS-QueueScience/objects/QueueItem__c/QueueItem__c.object-meta.xml
<CustomObject>
    <label>Queue Item</label>
    <nameField>
        <displayFormat>QI-{000000000}</displayFormat>
        <label>Queue Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Queue Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/CS-QueueScience/objects/QueueItem__c/fields/ErrorCount__c.field-meta.xml
<CustomField>
    <fullName>ErrorCount__c</fullName>
    <externalId>true</externalId>
    <label>Error Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/CS-QueueScience/objects/QueueItem__c/fields/ErrorMessageShort__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessageShort__c</fullName>
    <externalId>true</externalId>
    <label>Error Message (Short)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/CS-QueueScience/objects/QueueItem__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QueueItem__c/fields/PageNumber__c.field-meta.xml
<CustomField>
    <fullName>PageNumber__c</fullName>
    <description>This field is used with API pagination to indicate the next page number to retrieve</description>
    <label>Page Number</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/CS-QueueScience/objects/QueueItem__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Marked as External Id to create an index.</description>
    <externalId>true</externalId>
    <label>Priority</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/CS-QueueScience/objects/QueueItem__c/fields/Process_After__c.field-meta.xml
<CustomField>
    <fullName>Process_After__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>Do not process the Queue Item until after this data. Default now</description>
    <inlineHelpText>Do not process the Queue Item until after this data. Default now</inlineHelpText>
    <label>Process After</label>
    <type>DateTime</type>
</CustomField>

force-app/main/CS-QueueScience/objects/QueueItem__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <description>Contains the SFDC Id of the record to be processed.</description>
    <externalId>true</externalId>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QueueItem__c/fields/RequestType__c.field-meta.xml
<CustomField>
    <fullName>RequestType__c</fullName>
    <description>This field is used with API pagination to store the type of API we need to execute when the Queue Item record is processed.</description>
    <label>Request Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QueueItem__c/fields/StaleDataIdsList__c.field-meta.xml
<CustomField>
    <fullName>StaleDataIdsList__c</fullName>
    <label>Stale Data List</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/CS-QueueScience/objects/QueueItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;NEW&quot;</defaultValue>
    <description>Marked as External Id to create an index.</description>
    <externalId>true</externalId>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QueueItem__c/fields/TotalPagesNumber__c.field-meta.xml
<CustomField>
    <fullName>TotalPagesNumber__c</fullName>
    <description>This field is used with API pagination to indicate the total no of pages avialble</description>
    <label>Page Number</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/CS-QueueScience/classes/QueueItemSelector.cls
public with sharing class QueueItemSelector extends Selector {
    /**
     * Constructor that assumes we are enforcing CRUD/FLS/Sharing
     */
    public QueueItemSelector() {
        super(Schema.QueueItem__c.SObjectType);
    }

    /**
     * Constructor that allows us to specify the CRUD/FLS/Sharing for this instance
     * @param  enforceCRUD Enforce CRUD
     * @param  enforceFLS  Enforce FLS
     * @param  enforceShr  Enforce Sharing
     */
    public QueueItemSelector(Boolean enforceCRUD, Boolean enforceFLS, Boolean enforceShr) {
        super(Schema.QueueItem__c.SObjectType, enforceCRUD, enforceFLS, EnforceShr);
    }

    /**
     * Returns a set of strings that has all default values.
     * @return   return Set of default SELECT values
     */
    public override Set<String> getDefaultFields() {
        return new Set<String>{
            'Id',
            'ClassName__c', // contains class name
            'Context__c',
            'ErrorCount__c', // count of errors
            'ErrorMessageShort__c',
            'Object__c', // sObject name to process
            'Priority__c', // default 0, higher process first
            'Process_After__c', // defaults to immediate
            'RecordId__c', // record it to process
            'Status__c', // NEW is processed
            'PageNumber__c', //the page number to get in case of pagination
            'TotalPagesNumber__c', //the total number of pages to get in case of pagination
            'StaleDataIdsList__c', // the list of ids to use to get the stale data
            'RequestType__c' //the request type to run in case of pagination and queue item processor calls multiple APIs
        };
    }

    /**
     * Retrieve a list of ContentVersion records filtered on ContentDocumentId
     * @param  contentDocuments A list of ContentDocumentId's
     * @return                  A list of ContentVersion records
     */
    public List<QueueItem__c> getNextQueueItem(Integer rowLimit, DateTime processingTimeBoundary) {
        List<String> queryFields = new List<String>(this.getDefaultFields());

        Map<String, Object> queryArgs = new Map<String, Object>{
            'rowLimit' => rowLimit,
            'processingTimeBoundary' => processingTimeBoundary,
            'processingStatus' => 'NEW'
        };

        String query =
            'SELECT ' +
            String.join(queryFields, ', ') +
            ' FROM QueueItem__c' +
            ' WHERE Process_After__c <= :processingTimeBoundary' +
            ' AND Status__c = :processingStatus' +
            ' ORDER BY Priority__c DESC, Process_After__c ASC, Id' +
            ' LIMIT :rowLimit';

        return new List<QueueItem__c>(
            (List<QueueItem__c>) Data.read(
                query,
                queryArgs,
                this.isEnforcingCRUD(),
                this.isEnforcingFLS(),
                this.isEnforcingShr()
            )
        );
    }
}