force-app/main/CS-QueueScience/objects/QueueItem__c/QueueItem__c.object-meta.xml
<CustomObject>
    <label>Queue Item</label>
    <nameField>
        <displayFormat>QI-{000000000}</displayFormat>
        <label>Queue Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Queue Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/CS-QueueScience/objects/QueueItem__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <description>Contains the SFDC Id of the record to be processed.</description>
    <externalId>true</externalId>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityMeter__c/UtilityMeter__c.object-meta.xml
<CustomObject>
    <description>A custom object (created by the Urjanet Connect app) to store utility meter information</description>
    <label>Utility Meter</label>
    <nameField>
        <label>Utility Meter Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Meters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityMeter__c/fields/ServiceType__c.field-meta.xml
<CustomField>
    <fullName>ServiceType__c</fullName>
    <description>The meter’s service type.</description>
    <inlineHelpText>The meter’s service type.</inlineHelpText>
    <label>Service Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityMeterUsage__c/UtilityMeterUsage__c.object-meta.xml
<CustomObject>
    <description>A custom object (created by the Urjanet Connect app) to store utility meter usage data.</description>
    <label>Utility Meter Usage</label>
    <nameField>
        <label>Utility Meter Usage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Meter Usages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityMeterUsage__c/fields/UtilityMeter__c.field-meta.xml
<CustomField>
    <fullName>UtilityMeter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Utility Meter for this Utility Meter Usage record.</description>
    <inlineHelpText>The Utility Meter for this Utility Meter Usage record.</inlineHelpText>
    <label>Utility Meter</label>
    <referenceTo>UtilityMeter__c</referenceTo>
    <relationshipLabel>Utility Meter Usages</relationshipLabel>
    <relationshipName>UtilityMeterUsages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UtilityMeterUsageUpdateProcessor.cls
public with sharing class UtilityMeterUsageUpdateProcessor extends QueueItemWorkerBase {
    public override QueueItem__c process(QueueItem__c queueItem) {
        // Ignoring security here since this is a system process
        UtilityMeterUsage__c meterUsageToProcess = (UtilityMeterUsage__c) new UtilityMeterUsageSelector(
                false,
                false,
                false
            )
            .getRecordById(queueItem.RecordId__c);

        if (meterUsageToProcess == null) {
            Logger.getInstance()
                .log(
                    UtilityMeterUsageUpdateProcessor.class.getName(),
                    Logger.Level.WARN,
                    'Unable to Process Meter Usage as the record is null : ' + queueItem.RecordId__c
                );
            return queueItem;
        }

        if (meterUsageToProcess.UtilityMeter__c == null) {
            Logger.getInstance()
                .log(
                    UtilityMeterUsageUpdateProcessor.class.getName(),
                    Logger.Level.WARN,
                    'Unable to Process Meter Usage as Utility Meter is null : ' + queueItem.RecordId__c
                );
            return queueItem;
        }

        String ns = UtilityMeterUsageUpdateProcessor.class
            .getName()
            .substringBefore('UtilityMeterUsageUpdateProcessor')
            .removeEnd('.');

        String serviceType = meterUsageToProcess.UtilityMeter__r.ServiceType__c;

        deleteExistingStationaryAssets(ns, serviceType, meterUsageToProcess);

        createNewStationaryAssets(ns, serviceType, meterUsageToProcess);

        return queueItem;
    }

    private static void deleteExistingStationaryAssets(String ns, String serviceType, UtilityMeterUsage__c meterUsage) {
        Map<String, String> deleterMapping = UrjanetUtils.getStationaryAssetDeleterMappings();

        if (deleterMapping.containsKey(serviceType)) {
            Type dynamicType;
            if (String.isBlank(ns)) {
                dynamicType = Type.forName(deleterMapping.get(serviceType));
            } else {
                dynamicType = Type.forName(ns, deleterMapping.get(serviceType));
            }

            if (dynamicType != null) {
                IStationaryAssetDeleter processor = (IStationaryAssetDeleter) dynamicType.newInstance();
                processor.deleteStationaryAsset(meterUsage);
            }
        }
    }

    private static void createNewStationaryAssets(String ns, String serviceType, UtilityMeterUsage__c meterUsage) {
        Map<String, String> createrMapping = UrjanetUtils.getServiceToProcessorTypeMappings();

        if (createrMapping.containsKey(serviceType)) {
            Type dynamicType;
            if (String.isBlank(ns)) {
                dynamicType = Type.forName(createrMapping.get(serviceType));
            } else {
                dynamicType = Type.forName(ns, createrMapping.get(serviceType));
            }

            if (dynamicType != null) {
                IUtilityMeterUsageProcessor processor = (IUtilityMeterUsageProcessor) dynamicType.newInstance();
                processor.processUtilityMeterUsage(meterUsage);
            }
        }
    }
}