force-app/main/CS-QueueScience/objects/QueueItem__c/QueueItem__c.object-meta.xml
<CustomObject>
    <label>Queue Item</label>
    <nameField>
        <displayFormat>QI-{000000000}</displayFormat>
        <label>Queue Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Queue Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/CS-QueueScience/objects/QueueItem__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <description>Contains the SFDC Id of the record to be processed.</description>
    <externalId>true</externalId>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityMeter__c/UtilityMeter__c.object-meta.xml
<CustomObject>
    <description>A custom object (created by the Urjanet Connect app) to store utility meter information</description>
    <label>Utility Meter</label>
    <nameField>
        <label>Utility Meter Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Meters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityMeter__c/fields/ServiceType__c.field-meta.xml
<CustomField>
    <fullName>ServiceType__c</fullName>
    <description>The meter’s service type.</description>
    <inlineHelpText>The meter’s service type.</inlineHelpText>
    <label>Service Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityMeter__c/fields/UrjanetId__c.field-meta.xml
<CustomField>
    <fullName>UrjanetId__c</fullName>
    <description>Unique ID for the meter on Arcadia system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique ID for the meter on Arcadia system.</inlineHelpText>
    <label>ArcadiaId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/UtilityMeterProcessor.cls
public with sharing class UtilityMeterProcessor extends QueueItemWorkerBase {
    public override QueueItem__c process(QueueItem__c queueItem) {
        // Ignoring security here since this is a system process
        UtilityMeter__c meterToProcess = (UtilityMeter__c) new UtilityMeterSelector(false, false, false)
            .getRecordById(queueItem.RecordId__c);

        if (meterToProcess == null) {
            Logger.getInstance()
                .log(
                    UtilityMeterProcessor.class.getName(),
                    Logger.Level.WARN,
                    'Unable to Process Meter as the record is null : ' + queueItem.RecordId__c
                );
            return queueItem;
        }

        if (meterToProcess.UrjanetId__c == null) {
            Logger.getInstance()
                .log(
                    UtilityMeterProcessor.class.getName(),
                    Logger.Level.WARN,
                    'Unable to Process Meter as ArcadiaId is null : ' + queueItem.RecordId__c
                );
            return queueItem;
        }
        Map<String, String> serviceTypeMappings = UrjanetUtils.getServiceToMeterProcessorTypeMappings();
        //call the right processor (interface implementation) based on the custom metadata value
        if (serviceTypeMappings.containsKey(meterToProcess.ServiceType__c)) {
            String ns = UtilityMeterProcessor.class.getName().substringBefore('UtilityMeterProcessor').removeEnd('.');

            // Create an instance of the class dynamically
            Type dynamicType;
            if (String.isBlank(ns)) {
                dynamicType = Type.forName(serviceTypeMappings.get(meterToProcess.ServiceType__c));
            } else {
                dynamicType = Type.forName(ns, serviceTypeMappings.get(meterToProcess.ServiceType__c));
            }
            IUtilityMeterProcessor processor = (IUtilityMeterProcessor) dynamicType.newInstance();

            // Call the interface method
            processor.processUtilityMeterQueue(queueItem);
        }

        return queueItem;
    }
}