force-app/main/CS-QueueScience/objects/QueueItem__c/QueueItem__c.object-meta.xml
<CustomObject>
    <label>Queue Item</label>
    <nameField>
        <displayFormat>QI-{000000000}</displayFormat>
        <label>Queue Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Queue Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/CS-QueueScience/objects/QueueItem__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <description>Contains the SFDC Id of the record to be processed.</description>
    <externalId>true</externalId>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StnryAssetEnvrSrc/fields/UrjanetId__c.field-meta.xml
<CustomField>
    <fullName>UrjanetId__c</fullName>
    <description
    >A custom field to store the Arcadia ID to make recredentialing and other API calls easier.</description>
    <externalId>true</externalId>
    <inlineHelpText
    >A custom field to store the Arcadia ID to make recredentialing and other API calls easier.</inlineHelpText>
    <label>ArcadiaId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/StnryAssetEnvrSrc/fields/UrjanetSiteCode__c.field-meta.xml
<CustomField>
    <fullName>UrjanetSiteCode__c</fullName>
    <description
    >A custom field to store the Site Code field from Arcadia. This is an optional custom field in the Arcadia system.</description>
    <inlineHelpText>The site code as entered in the optional custom field in the Arcadia system.</inlineHelpText>
    <label>Arcadia Site Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StnryAssetEnvrSrc/fields/UrjanetSiteNumber__c.field-meta.xml
<CustomField>
    <fullName>UrjanetSiteNumber__c</fullName>
    <description
    >A custom field to store the Site Number field from Arcadia. This is an optional custom field in the Arcadia system.</description>
    <inlineHelpText>The site number as entered in the optional custom field in the Arcadia system.</inlineHelpText>
    <label>Arcadia Site Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StnryAssetEnvrSrc/fields/UrjanetSubRegion__c.field-meta.xml
<CustomField>
    <fullName>UrjanetSubRegion__c</fullName>
    <description>An optional custom field in the Arcadia system to input site’s sub region.</description>
    <inlineHelpText>An optional custom field in the Arcadia system to input site’s sub region.</inlineHelpText>
    <label>Arcadia subRegion</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SiteCreateProcessor.cls
public with sharing class SiteCreateProcessor extends QueueItemWorkerBase {
    //this method is to update the site in meters on Urjanet application
    public override QueueItem__c process(QueueItem__c queueItem) {
        // Ignoring security here since this is a system process
        StnryAssetEnvrSrc siteToProcess = (StnryAssetEnvrSrc) new StationaryAssetSourceSelector(false, false, false)
            .getRecordById(queueItem.RecordId__c);
        if (siteToProcess.UrjanetId__c == null) {
            List<String> requestParams = new List<String>{
                siteToProcess.City,
                StationaryAssetSourceService.mapToUrjanetCountryCode(siteToProcess.Country),
                siteToProcess.StationaryAssetType,
                siteToProcess.PostalCode,
                siteToProcess.BusinessRegion,
                siteToProcess.UrjanetSiteCode__c,
                siteToProcess.Name,
                siteToProcess.UrjanetSiteNumber__c,
                siteToProcess.UrjanetSubRegion__c,
                siteToProcess.State,
                siteToProcess.StreetAddress,
                siteToProcess.StreetAddress2
            };
            PostSiteResponse response = (PostSiteResponse) new UrjanetApiClient()
                .getUrjanetResponse(UrjanetEnums.RequestType.CREATE_SITE, UrjanetEnums.ApiMethod.POST, requestParams);
            if (response.errorMsg == null) {
                StationaryAssetSourceService.updateSiteDetailsFromResponse(response, queueItem.RecordId__c);
            } else {
                UrjanetUtils.handleApiError(
                    queueItem,
                    response.errorMsg,
                    response.message,
                    response.status,
                    SiteCreateProcessor.class.getName()
                );
            }

            return queueItem;
        }

        return queueItem;
    }
}