force-app/main/CS-QueueScience/objects/QueueItem__c/QueueItem__c.object-meta.xml
<CustomObject>
    <label>Queue Item</label>
    <nameField>
        <displayFormat>QI-{000000000}</displayFormat>
        <label>Queue Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Queue Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/CS-QueueScience/objects/QueueItem__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QueueItem__c/fields/PageNumber__c.field-meta.xml
<CustomField>
    <fullName>PageNumber__c</fullName>
    <description>This field is used with API pagination to indicate the next page number to retrieve</description>
    <label>Page Number</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/CS-QueueScience/objects/QueueItem__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <description>Contains the SFDC Id of the record to be processed.</description>
    <externalId>true</externalId>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QueueItem__c/fields/RequestType__c.field-meta.xml
<CustomField>
    <fullName>RequestType__c</fullName>
    <description>This field is used with API pagination to store the type of API we need to execute when the Queue Item record is processed.</description>
    <label>Request Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QueueItem__c/fields/StaleDataIdsList__c.field-meta.xml
<CustomField>
    <fullName>StaleDataIdsList__c</fullName>
    <label>Stale Data List</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QueueItem__c/fields/TotalPagesNumber__c.field-meta.xml
<CustomField>
    <fullName>TotalPagesNumber__c</fullName>
    <description>This field is used with API pagination to indicate the total no of pages avialble</description>
    <label>Page Number</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/UtilityAccount__c.object-meta.xml
<CustomObject>
    <description>A custom object (created by the Urjanet Connect app) to store utility account information</description>
    <label>Utility Account</label>
    <nameField>
        <label>Utility Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/QueueItemsBuilder.cls
public with sharing class QueueItemsBuilder {
    private List<QueueItem__c> queueItems;
    private List<SObject> records;
    private Type processorClass;

    private Id recordId;
    private String requestType;
    private Integer numberOfPages;

    private Double pageNumber;
    private Set<String> staleDataToBeDeletedSet;

    public QueueItemsBuilder(List<SObject> records, Type processorClass) {
        this.records = records;
        this.processorClass = processorClass;
    }

    public QueueItemsBuilder(Id recordI, Type processorClass, String requestType, Integer numberOfPages) {
        this.recordId = recordI;
        this.processorClass = processorClass;
        this.requestType = requestType;
        this.numberOfPages = numberOfPages;
    }

    public QueueItemsBuilder(
        Id recordId,
        Type processorClass,
        String requestType,
        Integer numberOfPages,
        Double pageNumber,
        Set<String> staleDataToBeDeletedSet
    ) {
        this.recordId = recordId;
        this.processorClass = processorClass;
        this.requestType = requestType;
        this.numberOfPages = numberOfPages;
        this.pageNumber = pageNumber;
        this.staleDataToBeDeletedSet = staleDataToBeDeletedSet;
    }

    public QueueItemsBuilder buildQueueItemsPerRecord() {
        this.queueItems = new List<QueueItem__c>();
        for (SObject record : this.records) {
            QueueItem__c item = new QueueItem__c();
            item.ClassName__c = this.processorClass.getName();
            item.RecordId__c = record.Id;
            item.Object__c = String.valueOf(record.getSObjectType());
            this.queueItems.add(item);
        }
        return this;
    }

    public QueueItemsBuilder buildQueueItemsPerPage() {
        this.queueItems = new List<QueueItem__c>();
        for (Integer i = 1; i < this.numberOfPages; i++) {
            QueueItem__c item = new QueueItem__c();
            item.ClassName__c = this.processorClass.getName();
            item.RecordId__c = this.recordId;
            item.Object__c = String.valueOf(this.recordId.getSObjectType().getDescribe().getName());
            item.RequestType__c = this.requestType;
            item.PageNumber__c = i;
            this.queueItems.add(item);
        }
        return this;
    }

    public QueueItemsBuilder buildQueueItemsPerPageForMeterUsages() {
        this.queueItems = new List<QueueItem__c>();
        QueueItem__c item = new QueueItem__c();
        item.ClassName__c = this.processorClass.getName();
        item.RecordId__c = this.recordId;
        item.Object__c = String.valueOf(this.recordId.getSObjectType().getDescribe().getName());
        item.RequestType__c = this.requestType;
        item.PageNumber__c = this.pageNumber;
        item.TotalPagesNumber__c = this.numberOfPages;
        item.StaleDataIdsList__c = JSON.serialize(this.staleDataToBeDeletedSet);
        this.queueItems.add(item);
        return this;
    }

    public List<Database.SaveResult> createRecords() {
        if (!this.queueItems.isEmpty()) {
            // Ignoring CRUD/FLS here since this is a system process that needs to run for all users
            Database.DMLOptions option = new Database.DMLOptions();
            option.OptAllOrNone = false;
            List<Database.SaveResult> saveResult = Data.create(this.queueItems, option, false, false, false);
            Logger.getInstance(false)
                .log(
                    UtilityAccountService.class.getName(),
                    UrjanetUtils.getSObjectName(Schema.UtilityAccount__c.SObjectType),
                    saveResult
                );
            return saveResult;
        }
        return new List<Database.SaveResult>();
    }

    public List<QueueItem__c> getRecords() {
        return this.queueItems;
    }
}