force-app/main/CS-QueueScience/objects/QueueItem__c/QueueItem__c.object-meta.xml
<CustomObject>
    <label>Queue Item</label>
    <nameField>
        <displayFormat>QI-{000000000}</displayFormat>
        <label>Queue Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Queue Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QueueItem__c/fields/PageNumber__c.field-meta.xml
<CustomField>
    <fullName>PageNumber__c</fullName>
    <description>This field is used with API pagination to indicate the next page number to retrieve</description>
    <label>Page Number</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/CS-QueueScience/objects/QueueItem__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <description>Contains the SFDC Id of the record to be processed.</description>
    <externalId>true</externalId>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QueueItem__c/fields/RequestType__c.field-meta.xml
<CustomField>
    <fullName>RequestType__c</fullName>
    <description>This field is used with API pagination to store the type of API we need to execute when the Queue Item record is processed.</description>
    <label>Request Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityMeter__c/UtilityMeter__c.object-meta.xml
<CustomObject>
    <description>A custom object (created by the Urjanet Connect app) to store utility meter information</description>
    <label>Utility Meter</label>
    <nameField>
        <label>Utility Meter Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Meters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityMeterUsage__c/UtilityMeterUsage__c.object-meta.xml
<CustomObject>
    <description>A custom object (created by the Urjanet Connect app) to store utility meter usage data.</description>
    <label>Utility Meter Usage</label>
    <nameField>
        <label>Utility Meter Usage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Meter Usages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityMeterUsage__c/fields/PeriodEnd__c.field-meta.xml
<CustomField>
    <fullName>PeriodEnd__c</fullName>
    <description>Date that the billing period ended.</description>
    <inlineHelpText
    >Date that the billing period ended. (Editing this field will trigger the "Manually Updated" field for this asset)</inlineHelpText>
    <label>Period End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/UtilityMeterUsage__c/fields/PeriodStart__c.field-meta.xml
<CustomField>
    <fullName>PeriodStart__c</fullName>
    <description>Date that the billing period started.</description>
    <inlineHelpText
    >Date that the billing period started. (Editing this field will trigger the "Manually Updated" field for this asset)
    </inlineHelpText>
    <label>Period Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/UtilityMeterUsage__c/fields/UtilityMeter__c.field-meta.xml
<CustomField>
    <fullName>UtilityMeter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Utility Meter for this Utility Meter Usage record.</description>
    <inlineHelpText>The Utility Meter for this Utility Meter Usage record.</inlineHelpText>
    <label>Utility Meter</label>
    <referenceTo>UtilityMeter__c</referenceTo>
    <relationshipLabel>Utility Meter Usages</relationshipLabel>
    <relationshipName>UtilityMeterUsages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/testClasses/UrjanetUtilsTest.cls
/**
 * Created by mike on 5/10/22.
 */

@IsTest
private class UrjanetUtilsTest {
    @IsTest
    static void givenRecordsWithDifferentSyncFieldTrueReturned() {
        String randomId = TestUtility.getRandomId(UtilityMeter__c.SObjectType);
        UtilityMeter__c updatedMeter = new UtilityMeter__c();
        updatedMeter.LastUrjanetSyncDateTime__c = Datetime.now();
        updatedMeter.Id = Id.valueOf(randomId);

        UtilityMeter__c oldMeter = new UtilityMeter__c();
        oldMeter.LastUrjanetSyncDateTime__c = Datetime.now().addMinutes(-1);
        oldMeter.Id = Id.valueOf(randomId);

        Map<Id, UtilityMeter__c> oldMap = new Map<Id, UtilityMeter__c>();
        oldMap.put(Id.valueOf(randomId), oldMeter);

        Test.startTest();
        Boolean hasRecordChanged = UrjanetUtils.hasSyncFieldUpdated(
            updatedMeter,
            oldMap,
            UtilityMeter__c.LastUrjanetSyncDateTime__c
        );
        Test.stopTest();

        CSutils.itShouldBe('Record Change Boolean should be true', true, hasRecordChanged);
    }

    @IsTest
    static void givenRecordsWithSameSyncFieldFalseReturned() {
        String randomId = TestUtility.getRandomId(UtilityMeter__c.SObjectType);
        DateTime lastSyncDateTime = DateTime.now();
        UtilityMeter__c updatedMeter = new UtilityMeter__c();
        updatedMeter.LastUrjanetSyncDateTime__c = lastSyncDateTime;
        updatedMeter.Id = Id.valueOf(randomId);

        UtilityMeter__c oldMeter = new UtilityMeter__c();
        oldMeter.LastUrjanetSyncDateTime__c = lastSyncDateTime;
        oldMeter.Id = Id.valueOf(randomId);

        Map<Id, UtilityMeter__c> oldMap = new Map<Id, UtilityMeter__c>();
        oldMap.put(Id.valueOf(randomId), oldMeter);

        Test.startTest();
        Boolean hasRecordChanged = UrjanetUtils.hasSyncFieldUpdated(
            updatedMeter,
            oldMap,
            UtilityMeter__c.LastUrjanetSyncDateTime__c
        );
        Test.stopTest();

        CSutils.itShouldBe('Record Change Boolean should be false', false, hasRecordChanged);
    }

    @isTest
    static void testProcessErrorHandling() {
        GetAccountsByCredsResponse response = new GetAccountsByCredsResponse();
        response.errorMsg = 'Error Message Test';
        response.status = 500;

        try {
            Test.startTest();
            QueueItem__c queueItem = new QueueItem__c(
                RecordId__c = 'RecordId123',
                PageNumber__c = 1,
                RequestType__c = UrjanetEnums.RequestType.ACCOUNTS_BY_CREDS.name()
            );
            insert queueItem;
            UrjanetUtils.handleApiError(
                queueItem,
                response.errorMsg,
                response.message,
                response.status,
                UtilityCredentialProcessor.class.getName()
            );
            Test.stopTest();
            System.assert(false, 'Expected exception to be thrown');
        } catch (ArcadiaCalloutServiceException e) {
            System.assertEquals('Error Message Test', e.getMessage(), 'Error is expected');
        } catch (Exception e) {
            System.assert(false, 'Unexpected exception occurred: ' + e.getMessage());
        }
    }

    @isTest
    static void testGetDateRanges() {
        UtilityMeterUsage__c meterUsage = new UtilityMeterUsage__c();
        meterUsage.PeriodStart__c = Date.newInstance(2018, 1, 1);
        meterUsage.PeriodEnd__c = Date.newInstance(2018, 1, 31);
        List<UrjanetUtils.SplitDateDetails> expectedDateRanges = new List<UrjanetUtils.SplitDateDetails>();
        expectedDateRanges.add(
            new UrjanetUtils.SplitDateDetails(Date.newInstance(2018, 1, 1), Date.newInstance(2018, 1, 31))
        );
        List<UrjanetUtils.SplitDateDetails> actualDateRanges = UrjanetUtils.getDateRanges(meterUsage);
        CSutils.itShouldBe('Expected Date Ranges Size ', 1, actualDateRanges.size());
        CSutils.itShouldBe(
            'Expected Start Date ',
            expectedDateRanges.get(0).startDate,
            actualDateRanges.get(0).startDate
        );
        CSutils.itShouldBe(
            'Expected End Date ',
            expectedDateRanges.get(0).startDate,
            actualDateRanges.get(0).startDate
        );
    }

    @isTest
    static void testGetDateRangesForThreeMonths() {
        UtilityMeterUsage__c meterUsage = new UtilityMeterUsage__c();
        meterUsage.PeriodStart__c = Date.newInstance(2018, 1, 15);
        meterUsage.PeriodEnd__c = Date.newInstance(2018, 3, 10);
        List<UrjanetUtils.SplitDateDetails> expectedDateRanges = new List<UrjanetUtils.SplitDateDetails>();
        expectedDateRanges.add(
            new UrjanetUtils.SplitDateDetails(Date.newInstance(2018, 1, 15), Date.newInstance(2018, 1, 31))
        );
        expectedDateRanges.add(
            new UrjanetUtils.SplitDateDetails(Date.newInstance(2018, 2, 1), Date.newInstance(2018, 2, 28))
        );
        expectedDateRanges.add(
            new UrjanetUtils.SplitDateDetails(Date.newInstance(2018, 3, 1), Date.newInstance(2018, 3, 10))
        );
        List<UrjanetUtils.SplitDateDetails> actualDateRanges = UrjanetUtils.getDateRanges(meterUsage);
        CSutils.itShouldBe('Expected Date Ranges Size ', 3, actualDateRanges.size());
        CSutils.itShouldBe(
            'Expected Start Date 1 ',
            expectedDateRanges.get(0).startDate,
            actualDateRanges.get(0).startDate
        );
        CSutils.itShouldBe(
            'Expected End Date 1 ',
            expectedDateRanges.get(0).startDate,
            actualDateRanges.get(0).startDate
        );
        CSutils.itShouldBe(
            'Expected Start Date 2 ',
            expectedDateRanges.get(1).startDate,
            actualDateRanges.get(1).startDate
        );
        CSutils.itShouldBe(
            'Expected End Date 2 ',
            expectedDateRanges.get(1).startDate,
            actualDateRanges.get(1).startDate
        );
        CSutils.itShouldBe(
            'Expected Start Date 3 ',
            expectedDateRanges.get(2).startDate,
            actualDateRanges.get(2).startDate
        );
        CSutils.itShouldBe(
            'Expected End Date 3 ',
            expectedDateRanges.get(2).startDate,
            actualDateRanges.get(2).startDate
        );
    }

    @isTest
    static void testGetDateRangesForSameDate() {
        UtilityMeterUsage__c meterUsage = new UtilityMeterUsage__c();
        meterUsage.PeriodStart__c = Date.newInstance(2018, 1, 15);
        meterUsage.PeriodEnd__c = Date.newInstance(2018, 1, 15);
        List<UrjanetUtils.SplitDateDetails> expectedDateRanges = new List<UrjanetUtils.SplitDateDetails>();
        expectedDateRanges.add(
            new UrjanetUtils.SplitDateDetails(Date.newInstance(2018, 1, 15), Date.newInstance(2018, 1, 15))
        );
        List<UrjanetUtils.SplitDateDetails> actualDateRanges = UrjanetUtils.getDateRanges(meterUsage);

        CSutils.itShouldBe('Expected Date Ranges Size ', 1, actualDateRanges.size());
        CSutils.itShouldBe(
            'Expected Start Date ',
            expectedDateRanges.get(0).startDate,
            actualDateRanges.get(0).startDate
        );
        CSutils.itShouldBe(
            'Expected End Date ',
            expectedDateRanges.get(0).startDate,
            actualDateRanges.get(0).startDate
        );
    }

    @isTest
    static void testGetDateRangesForOneMonthAndOneDay() {
        UtilityMeterUsage__c meterUsage = new UtilityMeterUsage__c();
        meterUsage.PeriodStart__c = Date.newInstance(2018, 1, 2);
        meterUsage.PeriodEnd__c = Date.newInstance(2018, 2, 1);
        List<UrjanetUtils.SplitDateDetails> expectedDateRanges = new List<UrjanetUtils.SplitDateDetails>();
        expectedDateRanges.add(
            new UrjanetUtils.SplitDateDetails(Date.newInstance(2018, 1, 2), Date.newInstance(2018, 1, 31))
        );
        expectedDateRanges.add(
            new UrjanetUtils.SplitDateDetails(Date.newInstance(2018, 2, 1), Date.newInstance(2018, 2, 1))
        );
        List<UrjanetUtils.SplitDateDetails> actualDateRanges = UrjanetUtils.getDateRanges(meterUsage);
        CSutils.itShouldBe('Expected Date Ranges Size ', 2, actualDateRanges.size());
        CSutils.itShouldBe(
            'Expected Start Date 1 ',
            expectedDateRanges.get(0).startDate,
            actualDateRanges.get(0).startDate
        );
        CSutils.itShouldBe(
            'Expected End Date 1 ',
            expectedDateRanges.get(0).startDate,
            actualDateRanges.get(0).startDate
        );
        CSutils.itShouldBe(
            'Expected Start Date 2 ',
            expectedDateRanges.get(1).startDate,
            actualDateRanges.get(1).startDate
        );
        CSutils.itShouldBe(
            'Expected End Date 2 ',
            expectedDateRanges.get(1).startDate,
            actualDateRanges.get(1).startDate
        );
    }
}