force-app/main/default/objects/UsageDownstreamDeleterSetting__mdt/UsageDownstreamDeleterSetting__mdt.object-meta.xml
<CustomObject>
    <description>Custom Metadata used to store the Deleter class name to be used for each service type</description>
    <label>Usage Downstream Data Deleter Setting</label>
    <pluralLabel>Usage Downstream Data Deleter Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/UsageDownstreamDeleterSetting__mdt/fields/DeleterClassName__c.field-meta.xml
<CustomField>
    <fullName>DeleterClassName__c</fullName>
    <description>Salesforce Deleter Class Name</description>
    <inlineHelpText>Salesforce Deleter Class Name</inlineHelpText>
    <label>Deleter Class Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ServiceToDownstreamDeleterMapSelector.cls
public with sharing class ServiceToDownstreamDeleterMapSelector extends Selector {
    public ServiceToDownstreamDeleterMapSelector() {
        super(Schema.UsageDownstreamDeleterSetting__mdt.SObjectType);
    }
    public ServiceToDownstreamDeleterMapSelector(Boolean enforceCRUD, Boolean enforceFLS, Boolean enforceShr) {
        super(Schema.UsageDownstreamDeleterSetting__mdt.SObjectType, enforceCRUD, enforceFLS, enforceShr);
    }

    /**
     * Returns a Set that has all of the default fields.
     * @return   Set of Strings that contain the default fields for this object
     */
    public override Set<String> getDefaultFields() {
        return new Set<String>{ 'Id', 'DeveloperName', 'DeleterClassName__c', 'ServiceType__c' };
    }
}