force-app/main/default/objects/UrjanetSettings__c/UrjanetSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for Arcadia Connect App</description>
    <label>Arcadia Settings</label>
</CustomObject>

force-app/main/default/objects/UrjanetSettings__c/fields/OrganizationId__c.field-meta.xml
<CustomField>
    <fullName>OrganizationId__c</fullName>
    <description
    >A field to store Arcadia’s Organization Id (which is the back part of the unique URL) https://connect.urjanet.com/&lt;Organization Id&gt;</description>
    <externalId>true</externalId>
    <label>Organization Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/UtilityCredential__c.object-meta.xml
<CustomObject>
    <description
    >A custom object (created by the Urjanet Connect app) to store status information about utility credentials</description>
    <label>Utility Credential</label>
    <nameField>
        <label>Utility Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityCredential__c/fields/CorrelationID__c.field-meta.xml
<CustomField>
    <fullName>CorrelationID__c</fullName>
    <description>A unique number to identify this utility credential record within Urjanet&apos;s sytem.</description>
    <externalId>true</externalId>
    <inlineHelpText>A unique number to identify this utility credential record within Urjanet&apos;s sytem.</inlineHelpText>
    <label>Correlation ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description
    >Credential-level statuses that let you know if there are any issues accessing the provider portal, the data, or with the credential itself.</description>
    <inlineHelpText
    >Credential-level statuses that let you know if there are any issues accessing the provider portal, the data, or with the credential itself.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>PENDING</fullName>
                <label>Pending</label>
            </value>
            <value>
                <fullName>SENT_TO_URJANET</fullName>
                <label>Sent To Arcadia</label>
            </value>
            <value>
                <fullName>ACTION_REQUIRED</fullName>
                <label>Action Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/UrjanetId__c.field-meta.xml
<CustomField>
    <fullName>UrjanetId__c</fullName>
    <description>Unique ID for the account on Arcadia system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique ID for the account on Arcadia system.</inlineHelpText>
    <label>ArcadiaId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/UrjanetCanvasApp/UrjanetCanvasAppControllerTest.cls
/**
 * Created by Alagu on 5/21/22.
 */

@IsTest
private class UrjanetCanvasAppControllerTest {
    @IsTest
    static void getInitialCredentialLinkWithoutIdTest() {
        String orgId = 'test org Id';
        String name = 'test correlation';
        User adminUser = TestUtility.createUserAdmin('urjanetAdmin@urjanettest.com');
        System.runAs(adminUser) {
            UtilityCredential__c utilityCredential = new UtilityCredential__c(Name = name);
            insert utilityCredential;
            UrjanetSettings__c settings = new UrjanetSettings__c();
            settings.OrganizationId__c = orgId;
            insert settings;

            Test.startTest();
            ApexPages.currentPage().getParameters().put('id', String.valueOf(utilityCredential.Id));
            UrjanetCanvasAppController controller = new UrjanetCanvasAppController();
            Test.stopTest();
            String initialCredentialLink =
                '{"path":"/test org Id/canvas?correlationId=NZC-ARC-' +
                utilityCredential.Id +
                '&hideFinalButtons=true&salesforce=true"}';

            CSutils.itShouldBe('Initial credential link', initialCredentialLink, controller.pathString);
        }
    }

    @IsTest
    static void getInitialCredentialLinkWithIdTest() {
        String orgId = 'test org Id';
        String correlationId = 'test correlation Id';
        User adminUser = TestUtility.createUserAdmin('urjanetAdmin@urjanettest.com');
        System.runAs(adminUser) {
            UtilityCredential__c utilityCredential = new UtilityCredential__c(CorrelationId__c = correlationId);
            insert utilityCredential;
            UrjanetSettings__c settings = new UrjanetSettings__c();
            settings.OrganizationId__c = orgId;
            insert settings;

            Test.startTest();
            ApexPages.currentPage().getParameters().put('id', String.valueOf(utilityCredential.Id));
            UrjanetCanvasAppController controller = new UrjanetCanvasAppController();
            Test.stopTest();
            String initialCredentialLink =
                '{"path":"/test org Id/canvas?correlationId=test+correlation+Id' +
                '&hideFinalButtons=true&salesforce=true"}';

            CSutils.itShouldBe('Initial credential link', initialCredentialLink, controller.pathString);
        }
    }

    @IsTest
    static void getNullCredentialLinkTest() {
        String orgId = 'test org Id';
        String correlationId = 'test correlation Id';
        User adminUser = TestUtility.createUserAdmin('urjanetAdmin@urjanettest.com');
        System.runAs(adminUser) {
            UtilityCredential__c utilityCredential = new UtilityCredential__c(
                CorrelationId__c = correlationId,
                Status__c = UrjanetConstants.CREDENTIAL_STATUS
            );
            insert utilityCredential;

            UrjanetSettings__c settings = new UrjanetSettings__c();
            settings.OrganizationId__c = orgId;
            insert settings;

            Test.startTest();
            ApexPages.currentPage().getParameters().put('id', String.valueOf(utilityCredential.Id));
            UrjanetCanvasAppController controller = new UrjanetCanvasAppController();
            Test.stopTest();

            CSutils.itShouldBe('Null Credential Link', '{"path":null}', controller.pathString);
        }
    }

    @IsTest
    static void getAlternateCredentialLinkTest() {
        StaticResourceCalloutMock mock = TestUtility.getStaticResourceCalloutMock('UpdateUrlByCredsResponse', 200);
        String orgId = 'test org Id';
        String correlationId = 'test correlation Id';
        String updateUrl = '/TestUpdatelUrl?app=RECURRING_UTILITY';
        User adminUser = TestUtility.createUserAdmin('urjanetAdmin@urjanettest.com');
        System.runAs(adminUser) {
            UtilityCredential__c utilityCredential = new UtilityCredential__c(
                CorrelationId__c = correlationId,
                Status__c = 'OK',
                UrjanetId__c = 'Test Urjanet Id'
            );
            insert utilityCredential;

            UrjanetSettings__c settings = new UrjanetSettings__c();
            settings.OrganizationId__c = orgId;
            insert settings;

            String recredentialLink = '{"path":"' + updateUrl + '&hideFinalButtons=true&salesforce=true"}';

            Test.startTest();
            ApexPages.currentPage().getParameters().put('id', String.valueOf(utilityCredential.Id));
            UrjanetCanvasAppController controller = new UrjanetCanvasAppController();
            Test.stopTest();

            CSutils.itShouldBe('Null Credential Link', recredentialLink, controller.pathString);
        }
    }

    @IsTest
    static void updateCredentialStatus() {
        String orgId = 'test org Id';
        String correlationId = 'test correlation Id';
        User adminUser = TestUtility.createUserAdmin('urjanetAdmin@urjanettest.com');
        System.runAs(adminUser) {
            UtilityCredential__c utilityCredential = new UtilityCredential__c(CorrelationId__c = correlationId);
            insert utilityCredential;

            UrjanetSettings__c settings = new UrjanetSettings__c();
            settings.OrganizationId__c = orgId;
            insert settings;

            Test.startTest();
            ApexPages.currentPage().getParameters().put('id', String.valueOf(utilityCredential.Id));
            UrjanetCanvasAppController controller = new UrjanetCanvasAppController();
            controller.updateCredentialStatus();
            Test.stopTest();

            List<UtilityCredential__c> credentialList = [SELECT Id, Status__c FROM UtilityCredential__c LIMIT 1];

            CSutils.itShouldBe(
                'Utility Credential Status',
                UrjanetConstants.CREDENTIAL_STATUS,
                credentialList[0].Status__c
            );
        }
    }
}