force-app/main/default/objects/StnryAssetDeleterSetting__mdt/StnryAssetDeleterSetting__mdt.object-meta.xml
<CustomObject>
    <description
    >Custom Metadata used to store the Stnry Asset Deleter class name to be used for each service type</description>
    <label>Stnry Asset Deleter Setting</label>
    <pluralLabel>Stnry Asset Deleter Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/StnryAssetDeleterSetting__mdt/fields/DeleterClassName__c.field-meta.xml
<CustomField>
    <fullName>DeleterClassName__c</fullName>
    <description>Stnry Asset Deleter Class Name</description>
    <inlineHelpText>Stnry Asset Deleter Class Name</inlineHelpText>
    <label>Deleter Class Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StnryAssetDeleterMappingSelector.cls
public with sharing class StnryAssetDeleterMappingSelector extends Selector {
    public StnryAssetDeleterMappingSelector() {
        super(Schema.StnryAssetDeleterSetting__mdt.SObjectType);
    }
    public StnryAssetDeleterMappingSelector(Boolean enforceCRUD, Boolean enforceFLS, Boolean enforceShr) {
        super(Schema.StnryAssetDeleterSetting__mdt.SObjectType, enforceCRUD, enforceFLS, enforceShr);
    }

    /**
     * Returns a Set that has all of the default fields.
     * @return   Set of Strings that contain the default fields for this object
     */
    public override Set<String> getDefaultFields() {
        return new Set<String>{ 'Id', 'DeveloperName', 'DeleterClassName__c', 'ServiceType__c' };
    }
}