force-app/main/default/objects/StnryAssetEnvrSrc/fields/CreatedByInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>CreatedByInUrjanet__c</fullName>
    <description
    >A custom field for the system user responsible for creating the site in Arcadia&apos;s system.</description>
    <inlineHelpText>The system user responsible for creating the site in Arcadia&apos;s system.</inlineHelpText>
    <label>Created By in Arcadia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StnryAssetEnvrSrc/fields/CreatedDateInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>CreatedDateInUrjanet__c</fullName>
    <description>A custom field for the date the site was created in Arcadia&apos;s system.</description>
    <inlineHelpText>The date the site was created in Arcadia&apos;s system.</inlineHelpText>
    <label>Created Date in Arcadia</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/StnryAssetEnvrSrc/fields/LastModifiedByInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedByInUrjanet__c</fullName>
    <description>A custom field to store the system user responsible for modifying the site most recently.</description>
    <inlineHelpText>The system user responsible for modifying the site most recently.</inlineHelpText>
    <label>Last Modified By in Arcadia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StnryAssetEnvrSrc/fields/LastModifiedInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedInUrjanet__c</fullName>
    <description
    >A custom field to store the date that the site was last modified in Arcadia&apos;s system.</description>
    <inlineHelpText>The date that the site was last modified in Arcadia&apos;s system.</inlineHelpText>
    <label>Last Modified in Arcadia</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/StnryAssetEnvrSrc/fields/UrjanetId__c.field-meta.xml
<CustomField>
    <fullName>UrjanetId__c</fullName>
    <description
    >A custom field to store the Arcadia ID to make recredentialing and other API calls easier.</description>
    <externalId>true</externalId>
    <inlineHelpText
    >A custom field to store the Arcadia ID to make recredentialing and other API calls easier.</inlineHelpText>
    <label>ArcadiaId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/StnryAssetEnvrSrc/fields/UrjanetSiteCode__c.field-meta.xml
<CustomField>
    <fullName>UrjanetSiteCode__c</fullName>
    <description
    >A custom field to store the Site Code field from Arcadia. This is an optional custom field in the Arcadia system.</description>
    <inlineHelpText>The site code as entered in the optional custom field in the Arcadia system.</inlineHelpText>
    <label>Arcadia Site Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StnryAssetEnvrSrc/fields/UrjanetSiteNumber__c.field-meta.xml
<CustomField>
    <fullName>UrjanetSiteNumber__c</fullName>
    <description
    >A custom field to store the Site Number field from Arcadia. This is an optional custom field in the Arcadia system.</description>
    <inlineHelpText>The site number as entered in the optional custom field in the Arcadia system.</inlineHelpText>
    <label>Arcadia Site Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StnryAssetEnvrSrc/fields/UrjanetSubRegion__c.field-meta.xml
<CustomField>
    <fullName>UrjanetSubRegion__c</fullName>
    <description>An optional custom field in the Arcadia system to input site’s sub region.</description>
    <inlineHelpText>An optional custom field in the Arcadia system to input site’s sub region.</inlineHelpText>
    <label>Arcadia subRegion</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StnryAssetEnvrSrc/fields/UtilityAccount__c.field-meta.xml
<CustomField>
    <fullName>UtilityAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To relate this Stationary Asset Environmental Source to a Utility Account</description>
    <inlineHelpText>To relate this Stationary Asset Environmental Source to a Utility Account</inlineHelpText>
    <label>Utility Account</label>
    <referenceTo>UtilityAccount__c</referenceTo>
    <relationshipLabel>Stationary Asset Environmental Sources</relationshipLabel>
    <relationshipName>Stationary_Asset_Environmental_Sources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier/fields/ElectricityEmissionsFactors__c.field-meta.xml
<CustomField>
    <fullName>ElectricityEmissionsFactors__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
    >A custom field so that the Urjanet app can create Stationary Asset Environmental Sources (since the emissions factor fields are required).</description>
    <inlineHelpText
    >The selection placed in this field will be used as the "Electricity Emissions Factors" field selection whenever the Urjanet App automatically creates Stationary Asset Environmental Sources from this Supplier.</inlineHelpText>
    <label>Electricity Emissions Factors</label>
    <referenceTo>ElectricityEmssnFctrSet</referenceTo>
    <relationshipLabel>Supplier</relationshipLabel>
    <relationshipName>Supplier</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier/fields/OtherEmissionsFactors__c.field-meta.xml
<CustomField>
    <fullName>OtherEmissionsFactors__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
    >A custom field so that the Urjanet app can create Stationary Asset Environmental Sources (since the emissions factor fields are required).</description>
    <inlineHelpText
    >The selection placed in this field will be used as the "Other Emissions Factors" field selection whenever the Urjanet App automatically creates Stationary Asset Environmental Sources from this Supplier.</inlineHelpText>
    <label>Other Emissions Factors</label>
    <referenceTo>OtherEmssnFctrSet</referenceTo>
    <relationshipLabel>Supplier</relationshipLabel>
    <relationshipName>Supplier</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/UtilityAccount__c.object-meta.xml
<CustomObject>
    <description>A custom object (created by the Urjanet Connect app) to store utility account information</description>
    <label>Utility Account</label>
    <nameField>
        <label>Utility Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityAccount__c/fields/CreatedByInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>CreatedByInUrjanet__c</fullName>
    <description>The system user responsible for creating the account in Arcadia&apos;s system.</description>
    <inlineHelpText>The system user responsible for creating the account in Arcadia&apos;s system.</inlineHelpText>
    <label>Created By in Arcadia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/fields/CreatedDateInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>CreatedDateInUrjanet__c</fullName>
    <description>The Date the account was registered in Arcadia’s system.</description>
    <inlineHelpText>The Date the account was registered in Arcadia’s system.</inlineHelpText>
    <label>Created Date in Arcadia</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/fields/LastModifiedByInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedByInUrjanet__c</fullName>
    <description>The system user responsible for modifying an account most recently in the Arcadia system.</description>
    <inlineHelpText
    >The system user responsible for modifying an account most recently in the Arcadia system.</inlineHelpText>
    <label>Last Modified By in Arcadia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/fields/LastModifiedInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedInUrjanet__c</fullName>
    <description>The date that an account was modified last in the Arcadia system.</description>
    <inlineHelpText>The date that an account was modified last in the Arcadia system.</inlineHelpText>
    <label>Last Modified in Arcadia</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Supplier</referenceTo>
    <relationshipLabel>Utility Accounts</relationshipLabel>
    <relationshipName>UtilityAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/fields/UtilityCredential__c.field-meta.xml
<CustomField>
    <fullName>UtilityCredential__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Utility Credential</label>
    <referenceTo>UtilityCredential__c</referenceTo>
    <relationshipLabel>Utility Accounts</relationshipLabel>
    <relationshipName>UtilityAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/UtilityCredential__c.object-meta.xml
<CustomObject>
    <description
    >A custom object (created by the Urjanet Connect app) to store status information about utility credentials</description>
    <label>Utility Credential</label>
    <nameField>
        <label>Utility Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityCredential__c/fields/CreatedByInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>CreatedByInUrjanet__c</fullName>
    <description>The system user responsible for creating a credential.</description>
    <inlineHelpText>The system user responsible for creating a credential.</inlineHelpText>
    <label>Created By in Arcadia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/LastModifiedByInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedByInUrjanet__c</fullName>
    <description>The system user responsible for modifying a credential most recently.</description>
    <inlineHelpText>The system user responsible for modifying a credential most recently.</inlineHelpText>
    <label>Last Modified By in Arcadia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/LastModifiedInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedInUrjanet__c</fullName>
    <description>The date that a credential was modified last.</description>
    <inlineHelpText>The date that a credential was modified last.</inlineHelpText>
    <label>Last Modified in Arcadia</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/ProviderName__c.field-meta.xml
<CustomField>
    <fullName>ProviderName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The commonly known name for the utility company.</description>
    <inlineHelpText>The commonly known name for the utility company.</inlineHelpText>
    <label>Provider Name</label>
    <referenceTo>Supplier</referenceTo>
    <relationshipLabel>Utility Credentials</relationshipLabel>
    <relationshipName>UtilityCredentials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityCredential__c/fields/UrjanetId__c.field-meta.xml
<CustomField>
    <fullName>UrjanetId__c</fullName>
    <description>Unique ID for the account on Arcadia system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique ID for the account on Arcadia system.</inlineHelpText>
    <label>ArcadiaId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/testClasses/StationaryAssetSourceServiceTest.cls
@IsTest
public with sharing class StationaryAssetSourceServiceTest {
    @TestSetup
    static void makeData() {
        User adminUser = TestUtility.createUserAdmin('urjanetAdmin@urjanettest.com');
        System.runAs(adminUser) {
            List<SObject> lstElectricityEmissionFactorSet = Test.loadData(
                ElectricityEmssnFctrSet.sObjectType,
                'ElectricityEmissionFactorSet'
            );
            List<SObject> lstOtherEmissionFactorSet = Test.loadData(
                OtherEmssnFctrSet.sObjectType,
                'OtherEmissionFactorSet'
            );

            Account providerAccount = new Account();
            providerAccount.Name = 'Test Provider Account';
            insert providerAccount;

            Supplier provider = new Supplier();
            provider.Name = 'Test Provider';
            provider.OtherEmissionsFactors__c = lstOtherEmissionFactorSet[0].Id;
            provider.ElectricityEmissionsFactors__c = lstElectricityEmissionFactorSet[0].Id;
            provider.AccountId = providerAccount.Id;
            insert provider;

            UtilityCredential__c credential = new UtilityCredential__c();
            credential.UrjanetId__c = TestUtility.CREDENTIAL_ID;
            credential.ProviderName__c = provider.Id;
            insert credential;

            UtilityAccount__c account = new UtilityAccount__c();
            account.UtilityCredential__c = credential.Id;
            account.UrjanetId__c = '1234abcd-2345-cd34-1234-1232434cdede';
            account.Supplier__c = provider.id;
            insert account;
        }
    }

    @IsTest
    static void postSiteResponseUpdateTest() {
        User adminUser = [SELECT Id FROM User WHERE email = 'urjanetAdmin@urjanettest.com' LIMIT 1];
        System.runAs(adminUser) {
            UtilityAccount__c account = [
                SELECT
                    Id,
                    urjanetId__c,
                    UtilityCredential__r.ProviderName__r.OtherEmissionsFactors__c,
                    UtilityCredential__r.ProviderName__r.ElectricityEmissionsFactors__c,
                    Supplier__c,
                    Supplier__r.Name,
                    Supplier__r.OtherEmissionsFactors__c,
                    Supplier__r.ElectricityEmissionsFactors__c
                FROM UtilityAccount__c
                LIMIT 1
            ];
            StnryAssetEnvrSrc site = new StnryAssetEnvrSrc();
            site.City = 'San Ramon';
            site.Country = 'US';
            site.StationaryAssetType = 'Office';
            site.PostalCode = '94583';
            site.BusinessRegion = 'AMER';
            site.UrjanetSiteCode__c = '123789';
            site.Name = 'Urjanet Test';
            site.UrjanetSiteNumber__c = 'NZC12345';
            site.UrjanetSubRegion__c = 'NorCal';
            site.State = 'CA';
            site.StreetAddress = '340 main st';
            site.StreetAddress2 = 'suite #13';
            site.UtilityAccount__c = account.Id;
            site.ElectricityEmssnFctrId = account.UtilityCredential__r.ProviderName__r.ElectricityEmissionsFactors__c;
            site.OtherEmssnFctrId = account.UtilityCredential__r.ProviderName__r.OtherEmissionsFactors__c;
            insert site;

            Test.startTest();
            StationaryAssetSourceService.updateSiteDetailsFromResponse(getMockPostSiteResponse(), site.Id);
            Test.stopTest();
            StnryAssetEnvrSrc stationaryAssetSource = [
                SELECT
                    Name,
                    UrjanetId__c,
                    LastModifiedInUrjanet__c,
                    LastModifiedByInUrjanet__c,
                    CreatedDateInUrjanet__c,
                    CreatedByInUrjanet__c
                FROM StnryAssetEnvrSrc
                LIMIT 1
            ];
            CSUtils.itShouldBe('Site Name ', 'Urjanet Test', stationaryAssetSource.Name);
            CSUtils.itShouldBe(
                'Urjanet Id ',
                '1ece6d51-dd82-d644-8a08-d23d6f619b36',
                stationaryAssetSource.UrjanetId__c
            );
            CSUtils.itShouldBe(
                'Last Modified ',
                UrjanetUtils.getDateTime('2022-06-08T02:45:54.539+00:00'),
                stationaryAssetSource.LastModifiedInUrjanet__c
            );
            CSUtils.itShouldBe('Last Modified By ', 'Urjanet.test', stationaryAssetSource.LastModifiedByInUrjanet__c);
            CSUtils.itShouldBe(
                'Created Date ',
                UrjanetUtils.getDateTime('2022-06-08T02:45:54.539+00:00'),
                stationaryAssetSource.CreatedDateInUrjanet__c
            );
            CSUtils.itShouldBe('Created By ', 'Urjanet.test', stationaryAssetSource.CreatedByInUrjanet__c);
        }
    }

    private static PostSiteResponse getMockPostSiteResponse() {
        StaticResourceCalloutMock mock = TestUtility.getStaticResourceCalloutMock('PostSiteResponse', 202);

        HttpResponse mockHttpResponse = mock.respond(new HttpRequest());
        PostSiteResponse mockResponse = (PostSiteResponse) new PostSiteResponseParser().parseResponse(mockHttpResponse);
        return mockResponse;
    }

    @isTest
    static void mapToUrjanetCountryCodeTest() {
        Test.StartTest();
        StationaryAssetSourceService.createQueueItemsToSendStationaryAssetSource();
        String countryCode3Digit = StationaryAssetSourceService.mapToUrjanetCountryCode('US');
        CSUtils.itShouldBe('Country 3 Digit Code would be :', 'USA', countryCode3Digit);
        Test.StopTest();
    }
}