force-app/main/default/objects/StnryAssetEnvrSrc/fields/UrjanetId__c.field-meta.xml
<CustomField>
    <fullName>UrjanetId__c</fullName>
    <description
    >A custom field to store the Arcadia ID to make recredentialing and other API calls easier.</description>
    <externalId>true</externalId>
    <inlineHelpText
    >A custom field to store the Arcadia ID to make recredentialing and other API calls easier.</inlineHelpText>
    <label>ArcadiaId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/UtilityMeter__c/UtilityMeter__c.object-meta.xml
<CustomObject>
    <description>A custom object (created by the Urjanet Connect app) to store utility meter information</description>
    <label>Utility Meter</label>
    <nameField>
        <label>Utility Meter Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Meters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityMeter__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates if an meter is active (meaning Urjanet is considering the meter to be valid).</description>
    <inlineHelpText>Indicates if an meter is active (meaning Urjanet is considering the meter to be valid).</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UtilityMeter__c/fields/PodNumber__c.field-meta.xml
<CustomField>
    <fullName>PodNumber__c</fullName>
    <description>The point of delivery number in deregulated markets. This is an independent identifier for meter location and used by all utility companies in deregulated markets.</description>
    <inlineHelpText>The point of delivery number in deregulated markets. This is an independent identifier for meter location and used by all utility companies in deregulated markets.</inlineHelpText>
    <label>Pod Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityMeter__c/fields/ServiceType__c.field-meta.xml
<CustomField>
    <fullName>ServiceType__c</fullName>
    <description>The meter’s service type.</description>
    <inlineHelpText>The meter’s service type.</inlineHelpText>
    <label>Service Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityMeter__c/fields/StationaryAssetEnvironmentalSource__c.field-meta.xml
<CustomField>
    <fullName>StationaryAssetEnvironmentalSource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Stationary Asset Environmental Source for this Utility Meter.</description>
    <inlineHelpText>The Stationary Asset Environmental Source for this Utility Meter.</inlineHelpText>
    <label>Stationary Asset Environmental Source</label>
    <referenceTo>StnryAssetEnvrSrc</referenceTo>
    <relationshipLabel>Utility Meters</relationshipLabel>
    <relationshipName>UtilityMeters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityMeter__c/fields/UrjanetId__c.field-meta.xml
<CustomField>
    <fullName>UrjanetId__c</fullName>
    <description>Unique ID for the meter on Arcadia system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique ID for the meter on Arcadia system.</inlineHelpText>
    <label>ArcadiaId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/UtilityMeterUsage__c/UtilityMeterUsage__c.object-meta.xml
<CustomObject>
    <description>A custom object (created by the Urjanet Connect app) to store utility meter usage data.</description>
    <label>Utility Meter Usage</label>
    <nameField>
        <label>Utility Meter Usage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Meter Usages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityMeterUsage__c/fields/Arcadia_Statement_ID__c.field-meta.xml
<CustomField>
    <fullName>Arcadia_Statement_ID__c</fullName>
    <description>It is used to store the statement Id of meter usage</description>
    <inlineHelpText>Unique ID for the statement on Arcadia system</inlineHelpText>
    <label>Arcadia Statement ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityMeterUsage__c/fields/MeasuredUsage__c.field-meta.xml
<CustomField>
    <fullName>MeasuredUsage__c</fullName>
    <description>Represents actual consumption at the meter location.</description>
    <inlineHelpText
    >Represents actual consumption at the meter location. (Editing this field will trigger the "Manually Updated" field for this asset)</inlineHelpText>
    <label>Measured Usage</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UtilityMeterUsage__c/fields/PeriodEnd__c.field-meta.xml
<CustomField>
    <fullName>PeriodEnd__c</fullName>
    <description>Date that the billing period ended.</description>
    <inlineHelpText
    >Date that the billing period ended. (Editing this field will trigger the "Manually Updated" field for this asset)</inlineHelpText>
    <label>Period End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/UtilityMeterUsage__c/fields/PeriodStart__c.field-meta.xml
<CustomField>
    <fullName>PeriodStart__c</fullName>
    <description>Date that the billing period started.</description>
    <inlineHelpText
    >Date that the billing period started. (Editing this field will trigger the "Manually Updated" field for this asset)
    </inlineHelpText>
    <label>Period Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/UtilityMeterUsage__c/fields/To_Be_Ignored__c.field-meta.xml
<CustomField>
    <fullName>To_Be_Ignored__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if an meter usage is to be ignored for downstream data creation (meaning Urjanet is considering the meter usage to be valid).</description>
    <inlineHelpText>Indicates if an meter usage is to be ignored for downstream data creation (meaning Urjanet is considering the meter usage to be valid).</inlineHelpText>
    <label>To Be Ignored</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UtilityMeterUsage__c/fields/UrjanetId__c.field-meta.xml
<CustomField>
    <fullName>UrjanetId__c</fullName>
    <description>Unique ID for the meter usage on Arcadia system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique ID for the meter usage on Arcadia system.</inlineHelpText>
    <label>ArcadiaId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/UtilityMeterUsage__c/fields/UtilityMeter__c.field-meta.xml
<CustomField>
    <fullName>UtilityMeter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Utility Meter for this Utility Meter Usage record.</description>
    <inlineHelpText>The Utility Meter for this Utility Meter Usage record.</inlineHelpText>
    <label>Utility Meter</label>
    <referenceTo>UtilityMeter__c</referenceTo>
    <relationshipLabel>Utility Meter Usages</relationshipLabel>
    <relationshipName>UtilityMeterUsages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UtilityMeterSelector.cls
public with sharing class UtilityMeterSelector extends Selector {
    public UtilityMeterSelector() {
        super(Schema.UtilityMeter__c.SObjectType);
    }

    public UtilityMeterSelector(Boolean enforceCRUD, Boolean enforceFLS, Boolean enforceShr) {
        super(Schema.UtilityMeter__c.SObjectType, enforceCRUD, enforceFLS, EnforceShr);
    }

    public override Set<String> getDefaultFields() {
        return new Set<String>{
            'Id',
            'Name',
            'UrjanetId__c',
            'ServiceType__c',
            'StationaryAssetEnvironmentalSource__c',
            'StationaryAssetEnvironmentalSource__r.UrjanetId__c',
            'Enabled__c'
        };
    }
    public Database.QueryLocator getUtilityMetersWithNullValues() {
        Map<String, Object> params = new Map<String, Object>();

        String query = getDefaultQuery();
        String subquery = 'SELECT UtilityMeter__c FROM UtilityMeterUsage__c WHERE UrjanetId__c = null';
        query += ' WHERE Id IN (' + subquery + ')';

        return Database.getQueryLocator(query);
    }
    public Database.QueryLocator getUtilityMeterWithValidUsages() {
        Map<String, Object> params = new Map<String, Object>();
        String query = 'SELECT Id,Name,Enabled__c,StationaryAssetEnvironmentalSource__c,PodNumber__c, ServiceType__c, '+
                        '(SELECT Id, MeasuredUsage__c, PeriodStart__c, PeriodEnd__c, Arcadia_Statement_ID__c , UtilityMeter__c FROM UtilityMeterUsages__r '+
                        'WHERE To_Be_Ignored__c = false AND MeasuredUsage__c != null) '+
                        'FROM UtilityMeter__c WHERE Enabled__c = true AND StationaryAssetEnvironmentalSource__c != null' ;
        return Database.getQueryLocator(query);
    }
}