force-app/main/default/objects/StnryAssetEnvrSrc/fields/UrjanetId__c.field-meta.xml
<CustomField>
    <fullName>UrjanetId__c</fullName>
    <description
    >A custom field to store the Arcadia ID to make recredentialing and other API calls easier.</description>
    <externalId>true</externalId>
    <inlineHelpText
    >A custom field to store the Arcadia ID to make recredentialing and other API calls easier.</inlineHelpText>
    <label>ArcadiaId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/StnryAssetEnvrSrc/fields/UrjanetSiteCode__c.field-meta.xml
<CustomField>
    <fullName>UrjanetSiteCode__c</fullName>
    <description
    >A custom field to store the Site Code field from Arcadia. This is an optional custom field in the Arcadia system.</description>
    <inlineHelpText>The site code as entered in the optional custom field in the Arcadia system.</inlineHelpText>
    <label>Arcadia Site Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StnryAssetEnvrSrc/fields/UrjanetSiteNumber__c.field-meta.xml
<CustomField>
    <fullName>UrjanetSiteNumber__c</fullName>
    <description
    >A custom field to store the Site Number field from Arcadia. This is an optional custom field in the Arcadia system.</description>
    <inlineHelpText>The site number as entered in the optional custom field in the Arcadia system.</inlineHelpText>
    <label>Arcadia Site Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StnryAssetEnvrSrc/fields/UrjanetSubRegion__c.field-meta.xml
<CustomField>
    <fullName>UrjanetSubRegion__c</fullName>
    <description>An optional custom field in the Arcadia system to input site’s sub region.</description>
    <inlineHelpText>An optional custom field in the Arcadia system to input site’s sub region.</inlineHelpText>
    <label>Arcadia subRegion</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StationaryAssetSourceSelector.cls
public with sharing class StationaryAssetSourceSelector extends Selector {
    public StationaryAssetSourceSelector() {
        super(Schema.StnryAssetEnvrSrc.SObjectType);
    }

    public StationaryAssetSourceSelector(Boolean enforceCRUD, Boolean enforceFLS, Boolean enforceShr) {
        super(Schema.StnryAssetEnvrSrc.SObjectType, enforceCRUD, enforceFLS, EnforceShr);
    }

    public override Set<String> getDefaultFields() {
        return new Set<String>{
            'Id',
            'Name',
            'City',
            'Country',
            'State',
            'StreetAddress',
            'StreetAddress2',
            'StationaryAssetType',
            'PostalCode',
            'UrjanetSiteCode__c',
            'UrjanetSiteNumber__c',
            'BusinessRegion',
            'UrjanetSubRegion__c',
            'UrjanetId__c'
        };
    }

    /**
     * Gets Stationary asset source records that need the details synced to Urjanet
     * @return Stationary Asset Sources
     */
    public List<StnryAssetEnvrSrc> getRecordsToCreateSites() {
        Map<String, Object> params = new Map<String, Object>();

        String query = getDefaultQuery();
        query += ' WHERE UrjanetId__c = null AND Name != null';

        return new List<StnryAssetEnvrSrc>(
            (List<StnryAssetEnvrSrc>) Data.read(
                query,
                params,
                this.isEnforcingCRUD(),
                this.isEnforcingFLS(),
                this.isEnforcingShr()
            )
        );
    }
}