force-app/main/default/objects/StnryAssetEnvrSrc/fields/UtilityAccount__c.field-meta.xml
<CustomField>
    <fullName>UtilityAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To relate this Stationary Asset Environmental Source to a Utility Account</description>
    <inlineHelpText>To relate this Stationary Asset Environmental Source to a Utility Account</inlineHelpText>
    <label>Utility Account</label>
    <referenceTo>UtilityAccount__c</referenceTo>
    <relationshipLabel>Stationary Asset Environmental Sources</relationshipLabel>
    <relationshipName>Stationary_Asset_Environmental_Sources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/UtilityAccount__c.object-meta.xml
<CustomObject>
    <description>A custom object (created by the Urjanet Connect app) to store utility account information</description>
    <label>Utility Account</label>
    <nameField>
        <label>Utility Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityMeter__c/UtilityMeter__c.object-meta.xml
<CustomObject>
    <description>A custom object (created by the Urjanet Connect app) to store utility meter information</description>
    <label>Utility Meter</label>
    <nameField>
        <label>Utility Meter Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Meters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityMeter__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates if an meter is active (meaning Urjanet is considering the meter to be valid).</description>
    <inlineHelpText>Indicates if an meter is active (meaning Urjanet is considering the meter to be valid).</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UtilityMeter__c/fields/PodNumber__c.field-meta.xml
<CustomField>
    <fullName>PodNumber__c</fullName>
    <description>The point of delivery number in deregulated markets. This is an independent identifier for meter location and used by all utility companies in deregulated markets.</description>
    <inlineHelpText>The point of delivery number in deregulated markets. This is an independent identifier for meter location and used by all utility companies in deregulated markets.</inlineHelpText>
    <label>Pod Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityMeter__c/fields/ProviderName__c.field-meta.xml
<CustomField>
    <fullName>ProviderName__c</fullName>
    <description>Provider Name for the meter on Arcadia System.</description>
    <externalId>true</externalId>
    <inlineHelpText>Provider Name for the meter on Arcadia System.</inlineHelpText>
    <label>Arcadia Utility Provider</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityMeter__c/fields/ServiceType__c.field-meta.xml
<CustomField>
    <fullName>ServiceType__c</fullName>
    <description>The meter’s service type.</description>
    <inlineHelpText>The meter’s service type.</inlineHelpText>
    <label>Service Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityMeter__c/fields/StationaryAssetEnvironmentalSource__c.field-meta.xml
<CustomField>
    <fullName>StationaryAssetEnvironmentalSource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Stationary Asset Environmental Source for this Utility Meter.</description>
    <inlineHelpText>The Stationary Asset Environmental Source for this Utility Meter.</inlineHelpText>
    <label>Stationary Asset Environmental Source</label>
    <referenceTo>StnryAssetEnvrSrc</referenceTo>
    <relationshipLabel>Utility Meters</relationshipLabel>
    <relationshipName>UtilityMeters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityMeterUsage__c/UtilityMeterUsage__c.object-meta.xml
<CustomObject>
    <description>A custom object (created by the Urjanet Connect app) to store utility meter usage data.</description>
    <label>Utility Meter Usage</label>
    <nameField>
        <label>Utility Meter Usage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Meter Usages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityMeterUsage__c/fields/AccountType__c.field-meta.xml
<CustomField>
    <fullName>AccountType__c</fullName>
    <description>Account Type : Normal, Sub Account, Summary</description>
    <inlineHelpText>Account Type : Normal, Sub Account, Summary.</inlineHelpText>
    <label>Account Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityMeterUsage__c/fields/Arcadia_Statement_ID__c.field-meta.xml
<CustomField>
    <fullName>Arcadia_Statement_ID__c</fullName>
    <description>It is used to store the statement Id of meter usage</description>
    <inlineHelpText>Unique ID for the statement on Arcadia system</inlineHelpText>
    <label>Arcadia Statement ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityMeterUsage__c/fields/DeregulationStatus__c.field-meta.xml
<CustomField>
    <fullName>DeregulationStatus__c</fullName>
    <description>Deregulation Status: supply, delivery, full service.</description>
    <inlineHelpText>Deregulation Status: supply, delivery, full service.</inlineHelpText>
    <label>Deregulation Status </label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityMeterUsage__c/fields/IsRecordLocked__c.field-meta.xml
<CustomField>
    <fullName>IsRecordLocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Record Locked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UtilityMeterUsage__c/fields/MeasuredUsage__c.field-meta.xml
<CustomField>
    <fullName>MeasuredUsage__c</fullName>
    <description>Represents actual consumption at the meter location.</description>
    <inlineHelpText
    >Represents actual consumption at the meter location. (Editing this field will trigger the "Manually Updated" field for this asset)</inlineHelpText>
    <label>Measured Usage</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UtilityMeterUsage__c/fields/MeasuredUsageInText__c.field-meta.xml
<CustomField>
    <fullName>MeasuredUsageInText__c</fullName>
    <description>Represents actual consumption at the meter location.</description>
    <inlineHelpText>Measured Usage in Text</inlineHelpText>
    <label>Measured Usage In Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>
    

force-app/main/default/objects/UtilityMeterUsage__c/fields/MeasurementType__c.field-meta.xml
<CustomField>
    <fullName>MeasurementType__c</fullName>
    <description>Delivery terms of the tariff: General consumption, demand, bi-directional in, bi-directional out, deduct, deliveries.</description>
    <inlineHelpText>Delivery terms of the tariff: General consumption, demand, bi-directional in, bi-directional out, deduct, deliveries.</inlineHelpText>
    <label>Measurement Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityMeterUsage__c/fields/PeriodEnd__c.field-meta.xml
<CustomField>
    <fullName>PeriodEnd__c</fullName>
    <description>Date that the billing period ended.</description>
    <inlineHelpText
    >Date that the billing period ended. (Editing this field will trigger the "Manually Updated" field for this asset)</inlineHelpText>
    <label>Period End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/UtilityMeterUsage__c/fields/PeriodStart__c.field-meta.xml
<CustomField>
    <fullName>PeriodStart__c</fullName>
    <description>Date that the billing period started.</description>
    <inlineHelpText
    >Date that the billing period started. (Editing this field will trigger the "Manually Updated" field for this asset)
    </inlineHelpText>
    <label>Period Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/UtilityMeterUsage__c/fields/To_Be_Ignored__c.field-meta.xml
<CustomField>
    <fullName>To_Be_Ignored__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if an meter usage is to be ignored for downstream data creation (meaning Urjanet is considering the meter usage to be valid).</description>
    <inlineHelpText>Indicates if an meter usage is to be ignored for downstream data creation (meaning Urjanet is considering the meter usage to be valid).</inlineHelpText>
    <label>To Be Ignored</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UtilityMeterUsage__c/fields/UsageUnit__c.field-meta.xml
<CustomField>
    <fullName>UsageUnit__c</fullName>
    <description>The meter’s usage unit of measure.</description>
    <inlineHelpText
    >The meter’s usage unit of measure. (Editing this field will trigger the "Manually Updated" field for this asset)</inlineHelpText>
    <label>Usage Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityMeterUsage__c/fields/UtilityMeter__c.field-meta.xml
<CustomField>
    <fullName>UtilityMeter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Utility Meter for this Utility Meter Usage record.</description>
    <inlineHelpText>The Utility Meter for this Utility Meter Usage record.</inlineHelpText>
    <label>Utility Meter</label>
    <referenceTo>UtilityMeter__c</referenceTo>
    <relationshipLabel>Utility Meter Usages</relationshipLabel>
    <relationshipName>UtilityMeterUsages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UtilityMeterUsageSelector.cls
/**
 * Created by mike on 5/11/22.
 */

 public with sharing class UtilityMeterUsageSelector extends Selector {
    public UtilityMeterUsageSelector() {
        super(Schema.UtilityMeterUsage__c.SObjectType);
    }

    public UtilityMeterUsageSelector(Boolean enforceCRUD, Boolean enforceFLS, Boolean enforceShr) {
        super(Schema.UtilityMeterUsage__c.SObjectType, enforceCRUD, enforceFLS, EnforceShr);
    }

    public override Set<String> getDefaultFields() {
        return new Set<String>{
            'Id',
            'Name',
            'PeriodStart__c',
            'PeriodEnd__c',
            'UsageUnit__c',
            'MeasuredUsage__c',
            'MeasurementType__c',
            'AccountType__c',
            'DeregulationStatus__c',
            'UtilityMeter__c',
            'UtilityMeter__r.ServiceType__c',
            'UtilityMeter__r.StationaryAssetEnvironmentalSource__c',
            'UtilityMeter__r.StationaryAssetEnvironmentalSource__r.Name',
            'UtilityMeter__r.StationaryAssetEnvironmentalSource__r.UtilityAccount__r.UtilityCredential__r.ProviderName__c'
        };
    }

    public List<UtilityMeterUsage__c> getMostRecentUtilityMeterUsageForMeter(Id meterId) {
        List<String> queryFields = new List<String>(this.getDefaultFields());

        Map<String, Object> queryArgs = new Map<String, Object>{ 'meterId' => meterId };

        String query =
            'SELECT ' +
            String.join(queryFields, ', ') +
            ' FROM UtilityMeterUsage__c' +
            ' WHERE UtilityMeter__c = :meterId' +
            ' ORDER BY PeriodEnd__c DESC' +
            ' LIMIT 1';

        return new List<UtilityMeterUsage__c>(
            (List<UtilityMeterUsage__c>) Data.read(
                query,
                queryArgs,
                this.isEnforcingCRUD(),
                this.isEnforcingFLS(),
                this.isEnforcingShr()
            )
        );
    }

    public Database.QueryLocator getUsagesToBeCheckedForDuplicacy() {
        List<String> measuredUsageInTextList = getMeasuredUsageInTextWithCountGreaterThanOne();

        if (measuredUsageInTextList.isEmpty()) {
            // Return an empty query locator if no results found in the first query
            return Database.getQueryLocator([SELECT Id FROM UtilityMeterUsage__c WHERE Id = NULL]);
        }

        String query =
            'SELECT Id, UsageUnit__c , MeasuredUsage__c , MeasuredUsageInText__c, PeriodStart__c, PeriodEnd__c, Arcadia_Statement_ID__c, To_Be_Ignored__c, UtilityMeter__c, UtilityMeter__r.PodNumber__c, UtilityMeter__r.ServiceType__c, UtilityMeter__r.StationaryAssetEnvironmentalSource__c, UtilityMeter__r.Enabled__c ' +
            'FROM UtilityMeterUsage__c ' +
            'WHERE To_Be_Ignored__c = false AND MeasuredUsage__c != null AND MeasuredUsage__c > 0 AND UtilityMeter__r.Enabled__c = true ' +
            'AND UsageUnit__c != null ' +
            'AND MeasuredUsageInText__c IN :measuredUsageInTextList AND IsRecordLocked__c = false ' +
            'ORDER BY CreatedDate ASC';

        return Database.getQueryLocator(query);
    }

    private List<String> getMeasuredUsageInTextWithCountGreaterThanOne() {
        String query =
            'SELECT MeasuredUsageInText__c ' +
            'FROM UtilityMeterUsage__c ' +
            'WHERE To_Be_Ignored__c = false AND MeasuredUsage__c != null AND MeasuredUsage__c > 0 AND UtilityMeter__r.Enabled__c = true ' +
            'AND PeriodStart__c != null AND PeriodEnd__c != null AND Arcadia_Statement_ID__c != null AND IsRecordLocked__c = false ' +
            'GROUP BY MeasuredUsageInText__c ' +
            'HAVING COUNT(Id) > 1';

        List<AggregateResult> aggregateResults = Database.query(query);
        List<String> measuredUsageInTextList = new List<String>();

        if (!UrjanetUtils.getDevelopmentOrg()){
            for (AggregateResult ar : aggregateResults) {
                measuredUsageInTextList.add((String) ar.get('urjanet__MeasuredUsageInText__c'));
            }
        }
        else {
            for (AggregateResult ar : aggregateResults) {
                measuredUsageInTextList.add((String) ar.get('MeasuredUsageInText__c'));
            }
        }
        return measuredUsageInTextList;
    }
    public Database.QueryLocator getUsagesToBeDeleted() {
        String query =
            'SELECT Id, UtilityMeter__r.ServiceType__c, UtilityMeter__r.Enabled__c ' +
            'FROM UtilityMeterUsage__c ' +
            'WHERE To_Be_Ignored__c = true ' +
            'OR UtilityMeter__r.Enabled__c = false';
        return Database.getQueryLocator(query);
    }
}