force-app/main/default/objects/LastSuccessfulSyncDate__c/LastSuccessfulSyncDate__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used to save the Last Successful Sync Date</description>
    <label>Last Successful Sync Date</label>
</CustomObject>

force-app/main/default/objects/LastSuccessfulSyncDate__c/fields/LastSyncDate__c.field-meta.xml
<CustomField>
    <fullName>LastSyncDate__c</fullName>
    <description>This field will be saving the Last Successful Sync Date</description>
    <label>LastSyncDate__c</label>
    <required>true</required>
    <type>DateTime</type>
    </CustomField>

force-app/main/default/objects/LastSuccessfulSyncDate__c/fields/PreviousLastSyncDate__c.field-meta.xml
<CustomField>
    <fullName>PreviousLastSyncDate__c</fullName>
    <description>This field will be saving the Previous Last Successful Sync Date</description>
    <label>PreviousLastSyncDate__c</label>
    <required>true</required>
    <type>DateTime</type>
    </CustomField>

force-app/main/CS-QueueScience/objects/QueueItem__c/QueueItem__c.object-meta.xml
<CustomObject>
    <label>Queue Item</label>
    <nameField>
        <displayFormat>QI-{000000000}</displayFormat>
        <label>Queue Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Queue Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QueueItem__c/fields/PageNumber__c.field-meta.xml
<CustomField>
    <fullName>PageNumber__c</fullName>
    <description>This field is used with API pagination to indicate the next page number to retrieve</description>
    <label>Page Number</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/CS-QueueScience/objects/QueueItem__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <description>Contains the SFDC Id of the record to be processed.</description>
    <externalId>true</externalId>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QueueItem__c/fields/RequestType__c.field-meta.xml
<CustomField>
    <fullName>RequestType__c</fullName>
    <description>This field is used with API pagination to store the type of API we need to execute when the Queue Item record is processed.</description>
    <label>Request Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityAccount__c/UtilityAccount__c.object-meta.xml
<CustomObject>
    <description>A custom object (created by the Urjanet Connect app) to store utility account information</description>
    <label>Utility Account</label>
    <nameField>
        <label>Utility Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityMeter__c/UtilityMeter__c.object-meta.xml
<CustomObject>
    <description>A custom object (created by the Urjanet Connect app) to store utility meter information</description>
    <label>Utility Meter</label>
    <nameField>
        <label>Utility Meter Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Meters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityMeter__c/fields/UrjanetId__c.field-meta.xml
<CustomField>
    <fullName>UrjanetId__c</fullName>
    <description>Unique ID for the meter on Arcadia system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique ID for the meter on Arcadia system.</inlineHelpText>
    <label>ArcadiaId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/UtilityAccountProcessor.cls
public with sharing class UtilityAccountProcessor extends QueueItemWorkerBase {
    public override QueueItem__c process(QueueItem__c queueItem) {
        // Ignoring security here since this is a system process
        UtilityAccount__c accountToProcess = (UtilityAccount__c) new UtilityAccountSelector(false, false, false)
            .getRecordById(queueItem.RecordId__c);

        if (accountToProcess == null) {
            Logger.getInstance()
                .log(
                    UtilityAccountProcessor.class.getName(),
                    Logger.Level.WARN,
                    'Unable to Process Account as the record is null : ' + queueItem.RecordId__c
                );
            return queueItem;
        }

        if (accountToProcess.UrjanetId__c == null) {
            Logger.getInstance()
                .log(
                    UtilityAccountProcessor.class.getName(),
                    Logger.Level.WARN,
                    'Unable to Process Account as ArcadiaId is null : ' + queueItem.RecordId__c
                );
            return queueItem;
        }

        String pageSize = UrjanetUtils.getAPIPageSize();
        String pageNumber = (queueItem.PageNumber__c == null
            ? '0'
            : String.valueOf(Integer.valueOf(queueItem.PageNumber__c)));

        Datetime previousLastSyncDate = null;
        LastSuccessfulSyncDate__c lastSuccessfulSyncDate = LastSuccessfulSyncDate__c.getInstance(
            UserInfo.getProfileId()
        );
        if (lastSuccessfulSyncDate != null) {
            previousLastSyncDate = lastSuccessfulSyncDate.PreviousLastSyncDate__c != null
                ? lastSuccessfulSyncDate.PreviousLastSyncDate__c
                : Datetime.newInstance(1990, 1, 1);
        } else {
            previousLastSyncDate = Datetime.newInstance(1990, 1, 1);
            lastSuccessfulSyncDate.PreviousLastSyncDate__c = previousLastSyncDate;
            lastSuccessfulSyncDate.LastSyncDate__c = Datetime.now();
            upsert lastSuccessfulSyncDate;
        }

        List<String> requestParams = new List<String>{
            accountToProcess.UrjanetId__c,
            pageSize,
            pageNumber,
            String.valueOf(previousLastSyncDate.format('yyyy-MM-dd\'T\'HH:mm:ss'))
        };

        ////////Start Finish all the API callout first///////////
        GetMetersByAccountResponse meterResponse;

        if (
            queueItem.RequestType__c == null ||
            queueItem.RequestType__c == UrjanetEnums.RequestType.METERS_BY_ACCOUNT.name()
        ) {
            // Get Meters data from urjanet
            meterResponse = (GetMetersByAccountResponse) new UrjanetApiClient()
                .getUrjanetResponse(
                    UrjanetEnums.RequestType.METERS_BY_ACCOUNT,
                    UrjanetEnums.ApiMethod.GET,
                    requestParams
                );
        }
        ////////End Finish all the API callout first///////////

        if (meterResponse != null) {
            if (meterResponse.errorMsg != null) {
                UrjanetUtils.handleApiError(
                    queueItem,
                    meterResponse.errorMsg,
                    meterResponse.message,
                    meterResponse.status,
                    UtilityAccountProcessor.class.getName()
                );
            } else {
                // Meter records from Account Response
                List<UtilityMeter__c> metersByAccountList = UtilityMeterService.createMeterFromDataResponse(
                    meterResponse
                );

                if (metersByAccountList != null && !metersByAccountList.isEmpty()) {
                    //write All Meters List
                    UtilityMeterService.upsertMeterListForAccountProcessed(metersByAccountList, accountToProcess);

                    //check if needed for pagination to create queue items for the other pages
                    UrjanetUtils.createPaginationQueueItemFromAPIResponse(
                        meterResponse.page,
                        accountToProcess.Id,
                        UrjanetEnums.RequestType.METERS_BY_ACCOUNT.name(),
                        QueueItemProcessorFactory.getProcessorType(UtilityAccount__c.SObjectType)
                    );
                }
            }
        }

        return queueItem;
    }
}