force-app/main/default/objects/CountryCodeMapping__mdt/CountryCodeMapping__mdt.object-meta.xml
<CustomObject>
    <description>Mapping between 2-digit and 3-digit country codes.</description>
    <label>Country Code Mapping</label>
    <pluralLabel>Country Code Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/CountryCodeMapping__mdt/fields/CountryCode2Digit__c.field-meta.xml
<CustomField>
    <fullName>CountryCode2Digit__c</fullName>
    <description>Holds the ISO3166-1-Alpha-2 country code value</description>
    <label>Country Code 2 Letter</label>
    <length>2</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CountryCodeMapping__mdt/fields/CountryCode3Digit__c.field-meta.xml
<CustomField>
    <fullName>CountryCode3Digit__c</fullName>
    <description>Holds the ISO3166-1-Alpha-3 country code value</description>
    <label>Country Code 3 Letter</label>
    <length>3</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/StnryAssetEnvrSrc/fields/CreatedByInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>CreatedByInUrjanet__c</fullName>
    <description
    >A custom field for the system user responsible for creating the site in Arcadia&apos;s system.</description>
    <inlineHelpText>The system user responsible for creating the site in Arcadia&apos;s system.</inlineHelpText>
    <label>Created By in Arcadia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StnryAssetEnvrSrc/fields/CreatedDateInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>CreatedDateInUrjanet__c</fullName>
    <description>A custom field for the date the site was created in Arcadia&apos;s system.</description>
    <inlineHelpText>The date the site was created in Arcadia&apos;s system.</inlineHelpText>
    <label>Created Date in Arcadia</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/StnryAssetEnvrSrc/fields/LastModifiedByInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedByInUrjanet__c</fullName>
    <description>A custom field to store the system user responsible for modifying the site most recently.</description>
    <inlineHelpText>The system user responsible for modifying the site most recently.</inlineHelpText>
    <label>Last Modified By in Arcadia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StnryAssetEnvrSrc/fields/LastModifiedInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedInUrjanet__c</fullName>
    <description
    >A custom field to store the date that the site was last modified in Arcadia&apos;s system.</description>
    <inlineHelpText>The date that the site was last modified in Arcadia&apos;s system.</inlineHelpText>
    <label>Last Modified in Arcadia</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/StnryAssetEnvrSrc/fields/UrjanetId__c.field-meta.xml
<CustomField>
    <fullName>UrjanetId__c</fullName>
    <description
    >A custom field to store the Arcadia ID to make recredentialing and other API calls easier.</description>
    <externalId>true</externalId>
    <inlineHelpText
    >A custom field to store the Arcadia ID to make recredentialing and other API calls easier.</inlineHelpText>
    <label>ArcadiaId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/unpackaged/objects/StnryAssetEnvrSrc/recordTypes/Default.recordType-meta.xml
<RecordType>
    <fullName>Default</fullName>
    <active>true</active>
    <label>Default</label>
</RecordType>

force-app/main/default/objects/UtilityMeter__c/UtilityMeter__c.object-meta.xml
<CustomObject>
    <description>A custom object (created by the Urjanet Connect app) to store utility meter information</description>
    <label>Utility Meter</label>
    <nameField>
        <label>Utility Meter Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Meters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UtilityMeter__c/fields/CreatedDateInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>CreatedDateInUrjanet__c</fullName>
    <description>The Date the credential was registered in Arcadia’s system.</description>
    <inlineHelpText>The Date the credential was registered in Arcadia’s system.</inlineHelpText>
    <label>Created Date in Arcadia</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/UtilityMeter__c/fields/LastModifiedByInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedByInUrjanet__c</fullName>
    <description>The system user responsible for modifying a meter most recently in the Arcadia system.</description>
    <inlineHelpText
    >The system user responsible for modifying a meter most recently in the Arcadia system.</inlineHelpText>
    <label>Last Modified By in Arcadia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityMeter__c/fields/LastModifiedInUrjanet__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedInUrjanet__c</fullName>
    <description>The date that a meter was modified last in the Arcadia system.</description>
    <inlineHelpText>The date that a meter was modified last in the Arcadia system.</inlineHelpText>
    <label>Last Modified in Arcadia</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/UtilityMeter__c/fields/StationaryAssetEnvironmentalSource__c.field-meta.xml
<CustomField>
    <fullName>StationaryAssetEnvironmentalSource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Stationary Asset Environmental Source for this Utility Meter.</description>
    <inlineHelpText>The Stationary Asset Environmental Source for this Utility Meter.</inlineHelpText>
    <label>Stationary Asset Environmental Source</label>
    <referenceTo>StnryAssetEnvrSrc</referenceTo>
    <relationshipLabel>Utility Meters</relationshipLabel>
    <relationshipName>UtilityMeters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UtilityMeter__c/fields/UrjanetId__c.field-meta.xml
<CustomField>
    <fullName>UrjanetId__c</fullName>
    <description>Unique ID for the meter on Arcadia system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique ID for the meter on Arcadia system.</inlineHelpText>
    <label>ArcadiaId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/StationaryAssetSourceService.cls
@namespaceAccessible
public with sharing class StationaryAssetSourceService {
    @TestVisible
    @namespaceAccessible
    public static void upsertSiteList(List<StnryAssetEnvrSrc> stationaryAssetRecords) {
        if (!stationaryAssetRecords.isEmpty()) {
            try {
                // This will be running as a system process that should complete
                // no matter who kicked it off
                Database.DMLOptions option = new Database.DMLOptions();
                option.OptAllOrNone = false;
                Logger.getInstance()
                    .log(
                        StationaryAssetSourceService.class.getName(),
                        UrjanetUtils.getSObjectName(Schema.StnryAssetEnvrSrc.SObjectType),
                        Data.upsurt(
                            stationaryAssetRecords,
                            Schema.StnryAssetEnvrSrc.fields.UrjanetId__c,
                            option,
                            false,
                            false,
                            false,
                            null
                        )
                    );
            } catch (DmlException e) {
                Logger.getInstance(false).log(StationaryAssetSourceService.class.getName(), e);
            }
        }
    }

    @namespaceAccessible
    public static void updateSiteDetailsFromResponse(PostSiteResponse site, Id siteId) {
        try {
            StnryAssetEnvrSrc stationaryAsset = toObject(site);
            stationaryAsset.Id = siteId;
            // This will be running as a system process that should complete
            // no matter who kicked it off
            Database.DMLOptions option = new Database.DMLOptions();
            option.OptAllOrNone = false;
            Logger.getInstance()
                .log(
                    StationaryAssetSourceService.class.getName(),
                    UrjanetUtils.getSObjectName(Schema.StnryAssetEnvrSrc.SObjectType),
                    Data.upsurt(
                        new List<sObject>{ stationaryAsset },
                        Schema.StnryAssetEnvrSrc.fields.UrjanetId__c,
                        option,
                        false,
                        false,
                        false,
                        null
                    )
                );
            updateMeterSiteLink(stationaryAsset);
        } catch (DmlException e) {
            Logger.getInstance(false).log(StationaryAssetSourceService.class.getName(), e);
        }
    }

    private static void updateMeterSiteLink(StnryAssetEnvrSrc stationaryAsset) {
        List<UtilityMeter__c> meters = [
            SELECT Id, StationaryAssetEnvironmentalSource__c
            FROM UtilityMeter__c
            WHERE StationaryAssetEnvironmentalSource__c = :stationaryAsset.Id
        ];
        if (meters != null && !meters.isEmpty()) {
            // Create queue to hit API for Meter Site Link Update
            List<Database.SaveResult> saveResults = new QueueItemsBuilder(meters, SiteUpdateProcessor.class)
                .buildQueueItemsPerRecord()
                .createRecords();
            UrjanetUtils.logFailures(
                UtilityMeterService.class.getName(),
                String.valueOf(UtilityMeter__c.SObjectType),
                saveResults
            );
        }
    }

    @TestVisible
    private static StnryAssetEnvrSrc toObject(PostSiteResponse site) {
        StnryAssetEnvrSrc stationaryAssetSrc = new StnryAssetEnvrSrc();
        stationaryAssetSrc.CreatedDateInUrjanet__c = UrjanetUtils.getDateTime(site.createdDate);
        stationaryAssetSrc.CreatedByInUrjanet__c = site.createdBy;
        stationaryAssetSrc.LastModifiedInUrjanet__c = UrjanetUtils.getDateTime(site.lastModifiedDate);
        stationaryAssetSrc.LastModifiedByInUrjanet__c = site.lastModifiedBy;
        stationaryAssetSrc.UrjanetId__c = site.entityId;
        stationaryAssetSrc.LastUrjanetSyncDateTime__c = Datetime.now();
        return stationaryAssetSrc;
    }

    //default constructor
    @namespaceAccessible
    public StationaryAssetSourceService() {
    }

    @AuraEnabled
    public static void createQueueItemsToSendStationaryAssetSource() {
        // This will be running as a system process that should complete
        // no matter who kicked it off
        Logger.getInstance(false)
            .log(StationaryAssetSourceService.class.getName(), Logger.Level.INFO, 'Push Sites process Started');
        List<StnryAssetEnvrSrc> sitesToCreate = (List<StnryAssetEnvrSrc>) new StationaryAssetSourceSelector(
                false,
                false,
                false
            )
            .getRecordsToCreateSites();
        List<Database.SaveResult> saveResults = new QueueItemsBuilder(sitesToCreate, SiteCreateProcessor.class)
            .buildQueueItemsPerRecord()
            .createRecords();
        UrjanetUtils.logFailures(
            StationaryAssetSourceService.class.getName(),
            String.valueOf(StnryAssetEnvrSrc.SObjectType),
            saveResults
        );
        Logger.getInstance(false)
            .log(
                StationaryAssetSourceService.class.getName(),
                Logger.Level.INFO,
                'QueueItems Successfully Created for Sites Processing'
            );
    }

    @namespaceAccessible
    public static String mapToSalesforceCountryCode(String countryCode) {
        String countryValue = countryCode;
        if (countryCode != null) {
            Map<String, CountryCodeMapping__mdt> countryMap = CountryCodeMapping__mdt.getAll();

            for (String nameCountry : countryMap.keySet()) {
                if (
                    countryCode.length() == 3 &&
                    countryCode.toUpperCase() == countryMap.get(nameCountry).CountryCode3Digit__c.toUpperCase()
                ) {
                    countryValue = countryMap.get(nameCountry).CountryCode2Digit__c;
                    break;
                }
            }
        }
        return countryValue;
    }

    @namespaceAccessible
    public static String mapToUrjanetCountryCode(String countryCode) {
        String countryValue = countryCode;

        if (countryCode != null) {
            Map<String, CountryCodeMapping__mdt> countryMap = CountryCodeMapping__mdt.getAll();
            for (String nameCountry : countryMap.keySet()) {
                if (
                    countryCode.length() == 2 &&
                    countryCode.toUpperCase() == countryMap.get(nameCountry).CountryCode2Digit__c.toUpperCase()
                ) {
                    countryValue = countryMap.get(nameCountry).CountryCode3Digit__c;
                    break;
                }
            }
        }
        return countryValue;
    }
}