force-app/main/default/objects/UtilityMeterUsageUpdaterSetting__mdt/UtilityMeterUsageUpdaterSetting__mdt.object-meta.xml
<CustomObject>
    <description>Custom Metadata used to store the Updater class name to be used for each service type</description>
    <label>Utility Meter Usage Updater Setting</label>
    <pluralLabel>Utility Meter Usage Updater Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/UtilityMeterUsageUpdaterSetting__mdt/fields/ServiceType__c.field-meta.xml
<CustomField>
    <fullName>ServiceType__c</fullName>
    <description>Urjanet Service Type</description>
    <inlineHelpText>Urjanet Service Type</inlineHelpText>
    <label>Service Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UtilityMeterUsageUpdaterSetting__mdt/fields/UpdaterClassName__c.field-meta.xml
<CustomField>
    <fullName>UpdaterClassName__c</fullName>
    <description>Salesforce Updater Class Name</description>
    <inlineHelpText>Salesforce Updater Class Name</inlineHelpText>
    <label>Updater Class Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ServiceToUpdaterTypeMappingSelector.cls
public with sharing class ServiceToUpdaterTypeMappingSelector extends Selector {
    public ServiceToUpdaterTypeMappingSelector() {
        super(Schema.UtilityMeterUsageUpdaterSetting__mdt.SObjectType);
    }
    public ServiceToUpdaterTypeMappingSelector(Boolean enforceCRUD, Boolean enforceFLS, Boolean enforceShr) {
        super(Schema.UtilityMeterUsageUpdaterSetting__mdt.SObjectType, enforceCRUD, enforceFLS, enforceShr);
    }

    /**
     * Returns a Set that has all of the default fields.
     * @return   Set of Strings that contain the default fields for this object
     */
    public override Set<String> getDefaultFields() {
        return new Set<String>{ 'Id', 'DeveloperName', 'UpdaterClassName__c', 'ServiceType__c' };
    }
}